// Entry point: parse enums and misc first (their types are referenced by
// message families), then each requested family, emitting one kmsg file
// per input plus the all-types smoke test.
module main

import os

struct FamilyOut {
	out_name string
	types    []TopType
}

struct TopType {
	name        string
	max_version int
	key         int
}

// out_file_name strips the numeric ordering prefix: 03_metadata -> metadata.v
fn out_file_name(fam string) string {
	if idx := fam.index('_') {
		if all_digits(fam[..idx]) {
			return fam[idx + 1..] + '.v'
		}
	}
	return fam + '.v'
}

fn emit_smoke_test(families []FamilyOut) string {
	mut sorted_fams := families.clone()
	sorted_fams.sort(a.out_name < b.out_name)

	mut l := []string{}
	l << '// Generated smoke test: round-trips every kmsg type at every wire'
	l << '// version with default (zero-value) structs, catching any asymmetry'
	l << '// between write_to and read_from version gating.'
	l << 'module kmsg'
	l << ''
	l << 'import kbin'
	l << ''
	l << '// Each V _test.v file compiles as its own program, so the roundtrip'
	l << '// helper is duplicated here rather than shared from kmsg_test.v.'
	l << 'fn smoke_roundtrip[T](orig T) {'
	l << '\tmut w := kbin.Writer{}'
	l << '\torig.write_to(mut w)'
	l << '\tmut got := T{'
	l << '\t\tversion: orig.version'
	l << '\t}'
	l << '\tmut r := kbin.Reader{'
	l << '\t\tsrc: w.buf'
	l << '\t}'
	l << '\tgot.read_from(mut r) or {'
	l << '\t\t' + r"assert false, '${T.name} v${orig.version} decode failed: ${err}'"
	l << '\t\treturn'
	l << '\t}'
	l << '\t' + r"assert r.remaining() == 0, '${T.name} v${orig.version} trailing bytes'"
	l << '\tmut w2 := kbin.Writer{}'
	l << '\tgot.write_to(mut w2)'
	l << '\t' + r"assert w2.buf == w.buf, '${T.name} v${orig.version} re-encode mismatch'"
	l << '}'
	l << ''
	l << 'fn test_all_messages_all_versions_default_roundtrip() {'
	for fam in sorted_fams {
		for t in fam.types {
			l << '\tfor version in i16(0) .. i16(${t.max_version + 1}) {'
			l << '\t\tsmoke_roundtrip(${t.name}{'
			l << '\t\t\tversion: version'
			l << '\t\t})'
			l << '\t}'
		}
	}
	l << '}'
	return l.join('\n') + '\n'
}

fn main() {
	if os.args.len < 4 {
		eprintln('usage: v run generate/ <definitions_dir> <out_dir> <family_files...>')
		exit(1)
	}
	defs_dir := os.args[1]
	out_dir := os.args[2]
	families := os.args[3..].filter(it != 'enums' && it != 'misc')

	mut g := Generator{}

	// enums and misc come first: families reference their types
	enums_path := os.join_path(defs_dir, 'enums')
	if os.exists(enums_path) {
		g.parse_enums(enums_path) or {
			eprintln('enums: ${err.msg()}')
			exit(1)
		}
		mut enum_defs := g.enums.values()
		enum_defs.sort(a.name < b.name)
		os.write_file(os.join_path(out_dir, 'enums.v'), emit_enums_file(enum_defs)) or {
			eprintln('enums.v: write failed: ${err.msg()}')
			exit(1)
		}
		println('enums -> enums.v: ${enum_defs.len} enums')
	}

	mut all_fams := []string{}
	misc_path := os.join_path(defs_dir, 'misc')
	if os.exists(misc_path) {
		all_fams << 'misc'
	}
	all_fams << families

	mut outs := []FamilyOut{}
	for fam in all_fams {
		path := os.join_path(defs_dir, fam)
		structs := g.parse_family(path) or {
			eprintln('${fam}: ${err.msg()}')
			exit(1)
		}
		out_name := out_file_name(fam)
		code := emit_file(structs, fam) or {
			eprintln('${fam}: ${err.msg()}')
			exit(1)
		}
		os.write_file(os.join_path(out_dir, out_name), code) or {
			eprintln('${fam}: write failed: ${err.msg()}')
			exit(1)
		}
		tops := structs.filter(it.top_level)
		outs << FamilyOut{
			out_name: out_name
			types:    tops.map(TopType{
				name:        it.name
				max_version: it.max_version
				key:         it.key
			})
		}
		names := tops.map(it.name)
		println('${fam} -> ${out_name}: ${names}, ${structs.len} structs total')
	}

	keys := emit_keys_file(outs)
	os.write_file(os.join_path(out_dir, 'keys.v'), keys) or {
		eprintln('keys.v: write failed: ${err.msg()}')
		exit(1)
	}

	smoke := emit_smoke_test(outs)
	os.write_file(os.join_path(out_dir, 'smoke_test.v'), smoke) or {
		eprintln('smoke_test.v: write failed: ${err.msg()}')
		exit(1)
	}
	total := outs.map(it.types.len)
	mut n := 0
	for c in total {
		n += c
	}
	println('smoke_test.v: ${n} top-level types')
}

// emit_keys_file renders the API key registry: key -> human name.
fn emit_keys_file(families []FamilyOut) string {
	mut reqs := []TopType{}
	for fam in families {
		for t in fam.types {
			if t.name.ends_with('Request') && t.key >= 0 {
				reqs << t
			}
		}
	}
	reqs.sort(a.key < b.key)
	mut l := []string{}
	l << '// Code generated by `v run generate/` — DO NOT EDIT.'
	l << 'module kmsg'
	l << ''
	l << '// name_for_key returns the name of the API that a key belongs to,'
	l << "// or 'Unknown' if the key is unknown."
	l << 'pub fn name_for_key(key i16) string {'
	l << '\treturn match key {'
	for t in reqs {
		name := t.name#[..t.name.len - 'Request'.len]
		l << "\t\t${t.key} { '${name}' }"
	}
	l << "\t\telse { 'Unknown' }"
	l << '\t}'
	l << '}'
	l << ''
	l << '// max_key is the highest known API key.'
	l << 'pub const max_key = i16(${reqs.last().key})'
	return l.join('\n') + '\n'
}
