module kbin

// Golden vectors below were generated by an independent Python
// implementation of the Kafka/protobuf zig-zag varint spec, so these tests
// check the implementation against the wire format, not against itself.

const varint_vectors = {
	0:           [u8(0x00)]
	-1:          [u8(0x01)]
	1:           [u8(0x02)]
	-2:          [u8(0x03)]
	2:           [u8(0x04)]
	63:          [u8(0x7e)]
	-64:         [u8(0x7f)]
	64:          [u8(0x80), 0x01]
	-65:         [u8(0x81), 0x01]
	300:         [u8(0xd8), 0x04]
	-300:        [u8(0xd7), 0x04]
	8191:        [u8(0xfe), 0x7f]
	-8192:       [u8(0xff), 0x7f]
	8192:        [u8(0x80), 0x80, 0x01]
	1048575:     [u8(0xfe), 0xff, 0x7f]
	-1048576:    [u8(0xff), 0xff, 0x7f]
	134217727:   [u8(0xfe), 0xff, 0xff, 0x7f]
	-134217728:  [u8(0xff), 0xff, 0xff, 0x7f]
	2147483647:  [u8(0xfe), 0xff, 0xff, 0xff, 0x0f]
	-2147483648: [u8(0xff), 0xff, 0xff, 0xff, 0x0f]
}

const varlong_vectors = {
	i64(0):                    [u8(0x00)]
	i64(-1):                   [u8(0x01)]
	i64(1):                    [u8(0x02)]
	i64(-2):                   [u8(0x03)]
	i64(300):                  [u8(0xd8), 0x04]
	i64(-300):                 [u8(0xd7), 0x04]
	i64(2147483647):           [u8(0xfe), 0xff, 0xff, 0xff, 0x0f]
	i64(-2147483648):          [u8(0xff), 0xff, 0xff, 0xff, 0x0f]
	i64(2147483648):           [u8(0x80), 0x80, 0x80, 0x80, 0x10]
	i64(-2147483649):          [u8(0x81), 0x80, 0x80, 0x80, 0x10]
	i64(1000000000000000):     [u8(0x80), 0x80, 0xb4, 0xcc, 0xd4, 0xdf, 0xc6, 0x03]
	i64(-1000000000000000):    [u8(0xff), 0xff, 0xb3, 0xcc, 0xd4, 0xdf, 0xc6, 0x03]
	i64(9223372036854775807):  [u8(0xfe), 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x01]
	i64(-9223372036854775808): [u8(0xff), 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x01]
}

// xorshift64 gives deterministic pseudo-random values without depending on
// the rand module's seeding API.
struct Rng {
mut:
	state u64 = 0x9e3779b97f4a7c15
}

fn (mut r Rng) next() u64 {
	mut x := r.state
	x ^= x << 13
	x ^= x >> 7
	x ^= x << 17
	r.state = x
	return x
}

fn test_varint_golden_vectors() {
	for val, want in varint_vectors {
		mut w := Writer{}
		w.write_varint(val)
		assert w.buf == want, 'write_varint(${val})'
		assert varint_len(val) == want.len, 'varint_len(${val})'
		dec, n := varint(want)
		assert n == want.len, 'varint(${val}) len'
		assert dec == val, 'varint(${val}) value'
	}
}

fn test_varlong_golden_vectors() {
	for val, want in varlong_vectors {
		mut w := Writer{}
		w.write_varlong(val)
		assert w.buf == want, 'write_varlong(${val})'
		assert varlong_len(val) == want.len, 'varlong_len(${val})'
		dec, n := varlong(want)
		assert n == want.len, 'varlong(${val}) len'
		assert dec == val, 'varlong(${val}) value'
	}
}

fn test_uvarint_boundaries() {
	// every length transition: 2^7k - 1 and 2^7k
	for k in 1 .. 5 {
		lo := u32(1) << (7 * k) - 1
		hi := u32(1) << (7 * k)
		assert uvarint_len(lo) == k
		assert uvarint_len(hi) == k + 1
		for u in [lo, hi] {
			mut w := Writer{}
			w.write_uvarint(u)
			assert w.buf.len == uvarint_len(u)
			dec, n := uvarint(w.buf)
			assert n == w.buf.len
			assert dec == u
		}
	}
	assert uvarint_len(0) == 1
	assert uvarint_len(0xffffffff) == 5
}

fn test_varint_decode_errors() {
	// truncated: high bit set but no continuation available
	_, n1 := uvarint([u8(0x80)])
	assert n1 == 0
	_, n2 := uvarint([]u8{})
	assert n2 == 0
	// overflow: 5th byte with more than 4 low bits set
	_, n3 := uvarint([u8(0xff), 0xff, 0xff, 0xff, 0x10])
	assert n3 == -5
	// varlong overflow: 10th byte with more than the low bit set
	_, n4 := uvarlong([u8(0xff), 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x02])
	assert n4 == -10
	// max valid 5-byte uvarint
	dec, n5 := uvarint([u8(0xff), 0xff, 0xff, 0xff, 0x0f])
	assert n5 == 5
	assert dec == u32(0xffffffff)
}

fn test_varint_random_roundtrip() {
	mut rng := Rng{}
	for _ in 0 .. 2000 {
		// varints carry int32s; int is 64 bits wide on 64-bit targets, so
		// narrow through i32 to stay in the wire range
		i := int(i32(rng.next()))
		mut w := Writer{}
		w.write_varint(i)
		assert w.buf.len == varint_len(i)
		dec, n := varint(w.buf)
		assert n == w.buf.len
		assert dec == i

		l := i64(rng.next())
		mut lw := Writer{}
		lw.write_varlong(l)
		assert lw.buf.len == varlong_len(l)
		ldec, ln := varlong(lw.buf)
		assert ln == lw.buf.len
		assert ldec == l
	}
}

fn test_fixed_width_byte_order() {
	mut w := Writer{}
	w.write_int16(i16(0x0102))
	w.write_int32(0x03040506)
	w.write_int64(i64(0x0708090a0b0c0d0e))
	w.write_uint16(u16(0xfffe))
	w.write_uint32(u32(0xdeadbeef))
	assert w.buf == [u8(0x01), 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c,
		0x0d, 0x0e, 0xff, 0xfe, 0xde, 0xad, 0xbe, 0xef]

	mut r := Reader{
		src: w.buf
	}
	assert r.read_int16() == i16(0x0102)
	assert r.read_int32() == 0x03040506
	assert r.read_int64() == i64(0x0708090a0b0c0d0e)
	assert r.read_uint16() == u16(0xfffe)
	assert r.read_uint32() == u32(0xdeadbeef)
	assert r.remaining() == 0
	r.complete() or { assert false, 'reader should be complete: ${err}' }

	// negative int32s must sign-extend: -1 is the null length marker
	mut nw := Writer{}
	nw.write_int32(-1)
	nw.write_int32(-2147483648)
	assert nw.buf == [u8(0xff), 0xff, 0xff, 0xff, 0x80, 0x00, 0x00, 0x00]
	mut nr := Reader{
		src: nw.buf
	}
	assert nr.read_int32() == -1
	assert nr.read_int32() == -2147483648
	assert nr.ok()
}

fn test_fixed_width_random_roundtrip() {
	mut rng := Rng{}
	for _ in 0 .. 500 {
		b := rng.next() & 1 == 1
		i8v := i8(rng.next())
		i16v := i16(rng.next())
		i32v := int(i32(rng.next()))
		i64v := i64(rng.next())
		u16v := u16(rng.next())
		u32v := u32(rng.next())
		f64v := f64(i64(rng.next())) / 7.0

		mut w := Writer{}
		w.write_bool(b)
		w.write_int8(i8v)
		w.write_int16(i16v)
		w.write_int32(i32v)
		w.write_int64(i64v)
		w.write_uint16(u16v)
		w.write_uint32(u32v)
		w.write_float64(f64v)

		mut r := Reader{
			src: w.buf
		}
		assert r.read_bool() == b
		assert r.read_int8() == i8v
		assert r.read_int16() == i16v
		assert r.read_int32() == i32v
		assert r.read_int64() == i64v
		assert r.read_uint16() == u16v
		assert r.read_uint32() == u32v
		assert r.read_float64() == f64v
		assert r.ok()
		assert r.remaining() == 0
	}
}

fn test_float64_special_values() {
	specials := [f64(0.0), -0.0, 1.5, -1.5, 1e308, -1e308, 5e-324]
	for f in specials {
		mut w := Writer{}
		w.write_float64(f)
		assert w.buf.len == 8
		mut r := Reader{
			src: w.buf
		}
		assert r.read_float64() == f
	}
}

fn test_strings_and_compact_strings() {
	// exact wire bytes: 'my-topic' compact = uvarint(9) + bytes (Python golden)
	mut cw := Writer{}
	cw.write_compact_string('my-topic')
	assert cw.buf == [u8(0x09), 0x6d, 0x79, 0x2d, 0x74, 0x6f, 0x70, 0x69, 0x63]

	// int16-prefixed string wire bytes
	mut sw := Writer{}
	sw.write_string('ab')
	assert sw.buf == [u8(0x00), 0x02, 0x61, 0x62]

	for s in ['', 'a', 'hello world', 'unicode: héllo κόσμε', 'x'.repeat(200)] {
		mut w := Writer{}
		w.write_string(s)
		w.write_compact_string(s)
		w.write_varint_string(s)
		mut r := Reader{
			src: w.buf
		}
		assert r.read_string() == s
		assert r.read_compact_string() == s
		assert r.read_varint_string() == s
		assert r.ok()
		assert r.remaining() == 0
	}
}

fn test_nullable_strings() {
	// null encodings: int16(-1) and uvarint(0)
	mut nw := Writer{}
	nw.write_nullable_string(none)
	assert nw.buf == [u8(0xff), 0xff]
	mut cnw := Writer{}
	cnw.write_compact_nullable_string(none)
	assert cnw.buf == [u8(0x00)]

	mut w := Writer{}
	w.write_nullable_string('present')
	w.write_nullable_string(none)
	w.write_compact_nullable_string('also-present')
	w.write_compact_nullable_string(none)
	w.write_nullable_string('') // empty is NOT null

	mut r := Reader{
		src: w.buf
	}
	s1 := r.read_nullable_string() or { '<none>' }
	assert s1 == 'present'
	if _ := r.read_nullable_string() {
		assert false, 'expected none'
	}
	s2 := r.read_compact_nullable_string() or { '<none>' }
	assert s2 == 'also-present'
	if _ := r.read_compact_nullable_string() {
		assert false, 'expected none'
	}
	s3 := r.read_nullable_string() or { '<none>' }
	assert s3 == ''
	assert r.ok()
	assert r.remaining() == 0
}

fn test_bytes_variants() {
	payload := [u8(0x00), 0x01, 0xfe, 0xff]
	mut w := Writer{}
	w.write_bytes(payload)
	w.write_compact_bytes(payload)
	w.write_nullable_bytes(payload)
	w.write_nullable_bytes(none)
	w.write_compact_nullable_bytes(payload)
	w.write_compact_nullable_bytes(none)
	w.write_varint_bytes(payload)
	w.write_varint_bytes(none)

	mut r := Reader{
		src: w.buf
	}
	assert r.read_bytes() == payload
	assert r.read_compact_bytes() == payload
	b1 := r.read_nullable_bytes() or { []u8{} }
	assert b1 == payload
	if _ := r.read_nullable_bytes() {
		assert false, 'expected none'
	}
	b2 := r.read_compact_nullable_bytes() or { []u8{} }
	assert b2 == payload
	if _ := r.read_compact_nullable_bytes() {
		assert false, 'expected none'
	}
	b3 := r.read_varint_bytes() or { []u8{} }
	assert b3 == payload
	if _ := r.read_varint_bytes() {
		assert false, 'expected none'
	}
	assert r.ok()
	assert r.remaining() == 0
}

fn test_bytes_eventhubs_workaround() {
	// non-nullable bytes with -1 length decode as empty, not an error
	// (franz-go workaround for Microsoft EventHubs)
	mut w := Writer{}
	w.write_int32(-1)
	mut r := Reader{
		src: w.buf
	}
	assert r.read_bytes() == []u8{}
	assert r.ok()

	mut cw := Writer{}
	cw.write_uvarint(0) // compact -1
	mut cr := Reader{
		src: cw.buf
	}
	assert cr.read_compact_bytes() == []u8{}
	assert cr.ok()
}

fn test_array_lens() {
	mut w := Writer{}
	w.write_array_len(3)
	w.write_compact_array_len(3)
	w.write_nullable_array_len(3, true)
	w.write_compact_nullable_array_len(3, true)
	assert w.buf == [u8(0x00), 0x00, 0x00, 0x03, 0x04, 0xff, 0xff, 0xff, 0xff, 0x00]

	// read_array_len guards: a claimed length larger than remaining is bad
	mut bad := Writer{}
	bad.write_array_len(1000)
	mut r := Reader{
		src: bad.buf
	}
	assert r.read_array_len() == 0
	assert !r.ok()

	// a sane length passes
	mut good := Writer{}
	good.write_array_len(2)
	good.write_int8(1)
	good.write_int8(2)
	mut r2 := Reader{
		src: good.buf
	}
	assert r2.read_array_len() == 2
	assert r2.read_int8() == 1
	assert r2.read_int8() == 2
	assert r2.ok()

	// compact and varint variants guard too
	mut bad2 := Writer{}
	bad2.write_compact_array_len(50)
	mut r3 := Reader{
		src: bad2.buf
	}
	assert r3.read_compact_array_len() == 0
	assert !r3.ok()

	mut bad3 := Writer{}
	bad3.write_varint(50)
	mut r4 := Reader{
		src: bad3.buf
	}
	assert r4.read_varint_array_len() == 0
	assert !r4.ok()
}

fn test_uuid_roundtrip() {
	mut uuid := [16]u8{}
	for i in 0 .. 16 {
		uuid[i] = u8(i * 17)
	}
	mut w := Writer{}
	w.write_uuid(uuid)
	assert w.buf.len == 16
	mut r := Reader{
		src: w.buf
	}
	got := r.read_uuid()
	assert got == uuid
	assert r.ok()
}

fn test_reader_invalidation_semantics() {
	// truncated int32
	mut r := Reader{
		src: [u8(0x00), 0x01]
	}
	assert r.read_int32() == 0
	assert !r.ok()
	r.complete() or {
		// the error is a typed struct, not a string to compare
		assert err is NotEnoughDataError
		// after invalidation, everything returns zero values
		assert r.read_int64() == 0
		assert r.read_string() == ''
		assert r.read_bool() == false
		assert r.span(1) == []u8{}
		return
	}
	assert false, 'complete() should have errored'
}

fn test_reader_string_truncation() {
	// string claims 10 bytes but only 3 present
	mut w := Writer{}
	w.write_int16(10)
	w.buf << 'abc'.bytes()
	mut r := Reader{
		src: w.buf
	}
	assert r.read_string() == ''
	assert !r.ok()
}

fn test_span_negative() {
	mut r := Reader{
		src: [u8(1), 2, 3]
	}
	assert r.span(-1) == []u8{}
	assert !r.ok()
}

fn test_mixed_message_roundtrip() {
	// simulate a small request body mixing everything, like generated kmsg
	// code will
	mut rng := Rng{}
	for _ in 0 .. 200 {
		topic := 'topic-${rng.next() % 1000}'
		partition := int(rng.next() % 64)
		offset := i64(rng.next())
		key := ?[]u8([u8(1), u8(rng.next()), 3])

		mut w := Writer{}
		w.write_compact_string(topic)
		w.write_int32(partition)
		w.write_int64(offset)
		w.write_varint_bytes(key)
		w.write_compact_array_len(1)
		w.write_int16(0) // error code
		w.write_uvarint(0) // empty tag section

		mut r := Reader{
			src: w.buf
		}
		assert r.read_compact_string() == topic
		assert r.read_int32() == partition
		assert r.read_int64() == offset
		k := r.read_varint_bytes() or { []u8{} }
		kexp := key or { []u8{} }
		assert k == kexp
		assert r.read_compact_array_len() == 1
		assert r.read_int16() == 0
		assert r.read_uvarint() == 0
		assert r.ok()
		assert r.remaining() == 0
	}
}
