// Code generated by `v run generate/` from
// franz-go generate/definitions/25_add_offsets_to_txn — DO NOT EDIT.
module kmsg

import kbin

pub struct AddOffsetsToTxnRequest {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version          i16
	transactional_id string
	producer_id      i64
	producer_epoch   i16
	group            string
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of AddOffsetsToTxnRequest (25).
pub fn (m &AddOffsetsToTxnRequest) key() i16 {
	return 25
}

// max_version returns the maximum wire version this client supports.
pub fn (m &AddOffsetsToTxnRequest) max_version() i16 {
	return 4
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &AddOffsetsToTxnRequest) is_flexible() bool {
	return m.version >= 3
}

// write_to encodes m at m.version into w.
pub fn (m &AddOffsetsToTxnRequest) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &AddOffsetsToTxnRequest) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_string(m.transactional_id)
	} else {
		w.write_string(m.transactional_id)
	}
	w.write_int64(m.producer_id)
	w.write_int16(m.producer_epoch)
	if flexible {
		w.write_compact_string(m.group)
	} else {
		w.write_string(m.group)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = AddOffsetsToTxnRequest{version: v}).
pub fn (mut m AddOffsetsToTxnRequest) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m AddOffsetsToTxnRequest) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	if flexible {
		m.transactional_id = r.read_compact_string()
	} else {
		m.transactional_id = r.read_string()
	}
	m.producer_id = r.read_int64()
	m.producer_epoch = r.read_int16()
	if flexible {
		m.group = r.read_compact_string()
	} else {
		m.group = r.read_string()
	}
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct AddOffsetsToTxnResponse {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version         i16
	throttle_millis int
	error_code      i16
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of AddOffsetsToTxnResponse (25).
pub fn (m &AddOffsetsToTxnResponse) key() i16 {
	return 25
}

// max_version returns the maximum wire version this client supports.
pub fn (m &AddOffsetsToTxnResponse) max_version() i16 {
	return 4
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &AddOffsetsToTxnResponse) is_flexible() bool {
	return m.version >= 3
}

// write_to encodes m at m.version into w.
pub fn (m &AddOffsetsToTxnResponse) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &AddOffsetsToTxnResponse) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int32(m.throttle_millis)
	w.write_int16(m.error_code)
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = AddOffsetsToTxnResponse{version: v}).
pub fn (mut m AddOffsetsToTxnResponse) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m AddOffsetsToTxnResponse) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	m.throttle_millis = r.read_int32()
	m.error_code = r.read_int16()
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}
