// Code generated by `v run generate/` from
// franz-go generate/definitions/67_allocate_producer_ids — DO NOT EDIT.
module kmsg

import kbin

pub struct AllocateProducerIDsRequest {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version      i16
	broker_id    int
	broker_epoch i64 = i64(-1)
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of AllocateProducerIDsRequest (67).
pub fn (m &AllocateProducerIDsRequest) key() i16 {
	return 67
}

// max_version returns the maximum wire version this client supports.
pub fn (m &AllocateProducerIDsRequest) max_version() i16 {
	return 0
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &AllocateProducerIDsRequest) is_flexible() bool {
	return m.version >= 0
}

// write_to encodes m at m.version into w.
pub fn (m &AllocateProducerIDsRequest) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &AllocateProducerIDsRequest) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int32(m.broker_id)
	w.write_int64(m.broker_epoch)
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = AllocateProducerIDsRequest{version: v}).
pub fn (mut m AllocateProducerIDsRequest) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m AllocateProducerIDsRequest) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	m.broker_id = r.read_int32()
	m.broker_epoch = r.read_int64()
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct AllocateProducerIDsResponse {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version           i16
	throttle_millis   int
	error_code        i16
	producer_id_start i64
	producer_id_len   int
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of AllocateProducerIDsResponse (67).
pub fn (m &AllocateProducerIDsResponse) key() i16 {
	return 67
}

// max_version returns the maximum wire version this client supports.
pub fn (m &AllocateProducerIDsResponse) max_version() i16 {
	return 0
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &AllocateProducerIDsResponse) is_flexible() bool {
	return m.version >= 0
}

// write_to encodes m at m.version into w.
pub fn (m &AllocateProducerIDsResponse) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &AllocateProducerIDsResponse) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int32(m.throttle_millis)
	w.write_int16(m.error_code)
	w.write_int64(m.producer_id_start)
	w.write_int32(m.producer_id_len)
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = AllocateProducerIDsResponse{version: v}).
pub fn (mut m AllocateProducerIDsResponse) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m AllocateProducerIDsResponse) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	m.throttle_millis = r.read_int32()
	m.error_code = r.read_int16()
	m.producer_id_start = r.read_int64()
	m.producer_id_len = r.read_int32()
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}
