// Code generated by `v run generate/` from
// franz-go generate/definitions/49_alter_client_quotas — DO NOT EDIT.
module kmsg

import kbin

pub struct AlterClientQuotasRequestEntryEntity {
pub mut:
	type_ string
	name  ?string
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &AlterClientQuotasRequestEntryEntity) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_string(m.type_)
	} else {
		w.write_string(m.type_)
	}
	if flexible {
		w.write_compact_nullable_string(m.name)
	} else {
		w.write_nullable_string(m.name)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m AlterClientQuotasRequestEntryEntity) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	if flexible {
		m.type_ = r.read_compact_string()
	} else {
		m.type_ = r.read_string()
	}
	if flexible {
		m.name = r.read_compact_nullable_string()
	} else {
		m.name = r.read_nullable_string()
	}
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct AlterClientQuotasRequestEntryOp {
pub mut:
	key    string
	value  f64
	remove bool
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &AlterClientQuotasRequestEntryOp) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_string(m.key)
	} else {
		w.write_string(m.key)
	}
	w.write_float64(m.value)
	w.write_bool(m.remove)
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m AlterClientQuotasRequestEntryOp) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	if flexible {
		m.key = r.read_compact_string()
	} else {
		m.key = r.read_string()
	}
	m.value = r.read_float64()
	m.remove = r.read_bool()
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct AlterClientQuotasRequestEntry {
pub mut:
	entity []AlterClientQuotasRequestEntryEntity
	ops    []AlterClientQuotasRequestEntryOp
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &AlterClientQuotasRequestEntry) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	arr_entity := m.entity
	if flexible {
		w.write_compact_array_len(arr_entity.len)
	} else {
		w.write_array_len(arr_entity.len)
	}
	for item_entity in arr_entity {
		item_entity.write_to_versioned(mut w, version, flexible)
	}
	arr_ops := m.ops
	if flexible {
		w.write_compact_array_len(arr_ops.len)
	} else {
		w.write_array_len(arr_ops.len)
	}
	for item_ops in arr_ops {
		item_ops.write_to_versioned(mut w, version, flexible)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m AlterClientQuotasRequestEntry) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_entity := []AlterClientQuotasRequestEntryEntity{cap: if arr_len > 0 {
		arr_len
	} else {
		0
	}}
	for _ in 0 .. arr_len {
		mut item_entity := AlterClientQuotasRequestEntryEntity{}
		item_entity.read_from_versioned(mut r, version, flexible)!
		arr_entity << item_entity
	}
	m.entity = arr_entity
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_ops := []AlterClientQuotasRequestEntryOp{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_ops := AlterClientQuotasRequestEntryOp{}
		item_ops.read_from_versioned(mut r, version, flexible)!
		arr_ops << item_ops
	}
	m.ops = arr_ops
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct AlterClientQuotasRequest {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version       i16
	entries       []AlterClientQuotasRequestEntry
	validate_only bool
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of AlterClientQuotasRequest (49).
pub fn (m &AlterClientQuotasRequest) key() i16 {
	return 49
}

// max_version returns the maximum wire version this client supports.
pub fn (m &AlterClientQuotasRequest) max_version() i16 {
	return 1
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &AlterClientQuotasRequest) is_flexible() bool {
	return m.version >= 1
}

// write_to encodes m at m.version into w.
pub fn (m &AlterClientQuotasRequest) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &AlterClientQuotasRequest) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	arr_entries := m.entries
	if flexible {
		w.write_compact_array_len(arr_entries.len)
	} else {
		w.write_array_len(arr_entries.len)
	}
	for item_entries in arr_entries {
		item_entries.write_to_versioned(mut w, version, flexible)
	}
	w.write_bool(m.validate_only)
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = AlterClientQuotasRequest{version: v}).
pub fn (mut m AlterClientQuotasRequest) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m AlterClientQuotasRequest) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_entries := []AlterClientQuotasRequestEntry{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_entries := AlterClientQuotasRequestEntry{}
		item_entries.read_from_versioned(mut r, version, flexible)!
		arr_entries << item_entries
	}
	m.entries = arr_entries
	m.validate_only = r.read_bool()
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct AlterClientQuotasResponseEntryEntity {
pub mut:
	type_ string
	name  ?string
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &AlterClientQuotasResponseEntryEntity) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_string(m.type_)
	} else {
		w.write_string(m.type_)
	}
	if flexible {
		w.write_compact_nullable_string(m.name)
	} else {
		w.write_nullable_string(m.name)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m AlterClientQuotasResponseEntryEntity) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	if flexible {
		m.type_ = r.read_compact_string()
	} else {
		m.type_ = r.read_string()
	}
	if flexible {
		m.name = r.read_compact_nullable_string()
	} else {
		m.name = r.read_nullable_string()
	}
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct AlterClientQuotasResponseEntry {
pub mut:
	error_code    i16
	error_message ?string
	entity        []AlterClientQuotasResponseEntryEntity
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &AlterClientQuotasResponseEntry) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int16(m.error_code)
	if flexible {
		w.write_compact_nullable_string(m.error_message)
	} else {
		w.write_nullable_string(m.error_message)
	}
	arr_entity := m.entity
	if flexible {
		w.write_compact_array_len(arr_entity.len)
	} else {
		w.write_array_len(arr_entity.len)
	}
	for item_entity in arr_entity {
		item_entity.write_to_versioned(mut w, version, flexible)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m AlterClientQuotasResponseEntry) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	m.error_code = r.read_int16()
	if flexible {
		m.error_message = r.read_compact_nullable_string()
	} else {
		m.error_message = r.read_nullable_string()
	}
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_entity := []AlterClientQuotasResponseEntryEntity{cap: if arr_len > 0 {
		arr_len
	} else {
		0
	}}
	for _ in 0 .. arr_len {
		mut item_entity := AlterClientQuotasResponseEntryEntity{}
		item_entity.read_from_versioned(mut r, version, flexible)!
		arr_entity << item_entity
	}
	m.entity = arr_entity
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct AlterClientQuotasResponse {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version         i16
	throttle_millis int
	entries         []AlterClientQuotasResponseEntry
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of AlterClientQuotasResponse (49).
pub fn (m &AlterClientQuotasResponse) key() i16 {
	return 49
}

// max_version returns the maximum wire version this client supports.
pub fn (m &AlterClientQuotasResponse) max_version() i16 {
	return 1
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &AlterClientQuotasResponse) is_flexible() bool {
	return m.version >= 1
}

// write_to encodes m at m.version into w.
pub fn (m &AlterClientQuotasResponse) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &AlterClientQuotasResponse) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int32(m.throttle_millis)
	arr_entries := m.entries
	if flexible {
		w.write_compact_array_len(arr_entries.len)
	} else {
		w.write_array_len(arr_entries.len)
	}
	for item_entries in arr_entries {
		item_entries.write_to_versioned(mut w, version, flexible)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = AlterClientQuotasResponse{version: v}).
pub fn (mut m AlterClientQuotasResponse) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m AlterClientQuotasResponse) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	m.throttle_millis = r.read_int32()
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_entries := []AlterClientQuotasResponseEntry{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_entries := AlterClientQuotasResponseEntry{}
		item_entries.read_from_versioned(mut r, version, flexible)!
		arr_entries << item_entries
	}
	m.entries = arr_entries
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}
