// Code generated by `v run generate/` from
// franz-go generate/definitions/18_api_versions — DO NOT EDIT.
module kmsg

import kbin

pub struct ApiVersionsRequest {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version                 i16
	client_software_name    string
	client_software_version string
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of ApiVersionsRequest (18).
pub fn (m &ApiVersionsRequest) key() i16 {
	return 18
}

// max_version returns the maximum wire version this client supports.
pub fn (m &ApiVersionsRequest) max_version() i16 {
	return 4
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &ApiVersionsRequest) is_flexible() bool {
	return m.version >= 3
}

// write_to encodes m at m.version into w.
pub fn (m &ApiVersionsRequest) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &ApiVersionsRequest) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if version >= 3 {
		if flexible {
			w.write_compact_string(m.client_software_name)
		} else {
			w.write_string(m.client_software_name)
		}
	}
	if version >= 3 {
		if flexible {
			w.write_compact_string(m.client_software_version)
		} else {
			w.write_string(m.client_software_version)
		}
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = ApiVersionsRequest{version: v}).
pub fn (mut m ApiVersionsRequest) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m ApiVersionsRequest) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	if version >= 3 {
		if flexible {
			m.client_software_name = r.read_compact_string()
		} else {
			m.client_software_name = r.read_string()
		}
	}
	if version >= 3 {
		if flexible {
			m.client_software_version = r.read_compact_string()
		} else {
			m.client_software_version = r.read_string()
		}
	}
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct ApiVersionsResponseApiKey {
pub mut:
	api_key     i16
	min_version i16
	max_version i16
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &ApiVersionsResponseApiKey) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int16(m.api_key)
	w.write_int16(m.min_version)
	w.write_int16(m.max_version)
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m ApiVersionsResponseApiKey) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	m.api_key = r.read_int16()
	m.min_version = r.read_int16()
	m.max_version = r.read_int16()
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct ApiVersionsResponseSupportedFeature {
pub mut:
	name        string
	min_version i16
	max_version i16
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &ApiVersionsResponseSupportedFeature) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_string(m.name)
	} else {
		w.write_string(m.name)
	}
	w.write_int16(m.min_version)
	w.write_int16(m.max_version)
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m ApiVersionsResponseSupportedFeature) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	if flexible {
		m.name = r.read_compact_string()
	} else {
		m.name = r.read_string()
	}
	m.min_version = r.read_int16()
	m.max_version = r.read_int16()
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct ApiVersionsResponseFinalizedFeature {
pub mut:
	name              string
	max_version_level i16
	min_version_level i16
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &ApiVersionsResponseFinalizedFeature) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_string(m.name)
	} else {
		w.write_string(m.name)
	}
	w.write_int16(m.max_version_level)
	w.write_int16(m.min_version_level)
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m ApiVersionsResponseFinalizedFeature) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	if flexible {
		m.name = r.read_compact_string()
	} else {
		m.name = r.read_string()
	}
	m.max_version_level = r.read_int16()
	m.min_version_level = r.read_int16()
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct ApiVersionsResponse {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version                  i16
	error_code               i16
	api_keys                 []ApiVersionsResponseApiKey
	throttle_millis          int
	supported_features       []ApiVersionsResponseSupportedFeature
	finalized_features_epoch i64 = i64(-1)
	finalized_features       []ApiVersionsResponseFinalizedFeature
	zk_migration_ready       bool
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of ApiVersionsResponse (18).
pub fn (m &ApiVersionsResponse) key() i16 {
	return 18
}

// max_version returns the maximum wire version this client supports.
pub fn (m &ApiVersionsResponse) max_version() i16 {
	return 4
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &ApiVersionsResponse) is_flexible() bool {
	return m.version >= 3
}

// write_to encodes m at m.version into w.
pub fn (m &ApiVersionsResponse) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &ApiVersionsResponse) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int16(m.error_code)
	arr_api_keys := m.api_keys
	if flexible {
		w.write_compact_array_len(arr_api_keys.len)
	} else {
		w.write_array_len(arr_api_keys.len)
	}
	for item_api_keys in arr_api_keys {
		item_api_keys.write_to_versioned(mut w, version, flexible)
	}
	if version >= 1 {
		w.write_int32(m.throttle_millis)
	}
	if flexible {
		mut tag_buf := kbin.Writer{}
		mut num_tags := u32(0)
		if m.supported_features.len > 0 {
			num_tags++
			mut tw := kbin.Writer{}
			arr_tag_supported_features := m.supported_features
			if flexible {
				tw.write_compact_array_len(arr_tag_supported_features.len)
			} else {
				tw.write_array_len(arr_tag_supported_features.len)
			}
			for item_tag_supported_features in arr_tag_supported_features {
				item_tag_supported_features.write_to_versioned(mut tw, version, flexible)
			}
			tag_buf.write_uvarint(0)
			tag_buf.write_uvarint(u32(tw.buf.len))
			tag_buf.buf << tw.buf
		}
		if m.finalized_features_epoch != -1 {
			num_tags++
			mut tw := kbin.Writer{}
			tw.write_int64(m.finalized_features_epoch)
			tag_buf.write_uvarint(1)
			tag_buf.write_uvarint(u32(tw.buf.len))
			tag_buf.buf << tw.buf
		}
		if m.finalized_features.len > 0 {
			num_tags++
			mut tw := kbin.Writer{}
			arr_tag_finalized_features := m.finalized_features
			if flexible {
				tw.write_compact_array_len(arr_tag_finalized_features.len)
			} else {
				tw.write_array_len(arr_tag_finalized_features.len)
			}
			for item_tag_finalized_features in arr_tag_finalized_features {
				item_tag_finalized_features.write_to_versioned(mut tw, version, flexible)
			}
			tag_buf.write_uvarint(2)
			tag_buf.write_uvarint(u32(tw.buf.len))
			tag_buf.buf << tw.buf
		}
		if m.zk_migration_ready {
			num_tags++
			mut tw := kbin.Writer{}
			tw.write_bool(m.zk_migration_ready)
			tag_buf.write_uvarint(3)
			tag_buf.write_uvarint(u32(tw.buf.len))
			tag_buf.buf << tw.buf
		}
		w.write_uvarint(num_tags + u32(m.unknown_tags.len))
		w.buf << tag_buf.buf
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = ApiVersionsResponse{version: v}).
pub fn (mut m ApiVersionsResponse) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m ApiVersionsResponse) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	m.error_code = r.read_int16()
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_api_keys := []ApiVersionsResponseApiKey{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_api_keys := ApiVersionsResponseApiKey{}
		item_api_keys.read_from_versioned(mut r, version, flexible)!
		arr_api_keys << item_api_keys
	}
	m.api_keys = arr_api_keys
	if version >= 1 {
		m.throttle_millis = r.read_int32()
	}
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			if tag == 0 {
				if flexible {
					arr_len = r.read_compact_array_len()
				} else {
					arr_len = r.read_array_len()
				}
				mut arr_tag_supported_features := []ApiVersionsResponseSupportedFeature{cap: if arr_len > 0 {
					arr_len
				} else {
					0
				}}
				for _ in 0 .. arr_len {
					mut item_tag_supported_features := ApiVersionsResponseSupportedFeature{}
					item_tag_supported_features.read_from_versioned(mut r, version, flexible)!
					arr_tag_supported_features << item_tag_supported_features
				}
				m.supported_features = arr_tag_supported_features
			} else if tag == 1 {
				m.finalized_features_epoch = r.read_int64()
			} else if tag == 2 {
				if flexible {
					arr_len = r.read_compact_array_len()
				} else {
					arr_len = r.read_array_len()
				}
				mut arr_tag_finalized_features := []ApiVersionsResponseFinalizedFeature{cap: if arr_len > 0 {
					arr_len
				} else {
					0
				}}
				for _ in 0 .. arr_len {
					mut item_tag_finalized_features := ApiVersionsResponseFinalizedFeature{}
					item_tag_finalized_features.read_from_versioned(mut r, version, flexible)!
					arr_tag_finalized_features << item_tag_finalized_features
				}
				m.finalized_features = arr_tag_finalized_features
			} else if tag == 3 {
				m.zk_migration_ready = r.read_bool()
			} else {
				data := r.span(size)
				if r.ok() {
					m.unknown_tags << UnknownTag{
						tag:  tag
						data: data.clone()
					}
				}
			}
		}
	}
	r.complete()!
}
