// Code generated by `v run generate/` from
// franz-go generate/definitions/53_begin_quorum_epoch — DO NOT EDIT.
module kmsg

import kbin

pub struct BeginQuorumEpochRequestTopicPartition {
pub mut:
	partition          int
	voter_directory_id [16]u8
	leader_id          int
	leader_epoch       int
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &BeginQuorumEpochRequestTopicPartition) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int32(m.partition)
	if version >= 1 {
		w.write_uuid(m.voter_directory_id)
	}
	w.write_int32(m.leader_id)
	w.write_int32(m.leader_epoch)
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m BeginQuorumEpochRequestTopicPartition) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	m.partition = r.read_int32()
	if version >= 1 {
		m.voter_directory_id = r.read_uuid()
	}
	m.leader_id = r.read_int32()
	m.leader_epoch = r.read_int32()
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct BeginQuorumEpochRequestTopic {
pub mut:
	topic      string
	partitions []BeginQuorumEpochRequestTopicPartition
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &BeginQuorumEpochRequestTopic) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_string(m.topic)
	} else {
		w.write_string(m.topic)
	}
	arr_partitions := m.partitions
	if flexible {
		w.write_compact_array_len(arr_partitions.len)
	} else {
		w.write_array_len(arr_partitions.len)
	}
	for item_partitions in arr_partitions {
		item_partitions.write_to_versioned(mut w, version, flexible)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m BeginQuorumEpochRequestTopic) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	if flexible {
		m.topic = r.read_compact_string()
	} else {
		m.topic = r.read_string()
	}
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_partitions := []BeginQuorumEpochRequestTopicPartition{cap: if arr_len > 0 {
		arr_len
	} else {
		0
	}}
	for _ in 0 .. arr_len {
		mut item_partitions := BeginQuorumEpochRequestTopicPartition{}
		item_partitions.read_from_versioned(mut r, version, flexible)!
		arr_partitions << item_partitions
	}
	m.partitions = arr_partitions
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct BeginQuorumEpochRequestLeaderEndpoint {
pub mut:
	name string
	host string
	port u16
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &BeginQuorumEpochRequestLeaderEndpoint) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_string(m.name)
	} else {
		w.write_string(m.name)
	}
	if flexible {
		w.write_compact_string(m.host)
	} else {
		w.write_string(m.host)
	}
	w.write_uint16(m.port)
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m BeginQuorumEpochRequestLeaderEndpoint) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	if flexible {
		m.name = r.read_compact_string()
	} else {
		m.name = r.read_string()
	}
	if flexible {
		m.host = r.read_compact_string()
	} else {
		m.host = r.read_string()
	}
	m.port = r.read_uint16()
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct BeginQuorumEpochRequest {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version          i16
	cluster_id       ?string
	voter_id         int = -1
	topics           []BeginQuorumEpochRequestTopic
	leader_endpoints []BeginQuorumEpochRequestLeaderEndpoint
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of BeginQuorumEpochRequest (53).
pub fn (m &BeginQuorumEpochRequest) key() i16 {
	return 53
}

// max_version returns the maximum wire version this client supports.
pub fn (m &BeginQuorumEpochRequest) max_version() i16 {
	return 1
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &BeginQuorumEpochRequest) is_flexible() bool {
	return m.version >= 1
}

// write_to encodes m at m.version into w.
pub fn (m &BeginQuorumEpochRequest) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &BeginQuorumEpochRequest) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_nullable_string(m.cluster_id)
	} else {
		w.write_nullable_string(m.cluster_id)
	}
	if version >= 1 {
		w.write_int32(m.voter_id)
	}
	arr_topics := m.topics
	if flexible {
		w.write_compact_array_len(arr_topics.len)
	} else {
		w.write_array_len(arr_topics.len)
	}
	for item_topics in arr_topics {
		item_topics.write_to_versioned(mut w, version, flexible)
	}
	if version >= 1 {
		arr_leader_endpoints := m.leader_endpoints
		if flexible {
			w.write_compact_array_len(arr_leader_endpoints.len)
		} else {
			w.write_array_len(arr_leader_endpoints.len)
		}
		for item_leader_endpoints in arr_leader_endpoints {
			item_leader_endpoints.write_to_versioned(mut w, version, flexible)
		}
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = BeginQuorumEpochRequest{version: v}).
pub fn (mut m BeginQuorumEpochRequest) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m BeginQuorumEpochRequest) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	if flexible {
		m.cluster_id = r.read_compact_nullable_string()
	} else {
		m.cluster_id = r.read_nullable_string()
	}
	if version >= 1 {
		m.voter_id = r.read_int32()
	}
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_topics := []BeginQuorumEpochRequestTopic{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_topics := BeginQuorumEpochRequestTopic{}
		item_topics.read_from_versioned(mut r, version, flexible)!
		arr_topics << item_topics
	}
	m.topics = arr_topics
	if version >= 1 {
		if flexible {
			arr_len = r.read_compact_array_len()
		} else {
			arr_len = r.read_array_len()
		}
		mut arr_leader_endpoints := []BeginQuorumEpochRequestLeaderEndpoint{cap: if arr_len > 0 {
			arr_len
		} else {
			0
		}}
		for _ in 0 .. arr_len {
			mut item_leader_endpoints := BeginQuorumEpochRequestLeaderEndpoint{}
			item_leader_endpoints.read_from_versioned(mut r, version, flexible)!
			arr_leader_endpoints << item_leader_endpoints
		}
		m.leader_endpoints = arr_leader_endpoints
	}
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct BeginQuorumEpochResponseTopicPartition {
pub mut:
	partition    int
	error_code   i16
	leader_id    int
	leader_epoch int
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &BeginQuorumEpochResponseTopicPartition) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int32(m.partition)
	w.write_int16(m.error_code)
	w.write_int32(m.leader_id)
	w.write_int32(m.leader_epoch)
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m BeginQuorumEpochResponseTopicPartition) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	m.partition = r.read_int32()
	m.error_code = r.read_int16()
	m.leader_id = r.read_int32()
	m.leader_epoch = r.read_int32()
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct BeginQuorumEpochResponseTopic {
pub mut:
	topic      string
	partitions []BeginQuorumEpochResponseTopicPartition
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &BeginQuorumEpochResponseTopic) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_string(m.topic)
	} else {
		w.write_string(m.topic)
	}
	arr_partitions := m.partitions
	if flexible {
		w.write_compact_array_len(arr_partitions.len)
	} else {
		w.write_array_len(arr_partitions.len)
	}
	for item_partitions in arr_partitions {
		item_partitions.write_to_versioned(mut w, version, flexible)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m BeginQuorumEpochResponseTopic) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	if flexible {
		m.topic = r.read_compact_string()
	} else {
		m.topic = r.read_string()
	}
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_partitions := []BeginQuorumEpochResponseTopicPartition{cap: if arr_len > 0 {
		arr_len
	} else {
		0
	}}
	for _ in 0 .. arr_len {
		mut item_partitions := BeginQuorumEpochResponseTopicPartition{}
		item_partitions.read_from_versioned(mut r, version, flexible)!
		arr_partitions << item_partitions
	}
	m.partitions = arr_partitions
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct BeginQuorumEpochResponseNodeEndpoint {
pub mut:
	node_id int
	host    string
	port    u16
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &BeginQuorumEpochResponseNodeEndpoint) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if version >= 1 {
		w.write_int32(m.node_id)
	}
	if version >= 1 {
		if flexible {
			w.write_compact_string(m.host)
		} else {
			w.write_string(m.host)
		}
	}
	if version >= 1 {
		w.write_uint16(m.port)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m BeginQuorumEpochResponseNodeEndpoint) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	if version >= 1 {
		m.node_id = r.read_int32()
	}
	if version >= 1 {
		if flexible {
			m.host = r.read_compact_string()
		} else {
			m.host = r.read_string()
		}
	}
	if version >= 1 {
		m.port = r.read_uint16()
	}
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct BeginQuorumEpochResponse {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version        i16
	error_code     i16
	topics         []BeginQuorumEpochResponseTopic
	node_endpoints []BeginQuorumEpochResponseNodeEndpoint
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of BeginQuorumEpochResponse (53).
pub fn (m &BeginQuorumEpochResponse) key() i16 {
	return 53
}

// max_version returns the maximum wire version this client supports.
pub fn (m &BeginQuorumEpochResponse) max_version() i16 {
	return 1
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &BeginQuorumEpochResponse) is_flexible() bool {
	return m.version >= 1
}

// write_to encodes m at m.version into w.
pub fn (m &BeginQuorumEpochResponse) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &BeginQuorumEpochResponse) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int16(m.error_code)
	arr_topics := m.topics
	if flexible {
		w.write_compact_array_len(arr_topics.len)
	} else {
		w.write_array_len(arr_topics.len)
	}
	for item_topics in arr_topics {
		item_topics.write_to_versioned(mut w, version, flexible)
	}
	if flexible {
		mut tag_buf := kbin.Writer{}
		mut num_tags := u32(0)
		if m.node_endpoints.len > 0 {
			num_tags++
			mut tw := kbin.Writer{}
			arr_tag_node_endpoints := m.node_endpoints
			if flexible {
				tw.write_compact_array_len(arr_tag_node_endpoints.len)
			} else {
				tw.write_array_len(arr_tag_node_endpoints.len)
			}
			for item_tag_node_endpoints in arr_tag_node_endpoints {
				item_tag_node_endpoints.write_to_versioned(mut tw, version, flexible)
			}
			tag_buf.write_uvarint(0)
			tag_buf.write_uvarint(u32(tw.buf.len))
			tag_buf.buf << tw.buf
		}
		w.write_uvarint(num_tags + u32(m.unknown_tags.len))
		w.buf << tag_buf.buf
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = BeginQuorumEpochResponse{version: v}).
pub fn (mut m BeginQuorumEpochResponse) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m BeginQuorumEpochResponse) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	m.error_code = r.read_int16()
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_topics := []BeginQuorumEpochResponseTopic{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_topics := BeginQuorumEpochResponseTopic{}
		item_topics.read_from_versioned(mut r, version, flexible)!
		arr_topics << item_topics
	}
	m.topics = arr_topics
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			if tag == 0 {
				if flexible {
					arr_len = r.read_compact_array_len()
				} else {
					arr_len = r.read_array_len()
				}
				mut arr_tag_node_endpoints := []BeginQuorumEpochResponseNodeEndpoint{cap: if arr_len > 0 {
					arr_len
				} else {
					0
				}}
				for _ in 0 .. arr_len {
					mut item_tag_node_endpoints := BeginQuorumEpochResponseNodeEndpoint{}
					item_tag_node_endpoints.read_from_versioned(mut r, version, flexible)!
					arr_tag_node_endpoints << item_tag_node_endpoints
				}
				m.node_endpoints = arr_tag_node_endpoints
			} else {
				data := r.span(size)
				if r.ok() {
					m.unknown_tags << UnknownTag{
						tag:  tag
						data: data.clone()
					}
				}
			}
		}
	}
	r.complete()!
}
