// Code generated by `v run generate/` from
// franz-go generate/definitions/63_broker_heartbeat — DO NOT EDIT.
module kmsg

import kbin

pub struct BrokerHeartbeatRequest {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version                 i16
	broker_id               int
	broker_epoch            i64 = i64(-1)
	current_metadata_offset i64
	want_fence              bool
	want_shutdown           bool
	offline_log_dirs        [][16]u8
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of BrokerHeartbeatRequest (63).
pub fn (m &BrokerHeartbeatRequest) key() i16 {
	return 63
}

// max_version returns the maximum wire version this client supports.
pub fn (m &BrokerHeartbeatRequest) max_version() i16 {
	return 1
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &BrokerHeartbeatRequest) is_flexible() bool {
	return m.version >= 0
}

// write_to encodes m at m.version into w.
pub fn (m &BrokerHeartbeatRequest) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &BrokerHeartbeatRequest) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int32(m.broker_id)
	w.write_int64(m.broker_epoch)
	w.write_int64(m.current_metadata_offset)
	w.write_bool(m.want_fence)
	w.write_bool(m.want_shutdown)
	if flexible {
		mut tag_buf := kbin.Writer{}
		mut num_tags := u32(0)
		if m.offline_log_dirs.len > 0 {
			num_tags++
			mut tw := kbin.Writer{}
			arr_tag_offline_log_dirs := m.offline_log_dirs
			if flexible {
				tw.write_compact_array_len(arr_tag_offline_log_dirs.len)
			} else {
				tw.write_array_len(arr_tag_offline_log_dirs.len)
			}
			for item_tag_offline_log_dirs in arr_tag_offline_log_dirs {
				tw.write_uuid(item_tag_offline_log_dirs)
			}
			tag_buf.write_uvarint(0)
			tag_buf.write_uvarint(u32(tw.buf.len))
			tag_buf.buf << tw.buf
		}
		w.write_uvarint(num_tags + u32(m.unknown_tags.len))
		w.buf << tag_buf.buf
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = BrokerHeartbeatRequest{version: v}).
pub fn (mut m BrokerHeartbeatRequest) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m BrokerHeartbeatRequest) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	m.broker_id = r.read_int32()
	m.broker_epoch = r.read_int64()
	m.current_metadata_offset = r.read_int64()
	m.want_fence = r.read_bool()
	m.want_shutdown = r.read_bool()
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			if tag == 0 {
				if flexible {
					arr_len = r.read_compact_array_len()
				} else {
					arr_len = r.read_array_len()
				}
				mut arr_tag_offline_log_dirs := [][16]u8{cap: if arr_len > 0 { arr_len } else { 0 }}
				for _ in 0 .. arr_len {
					mut item_tag_offline_log_dirs := [16]u8{}
					item_tag_offline_log_dirs = r.read_uuid()
					arr_tag_offline_log_dirs << item_tag_offline_log_dirs
				}
				m.offline_log_dirs = arr_tag_offline_log_dirs
			} else {
				data := r.span(size)
				if r.ok() {
					m.unknown_tags << UnknownTag{
						tag:  tag
						data: data.clone()
					}
				}
			}
		}
	}
	r.complete()!
}

pub struct BrokerHeartbeatResponse {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version         i16
	throttle_millis int
	error_code      i16
	is_caught_up    bool
	is_fenced       bool = true
	should_shutdown bool
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of BrokerHeartbeatResponse (63).
pub fn (m &BrokerHeartbeatResponse) key() i16 {
	return 63
}

// max_version returns the maximum wire version this client supports.
pub fn (m &BrokerHeartbeatResponse) max_version() i16 {
	return 1
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &BrokerHeartbeatResponse) is_flexible() bool {
	return m.version >= 0
}

// write_to encodes m at m.version into w.
pub fn (m &BrokerHeartbeatResponse) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &BrokerHeartbeatResponse) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int32(m.throttle_millis)
	w.write_int16(m.error_code)
	w.write_bool(m.is_caught_up)
	w.write_bool(m.is_fenced)
	w.write_bool(m.should_shutdown)
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = BrokerHeartbeatResponse{version: v}).
pub fn (mut m BrokerHeartbeatResponse) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m BrokerHeartbeatResponse) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	m.throttle_millis = r.read_int32()
	m.error_code = r.read_int16()
	m.is_caught_up = r.read_bool()
	m.is_fenced = r.read_bool()
	m.should_shutdown = r.read_bool()
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}
