// Code generated by `v run generate/` from
// franz-go generate/definitions/62_broker_registration — DO NOT EDIT.
module kmsg

import kbin

pub struct BrokerRegistrationRequestListener {
pub mut:
	name              string
	host              string
	port              u16
	security_protocol i16
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &BrokerRegistrationRequestListener) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_string(m.name)
	} else {
		w.write_string(m.name)
	}
	if flexible {
		w.write_compact_string(m.host)
	} else {
		w.write_string(m.host)
	}
	w.write_uint16(m.port)
	w.write_int16(m.security_protocol)
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m BrokerRegistrationRequestListener) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	if flexible {
		m.name = r.read_compact_string()
	} else {
		m.name = r.read_string()
	}
	if flexible {
		m.host = r.read_compact_string()
	} else {
		m.host = r.read_string()
	}
	m.port = r.read_uint16()
	m.security_protocol = r.read_int16()
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct BrokerRegistrationRequestFeature {
pub mut:
	name                  string
	min_supported_version i16
	max_supported_version i16
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &BrokerRegistrationRequestFeature) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_string(m.name)
	} else {
		w.write_string(m.name)
	}
	w.write_int16(m.min_supported_version)
	w.write_int16(m.max_supported_version)
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m BrokerRegistrationRequestFeature) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	if flexible {
		m.name = r.read_compact_string()
	} else {
		m.name = r.read_string()
	}
	m.min_supported_version = r.read_int16()
	m.max_supported_version = r.read_int16()
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct BrokerRegistrationRequest {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version                i16
	broker_id              int
	cluster_id             string
	incarnation_id         [16]u8
	listeners              []BrokerRegistrationRequestListener
	features               []BrokerRegistrationRequestFeature
	rack                   ?string
	is_migrating_zk_broker bool
	log_dirs               [][16]u8
	previous_broker_epoch  i64 = i64(-1)
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of BrokerRegistrationRequest (62).
pub fn (m &BrokerRegistrationRequest) key() i16 {
	return 62
}

// max_version returns the maximum wire version this client supports.
pub fn (m &BrokerRegistrationRequest) max_version() i16 {
	return 4
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &BrokerRegistrationRequest) is_flexible() bool {
	return m.version >= 0
}

// write_to encodes m at m.version into w.
pub fn (m &BrokerRegistrationRequest) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &BrokerRegistrationRequest) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int32(m.broker_id)
	if flexible {
		w.write_compact_string(m.cluster_id)
	} else {
		w.write_string(m.cluster_id)
	}
	w.write_uuid(m.incarnation_id)
	arr_listeners := m.listeners
	if flexible {
		w.write_compact_array_len(arr_listeners.len)
	} else {
		w.write_array_len(arr_listeners.len)
	}
	for item_listeners in arr_listeners {
		item_listeners.write_to_versioned(mut w, version, flexible)
	}
	arr_features := m.features
	if flexible {
		w.write_compact_array_len(arr_features.len)
	} else {
		w.write_array_len(arr_features.len)
	}
	for item_features in arr_features {
		item_features.write_to_versioned(mut w, version, flexible)
	}
	if flexible {
		w.write_compact_nullable_string(m.rack)
	} else {
		w.write_nullable_string(m.rack)
	}
	if version >= 1 {
		w.write_bool(m.is_migrating_zk_broker)
	}
	if version >= 2 {
		arr_log_dirs := m.log_dirs
		if flexible {
			w.write_compact_array_len(arr_log_dirs.len)
		} else {
			w.write_array_len(arr_log_dirs.len)
		}
		for item_log_dirs in arr_log_dirs {
			w.write_uuid(item_log_dirs)
		}
	}
	if version >= 3 {
		w.write_int64(m.previous_broker_epoch)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = BrokerRegistrationRequest{version: v}).
pub fn (mut m BrokerRegistrationRequest) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m BrokerRegistrationRequest) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	m.broker_id = r.read_int32()
	if flexible {
		m.cluster_id = r.read_compact_string()
	} else {
		m.cluster_id = r.read_string()
	}
	m.incarnation_id = r.read_uuid()
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_listeners := []BrokerRegistrationRequestListener{cap: if arr_len > 0 {
		arr_len
	} else {
		0
	}}
	for _ in 0 .. arr_len {
		mut item_listeners := BrokerRegistrationRequestListener{}
		item_listeners.read_from_versioned(mut r, version, flexible)!
		arr_listeners << item_listeners
	}
	m.listeners = arr_listeners
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_features := []BrokerRegistrationRequestFeature{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_features := BrokerRegistrationRequestFeature{}
		item_features.read_from_versioned(mut r, version, flexible)!
		arr_features << item_features
	}
	m.features = arr_features
	if flexible {
		m.rack = r.read_compact_nullable_string()
	} else {
		m.rack = r.read_nullable_string()
	}
	if version >= 1 {
		m.is_migrating_zk_broker = r.read_bool()
	}
	if version >= 2 {
		if flexible {
			arr_len = r.read_compact_array_len()
		} else {
			arr_len = r.read_array_len()
		}
		mut arr_log_dirs := [][16]u8{cap: if arr_len > 0 { arr_len } else { 0 }}
		for _ in 0 .. arr_len {
			mut item_log_dirs := [16]u8{}
			item_log_dirs = r.read_uuid()
			arr_log_dirs << item_log_dirs
		}
		m.log_dirs = arr_log_dirs
	}
	if version >= 3 {
		m.previous_broker_epoch = r.read_int64()
	}
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct BrokerRegistrationResponse {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version         i16
	throttle_millis int
	error_code      i16
	broker_epoch    i64 = i64(-1)
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of BrokerRegistrationResponse (62).
pub fn (m &BrokerRegistrationResponse) key() i16 {
	return 62
}

// max_version returns the maximum wire version this client supports.
pub fn (m &BrokerRegistrationResponse) max_version() i16 {
	return 4
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &BrokerRegistrationResponse) is_flexible() bool {
	return m.version >= 0
}

// write_to encodes m at m.version into w.
pub fn (m &BrokerRegistrationResponse) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &BrokerRegistrationResponse) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int32(m.throttle_millis)
	w.write_int16(m.error_code)
	w.write_int64(m.broker_epoch)
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = BrokerRegistrationResponse{version: v}).
pub fn (mut m BrokerRegistrationResponse) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m BrokerRegistrationResponse) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	m.throttle_millis = r.read_int32()
	m.error_code = r.read_int16()
	m.broker_epoch = r.read_int64()
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}
