// Code generated by `v run generate/` from
// franz-go generate/definitions/68_consumer_group_heartbeat — DO NOT EDIT.
module kmsg

import kbin

pub struct ConsumerGroupHeartbeatRequestTopic {
pub mut:
	topic_id   [16]u8
	partitions []int
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &ConsumerGroupHeartbeatRequestTopic) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_uuid(m.topic_id)
	arr_partitions := m.partitions
	if flexible {
		w.write_compact_array_len(arr_partitions.len)
	} else {
		w.write_array_len(arr_partitions.len)
	}
	for item_partitions in arr_partitions {
		w.write_int32(item_partitions)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m ConsumerGroupHeartbeatRequestTopic) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	m.topic_id = r.read_uuid()
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_partitions := []int{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_partitions := 0
		item_partitions = r.read_int32()
		arr_partitions << item_partitions
	}
	m.partitions = arr_partitions
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct ConsumerGroupHeartbeatRequest {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version                  i16
	group                    string
	member_id                string
	member_epoch             int
	instance_id              ?string
	rack_id                  ?string
	rebalance_timeout_millis int = -1
	subscribed_topic_names   ?[]string
	subscribed_topic_regex   ?string
	server_assignor          ?string
	topics                   ?[]ConsumerGroupHeartbeatRequestTopic
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of ConsumerGroupHeartbeatRequest (68).
pub fn (m &ConsumerGroupHeartbeatRequest) key() i16 {
	return 68
}

// max_version returns the maximum wire version this client supports.
pub fn (m &ConsumerGroupHeartbeatRequest) max_version() i16 {
	return 1
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &ConsumerGroupHeartbeatRequest) is_flexible() bool {
	return m.version >= 0
}

// write_to encodes m at m.version into w.
pub fn (m &ConsumerGroupHeartbeatRequest) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &ConsumerGroupHeartbeatRequest) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_string(m.group)
	} else {
		w.write_string(m.group)
	}
	if flexible {
		w.write_compact_string(m.member_id)
	} else {
		w.write_string(m.member_id)
	}
	w.write_int32(m.member_epoch)
	if flexible {
		w.write_compact_nullable_string(m.instance_id)
	} else {
		w.write_nullable_string(m.instance_id)
	}
	if flexible {
		w.write_compact_nullable_string(m.rack_id)
	} else {
		w.write_nullable_string(m.rack_id)
	}
	w.write_int32(m.rebalance_timeout_millis)
	if arr_subscribed_topic_names := m.subscribed_topic_names {
		if flexible {
			w.write_compact_array_len(arr_subscribed_topic_names.len)
		} else {
			w.write_array_len(arr_subscribed_topic_names.len)
		}
		for item_subscribed_topic_names in arr_subscribed_topic_names {
			if flexible {
				w.write_compact_string(item_subscribed_topic_names)
			} else {
				w.write_string(item_subscribed_topic_names)
			}
		}
	} else {
		if flexible {
			w.write_uvarint(0)
		} else {
			w.write_int32(-1)
		}
	}
	if version >= 1 {
		if flexible {
			w.write_compact_nullable_string(m.subscribed_topic_regex)
		} else {
			w.write_nullable_string(m.subscribed_topic_regex)
		}
	}
	if flexible {
		w.write_compact_nullable_string(m.server_assignor)
	} else {
		w.write_nullable_string(m.server_assignor)
	}
	if arr_topics := m.topics {
		if flexible {
			w.write_compact_array_len(arr_topics.len)
		} else {
			w.write_array_len(arr_topics.len)
		}
		for item_topics in arr_topics {
			item_topics.write_to_versioned(mut w, version, flexible)
		}
	} else {
		if flexible {
			w.write_uvarint(0)
		} else {
			w.write_int32(-1)
		}
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = ConsumerGroupHeartbeatRequest{version: v}).
pub fn (mut m ConsumerGroupHeartbeatRequest) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m ConsumerGroupHeartbeatRequest) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	if flexible {
		m.group = r.read_compact_string()
	} else {
		m.group = r.read_string()
	}
	if flexible {
		m.member_id = r.read_compact_string()
	} else {
		m.member_id = r.read_string()
	}
	m.member_epoch = r.read_int32()
	if flexible {
		m.instance_id = r.read_compact_nullable_string()
	} else {
		m.instance_id = r.read_nullable_string()
	}
	if flexible {
		m.rack_id = r.read_compact_nullable_string()
	} else {
		m.rack_id = r.read_nullable_string()
	}
	m.rebalance_timeout_millis = r.read_int32()
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	if arr_len < 0 {
		m.subscribed_topic_names = none
	} else {
		mut arr_subscribed_topic_names := []string{cap: if arr_len > 0 { arr_len } else { 0 }}
		for _ in 0 .. arr_len {
			mut item_subscribed_topic_names := ''
			if flexible {
				item_subscribed_topic_names = r.read_compact_string()
			} else {
				item_subscribed_topic_names = r.read_string()
			}
			arr_subscribed_topic_names << item_subscribed_topic_names
		}
		m.subscribed_topic_names = arr_subscribed_topic_names
	}
	if version >= 1 {
		if flexible {
			m.subscribed_topic_regex = r.read_compact_nullable_string()
		} else {
			m.subscribed_topic_regex = r.read_nullable_string()
		}
	}
	if flexible {
		m.server_assignor = r.read_compact_nullable_string()
	} else {
		m.server_assignor = r.read_nullable_string()
	}
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	if arr_len < 0 {
		m.topics = none
	} else {
		mut arr_topics := []ConsumerGroupHeartbeatRequestTopic{cap: if arr_len > 0 {
			arr_len
		} else {
			0
		}}
		for _ in 0 .. arr_len {
			mut item_topics := ConsumerGroupHeartbeatRequestTopic{}
			item_topics.read_from_versioned(mut r, version, flexible)!
			arr_topics << item_topics
		}
		m.topics = arr_topics
	}
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct ConsumerGroupHeartbeatResponseAssignmentTopic {
pub mut:
	topic_id   [16]u8
	partitions []int
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &ConsumerGroupHeartbeatResponseAssignmentTopic) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_uuid(m.topic_id)
	arr_partitions := m.partitions
	if flexible {
		w.write_compact_array_len(arr_partitions.len)
	} else {
		w.write_array_len(arr_partitions.len)
	}
	for item_partitions in arr_partitions {
		w.write_int32(item_partitions)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m ConsumerGroupHeartbeatResponseAssignmentTopic) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	m.topic_id = r.read_uuid()
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_partitions := []int{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_partitions := 0
		item_partitions = r.read_int32()
		arr_partitions << item_partitions
	}
	m.partitions = arr_partitions
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct ConsumerGroupHeartbeatResponseAssignment {
pub mut:
	topics []ConsumerGroupHeartbeatResponseAssignmentTopic
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &ConsumerGroupHeartbeatResponseAssignment) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	arr_topics := m.topics
	if flexible {
		w.write_compact_array_len(arr_topics.len)
	} else {
		w.write_array_len(arr_topics.len)
	}
	for item_topics in arr_topics {
		item_topics.write_to_versioned(mut w, version, flexible)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m ConsumerGroupHeartbeatResponseAssignment) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_topics := []ConsumerGroupHeartbeatResponseAssignmentTopic{cap: if arr_len > 0 {
		arr_len
	} else {
		0
	}}
	for _ in 0 .. arr_len {
		mut item_topics := ConsumerGroupHeartbeatResponseAssignmentTopic{}
		item_topics.read_from_versioned(mut r, version, flexible)!
		arr_topics << item_topics
	}
	m.topics = arr_topics
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct ConsumerGroupHeartbeatResponse {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version                   i16
	throttle_millis           int
	error_code                i16
	error_message             ?string
	member_id                 ?string
	member_epoch              int
	heartbeat_interval_millis int
	assignment                ?ConsumerGroupHeartbeatResponseAssignment
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of ConsumerGroupHeartbeatResponse (68).
pub fn (m &ConsumerGroupHeartbeatResponse) key() i16 {
	return 68
}

// max_version returns the maximum wire version this client supports.
pub fn (m &ConsumerGroupHeartbeatResponse) max_version() i16 {
	return 1
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &ConsumerGroupHeartbeatResponse) is_flexible() bool {
	return m.version >= 0
}

// write_to encodes m at m.version into w.
pub fn (m &ConsumerGroupHeartbeatResponse) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &ConsumerGroupHeartbeatResponse) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int32(m.throttle_millis)
	w.write_int16(m.error_code)
	if flexible {
		w.write_compact_nullable_string(m.error_message)
	} else {
		w.write_nullable_string(m.error_message)
	}
	if flexible {
		w.write_compact_nullable_string(m.member_id)
	} else {
		w.write_nullable_string(m.member_id)
	}
	w.write_int32(m.member_epoch)
	w.write_int32(m.heartbeat_interval_millis)
	if sub_assignment := m.assignment {
		w.write_int8(1)
		sub_assignment.write_to_versioned(mut w, version, flexible)
	} else {
		w.write_int8(-1)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = ConsumerGroupHeartbeatResponse{version: v}).
pub fn (mut m ConsumerGroupHeartbeatResponse) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m ConsumerGroupHeartbeatResponse) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	m.throttle_millis = r.read_int32()
	m.error_code = r.read_int16()
	if flexible {
		m.error_message = r.read_compact_nullable_string()
	} else {
		m.error_message = r.read_nullable_string()
	}
	if flexible {
		m.member_id = r.read_compact_nullable_string()
	} else {
		m.member_id = r.read_nullable_string()
	}
	m.member_epoch = r.read_int32()
	m.heartbeat_interval_millis = r.read_int32()
	if r.read_int8() < 0 {
		m.assignment = none
	} else {
		mut sub_assignment := ConsumerGroupHeartbeatResponseAssignment{}
		sub_assignment.read_from_versioned(mut r, version, flexible)!
		m.assignment = sub_assignment
	}
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}
