// Code generated by `v run generate/` from
// franz-go generate/definitions/70_controller_registration — DO NOT EDIT.
module kmsg

import kbin

pub struct ControllerRegistrationRequestListener {
pub mut:
	name              string
	host              string
	port              u16
	security_protocol i16
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &ControllerRegistrationRequestListener) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_string(m.name)
	} else {
		w.write_string(m.name)
	}
	if flexible {
		w.write_compact_string(m.host)
	} else {
		w.write_string(m.host)
	}
	w.write_uint16(m.port)
	w.write_int16(m.security_protocol)
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m ControllerRegistrationRequestListener) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	if flexible {
		m.name = r.read_compact_string()
	} else {
		m.name = r.read_string()
	}
	if flexible {
		m.host = r.read_compact_string()
	} else {
		m.host = r.read_string()
	}
	m.port = r.read_uint16()
	m.security_protocol = r.read_int16()
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct ControllerRegistrationRequestFeature {
pub mut:
	name                  string
	min_supported_version i16
	max_supported_version i16
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &ControllerRegistrationRequestFeature) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_string(m.name)
	} else {
		w.write_string(m.name)
	}
	w.write_int16(m.min_supported_version)
	w.write_int16(m.max_supported_version)
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m ControllerRegistrationRequestFeature) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	if flexible {
		m.name = r.read_compact_string()
	} else {
		m.name = r.read_string()
	}
	m.min_supported_version = r.read_int16()
	m.max_supported_version = r.read_int16()
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct ControllerRegistrationRequest {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version            i16
	controller_id      int
	incarnation_id     [16]u8
	zk_migration_ready bool
	listeners          []ControllerRegistrationRequestListener
	features           []ControllerRegistrationRequestFeature
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of ControllerRegistrationRequest (70).
pub fn (m &ControllerRegistrationRequest) key() i16 {
	return 70
}

// max_version returns the maximum wire version this client supports.
pub fn (m &ControllerRegistrationRequest) max_version() i16 {
	return 0
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &ControllerRegistrationRequest) is_flexible() bool {
	return m.version >= 0
}

// write_to encodes m at m.version into w.
pub fn (m &ControllerRegistrationRequest) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &ControllerRegistrationRequest) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int32(m.controller_id)
	w.write_uuid(m.incarnation_id)
	w.write_bool(m.zk_migration_ready)
	arr_listeners := m.listeners
	if flexible {
		w.write_compact_array_len(arr_listeners.len)
	} else {
		w.write_array_len(arr_listeners.len)
	}
	for item_listeners in arr_listeners {
		item_listeners.write_to_versioned(mut w, version, flexible)
	}
	arr_features := m.features
	if flexible {
		w.write_compact_array_len(arr_features.len)
	} else {
		w.write_array_len(arr_features.len)
	}
	for item_features in arr_features {
		item_features.write_to_versioned(mut w, version, flexible)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = ControllerRegistrationRequest{version: v}).
pub fn (mut m ControllerRegistrationRequest) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m ControllerRegistrationRequest) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	m.controller_id = r.read_int32()
	m.incarnation_id = r.read_uuid()
	m.zk_migration_ready = r.read_bool()
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_listeners := []ControllerRegistrationRequestListener{cap: if arr_len > 0 {
		arr_len
	} else {
		0
	}}
	for _ in 0 .. arr_len {
		mut item_listeners := ControllerRegistrationRequestListener{}
		item_listeners.read_from_versioned(mut r, version, flexible)!
		arr_listeners << item_listeners
	}
	m.listeners = arr_listeners
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_features := []ControllerRegistrationRequestFeature{cap: if arr_len > 0 {
		arr_len
	} else {
		0
	}}
	for _ in 0 .. arr_len {
		mut item_features := ControllerRegistrationRequestFeature{}
		item_features.read_from_versioned(mut r, version, flexible)!
		arr_features << item_features
	}
	m.features = arr_features
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct ControllerRegistrationResponse {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version         i16
	throttle_millis int
	error_code      i16
	error_message   ?string
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of ControllerRegistrationResponse (70).
pub fn (m &ControllerRegistrationResponse) key() i16 {
	return 70
}

// max_version returns the maximum wire version this client supports.
pub fn (m &ControllerRegistrationResponse) max_version() i16 {
	return 0
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &ControllerRegistrationResponse) is_flexible() bool {
	return m.version >= 0
}

// write_to encodes m at m.version into w.
pub fn (m &ControllerRegistrationResponse) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &ControllerRegistrationResponse) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int32(m.throttle_millis)
	w.write_int16(m.error_code)
	if flexible {
		w.write_compact_nullable_string(m.error_message)
	} else {
		w.write_nullable_string(m.error_message)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = ControllerRegistrationResponse{version: v}).
pub fn (mut m ControllerRegistrationResponse) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m ControllerRegistrationResponse) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	m.throttle_millis = r.read_int32()
	m.error_code = r.read_int16()
	if flexible {
		m.error_message = r.read_compact_nullable_string()
	} else {
		m.error_message = r.read_nullable_string()
	}
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}
