// Code generated by `v run generate/` from
// franz-go generate/definitions/37_create_partitions — DO NOT EDIT.
module kmsg

import kbin

pub struct CreatePartitionsRequestTopicAssignment {
pub mut:
	replicas []int
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &CreatePartitionsRequestTopicAssignment) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	arr_replicas := m.replicas
	if flexible {
		w.write_compact_array_len(arr_replicas.len)
	} else {
		w.write_array_len(arr_replicas.len)
	}
	for item_replicas in arr_replicas {
		w.write_int32(item_replicas)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m CreatePartitionsRequestTopicAssignment) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_replicas := []int{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_replicas := 0
		item_replicas = r.read_int32()
		arr_replicas << item_replicas
	}
	m.replicas = arr_replicas
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct CreatePartitionsRequestTopic {
pub mut:
	topic      string
	count      int
	assignment ?[]CreatePartitionsRequestTopicAssignment
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &CreatePartitionsRequestTopic) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_string(m.topic)
	} else {
		w.write_string(m.topic)
	}
	w.write_int32(m.count)
	if arr_assignment := m.assignment {
		if flexible {
			w.write_compact_array_len(arr_assignment.len)
		} else {
			w.write_array_len(arr_assignment.len)
		}
		for item_assignment in arr_assignment {
			item_assignment.write_to_versioned(mut w, version, flexible)
		}
	} else {
		if flexible {
			w.write_uvarint(0)
		} else {
			w.write_int32(-1)
		}
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m CreatePartitionsRequestTopic) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	if flexible {
		m.topic = r.read_compact_string()
	} else {
		m.topic = r.read_string()
	}
	m.count = r.read_int32()
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	if arr_len < 0 {
		m.assignment = none
	} else {
		mut arr_assignment := []CreatePartitionsRequestTopicAssignment{cap: if arr_len > 0 {
			arr_len
		} else {
			0
		}}
		for _ in 0 .. arr_len {
			mut item_assignment := CreatePartitionsRequestTopicAssignment{}
			item_assignment.read_from_versioned(mut r, version, flexible)!
			arr_assignment << item_assignment
		}
		m.assignment = arr_assignment
	}
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct CreatePartitionsRequest {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version        i16
	topics         []CreatePartitionsRequestTopic
	timeout_millis int = 15000
	validate_only  bool
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of CreatePartitionsRequest (37).
pub fn (m &CreatePartitionsRequest) key() i16 {
	return 37
}

// max_version returns the maximum wire version this client supports.
pub fn (m &CreatePartitionsRequest) max_version() i16 {
	return 3
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &CreatePartitionsRequest) is_flexible() bool {
	return m.version >= 2
}

// write_to encodes m at m.version into w.
pub fn (m &CreatePartitionsRequest) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &CreatePartitionsRequest) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	arr_topics := m.topics
	if flexible {
		w.write_compact_array_len(arr_topics.len)
	} else {
		w.write_array_len(arr_topics.len)
	}
	for item_topics in arr_topics {
		item_topics.write_to_versioned(mut w, version, flexible)
	}
	w.write_int32(m.timeout_millis)
	w.write_bool(m.validate_only)
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = CreatePartitionsRequest{version: v}).
pub fn (mut m CreatePartitionsRequest) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m CreatePartitionsRequest) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_topics := []CreatePartitionsRequestTopic{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_topics := CreatePartitionsRequestTopic{}
		item_topics.read_from_versioned(mut r, version, flexible)!
		arr_topics << item_topics
	}
	m.topics = arr_topics
	m.timeout_millis = r.read_int32()
	m.validate_only = r.read_bool()
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct CreatePartitionsResponseTopic {
pub mut:
	topic         string
	error_code    i16
	error_message ?string
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &CreatePartitionsResponseTopic) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_string(m.topic)
	} else {
		w.write_string(m.topic)
	}
	w.write_int16(m.error_code)
	if flexible {
		w.write_compact_nullable_string(m.error_message)
	} else {
		w.write_nullable_string(m.error_message)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m CreatePartitionsResponseTopic) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	if flexible {
		m.topic = r.read_compact_string()
	} else {
		m.topic = r.read_string()
	}
	m.error_code = r.read_int16()
	if flexible {
		m.error_message = r.read_compact_nullable_string()
	} else {
		m.error_message = r.read_nullable_string()
	}
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct CreatePartitionsResponse {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version         i16
	throttle_millis int
	topics          []CreatePartitionsResponseTopic
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of CreatePartitionsResponse (37).
pub fn (m &CreatePartitionsResponse) key() i16 {
	return 37
}

// max_version returns the maximum wire version this client supports.
pub fn (m &CreatePartitionsResponse) max_version() i16 {
	return 3
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &CreatePartitionsResponse) is_flexible() bool {
	return m.version >= 2
}

// write_to encodes m at m.version into w.
pub fn (m &CreatePartitionsResponse) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &CreatePartitionsResponse) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int32(m.throttle_millis)
	arr_topics := m.topics
	if flexible {
		w.write_compact_array_len(arr_topics.len)
	} else {
		w.write_array_len(arr_topics.len)
	}
	for item_topics in arr_topics {
		item_topics.write_to_versioned(mut w, version, flexible)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = CreatePartitionsResponse{version: v}).
pub fn (mut m CreatePartitionsResponse) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m CreatePartitionsResponse) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	m.throttle_millis = r.read_int32()
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_topics := []CreatePartitionsResponseTopic{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_topics := CreatePartitionsResponseTopic{}
		item_topics.read_from_versioned(mut r, version, flexible)!
		arr_topics << item_topics
	}
	m.topics = arr_topics
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}
