// Code generated by `v run generate/` from
// franz-go generate/definitions/19_create_topics — DO NOT EDIT.
module kmsg

import kbin

pub struct CreateTopicsRequestTopicReplicaAssignment {
pub mut:
	partition int
	replicas  []int
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &CreateTopicsRequestTopicReplicaAssignment) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int32(m.partition)
	arr_replicas := m.replicas
	if flexible {
		w.write_compact_array_len(arr_replicas.len)
	} else {
		w.write_array_len(arr_replicas.len)
	}
	for item_replicas in arr_replicas {
		w.write_int32(item_replicas)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m CreateTopicsRequestTopicReplicaAssignment) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	m.partition = r.read_int32()
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_replicas := []int{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_replicas := 0
		item_replicas = r.read_int32()
		arr_replicas << item_replicas
	}
	m.replicas = arr_replicas
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct CreateTopicsRequestTopicConfig {
pub mut:
	name  string
	value ?string
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &CreateTopicsRequestTopicConfig) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_string(m.name)
	} else {
		w.write_string(m.name)
	}
	if flexible {
		w.write_compact_nullable_string(m.value)
	} else {
		w.write_nullable_string(m.value)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m CreateTopicsRequestTopicConfig) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	if flexible {
		m.name = r.read_compact_string()
	} else {
		m.name = r.read_string()
	}
	if flexible {
		m.value = r.read_compact_nullable_string()
	} else {
		m.value = r.read_nullable_string()
	}
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct CreateTopicsRequestTopic {
pub mut:
	topic              string
	num_partitions     int
	replication_factor i16
	replica_assignment []CreateTopicsRequestTopicReplicaAssignment
	configs            []CreateTopicsRequestTopicConfig
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &CreateTopicsRequestTopic) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_string(m.topic)
	} else {
		w.write_string(m.topic)
	}
	w.write_int32(m.num_partitions)
	w.write_int16(m.replication_factor)
	arr_replica_assignment := m.replica_assignment
	if flexible {
		w.write_compact_array_len(arr_replica_assignment.len)
	} else {
		w.write_array_len(arr_replica_assignment.len)
	}
	for item_replica_assignment in arr_replica_assignment {
		item_replica_assignment.write_to_versioned(mut w, version, flexible)
	}
	arr_configs := m.configs
	if flexible {
		w.write_compact_array_len(arr_configs.len)
	} else {
		w.write_array_len(arr_configs.len)
	}
	for item_configs in arr_configs {
		item_configs.write_to_versioned(mut w, version, flexible)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m CreateTopicsRequestTopic) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	if flexible {
		m.topic = r.read_compact_string()
	} else {
		m.topic = r.read_string()
	}
	m.num_partitions = r.read_int32()
	m.replication_factor = r.read_int16()
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_replica_assignment := []CreateTopicsRequestTopicReplicaAssignment{cap: if arr_len > 0 {
		arr_len
	} else {
		0
	}}
	for _ in 0 .. arr_len {
		mut item_replica_assignment := CreateTopicsRequestTopicReplicaAssignment{}
		item_replica_assignment.read_from_versioned(mut r, version, flexible)!
		arr_replica_assignment << item_replica_assignment
	}
	m.replica_assignment = arr_replica_assignment
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_configs := []CreateTopicsRequestTopicConfig{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_configs := CreateTopicsRequestTopicConfig{}
		item_configs.read_from_versioned(mut r, version, flexible)!
		arr_configs << item_configs
	}
	m.configs = arr_configs
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct CreateTopicsRequest {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version        i16
	topics         []CreateTopicsRequestTopic
	timeout_millis int = 15000
	validate_only  bool
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of CreateTopicsRequest (19).
pub fn (m &CreateTopicsRequest) key() i16 {
	return 19
}

// max_version returns the maximum wire version this client supports.
pub fn (m &CreateTopicsRequest) max_version() i16 {
	return 7
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &CreateTopicsRequest) is_flexible() bool {
	return m.version >= 5
}

// write_to encodes m at m.version into w.
pub fn (m &CreateTopicsRequest) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &CreateTopicsRequest) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	arr_topics := m.topics
	if flexible {
		w.write_compact_array_len(arr_topics.len)
	} else {
		w.write_array_len(arr_topics.len)
	}
	for item_topics in arr_topics {
		item_topics.write_to_versioned(mut w, version, flexible)
	}
	w.write_int32(m.timeout_millis)
	if version >= 1 {
		w.write_bool(m.validate_only)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = CreateTopicsRequest{version: v}).
pub fn (mut m CreateTopicsRequest) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m CreateTopicsRequest) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_topics := []CreateTopicsRequestTopic{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_topics := CreateTopicsRequestTopic{}
		item_topics.read_from_versioned(mut r, version, flexible)!
		arr_topics << item_topics
	}
	m.topics = arr_topics
	m.timeout_millis = r.read_int32()
	if version >= 1 {
		m.validate_only = r.read_bool()
	}
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct CreateTopicsResponseTopicConfig {
pub mut:
	name         string
	value        ?string
	read_only    bool
	source       i8 = i8(-1)
	is_sensitive bool
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &CreateTopicsResponseTopicConfig) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_string(m.name)
	} else {
		w.write_string(m.name)
	}
	if flexible {
		w.write_compact_nullable_string(m.value)
	} else {
		w.write_nullable_string(m.value)
	}
	w.write_bool(m.read_only)
	w.write_int8(m.source)
	w.write_bool(m.is_sensitive)
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m CreateTopicsResponseTopicConfig) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	if flexible {
		m.name = r.read_compact_string()
	} else {
		m.name = r.read_string()
	}
	if flexible {
		m.value = r.read_compact_nullable_string()
	} else {
		m.value = r.read_nullable_string()
	}
	m.read_only = r.read_bool()
	m.source = r.read_int8()
	m.is_sensitive = r.read_bool()
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct CreateTopicsResponseTopic {
pub mut:
	topic              string
	topic_id           [16]u8
	error_code         i16
	error_message      ?string
	config_error_code  i16
	num_partitions     int = -1
	replication_factor i16 = i16(-1)
	configs            ?[]CreateTopicsResponseTopicConfig
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &CreateTopicsResponseTopic) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_string(m.topic)
	} else {
		w.write_string(m.topic)
	}
	if version >= 7 {
		w.write_uuid(m.topic_id)
	}
	w.write_int16(m.error_code)
	if version >= 1 {
		if flexible {
			w.write_compact_nullable_string(m.error_message)
		} else {
			w.write_nullable_string(m.error_message)
		}
	}
	if version >= 5 {
		w.write_int32(m.num_partitions)
	}
	if version >= 5 {
		w.write_int16(m.replication_factor)
	}
	if version >= 5 {
		if arr_configs := m.configs {
			if flexible {
				w.write_compact_array_len(arr_configs.len)
			} else {
				w.write_array_len(arr_configs.len)
			}
			for item_configs in arr_configs {
				item_configs.write_to_versioned(mut w, version, flexible)
			}
		} else {
			if flexible {
				w.write_uvarint(0)
			} else {
				w.write_int32(-1)
			}
		}
	}
	if flexible {
		mut tag_buf := kbin.Writer{}
		mut num_tags := u32(0)
		if m.config_error_code != 0 {
			num_tags++
			mut tw := kbin.Writer{}
			tw.write_int16(m.config_error_code)
			tag_buf.write_uvarint(0)
			tag_buf.write_uvarint(u32(tw.buf.len))
			tag_buf.buf << tw.buf
		}
		w.write_uvarint(num_tags + u32(m.unknown_tags.len))
		w.buf << tag_buf.buf
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m CreateTopicsResponseTopic) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	if flexible {
		m.topic = r.read_compact_string()
	} else {
		m.topic = r.read_string()
	}
	if version >= 7 {
		m.topic_id = r.read_uuid()
	}
	m.error_code = r.read_int16()
	if version >= 1 {
		if flexible {
			m.error_message = r.read_compact_nullable_string()
		} else {
			m.error_message = r.read_nullable_string()
		}
	}
	if version >= 5 {
		m.num_partitions = r.read_int32()
	}
	if version >= 5 {
		m.replication_factor = r.read_int16()
	}
	if version >= 5 {
		if flexible {
			arr_len = r.read_compact_array_len()
		} else {
			arr_len = r.read_array_len()
		}
		if arr_len < 0 {
			m.configs = none
		} else {
			mut arr_configs := []CreateTopicsResponseTopicConfig{cap: if arr_len > 0 {
				arr_len
			} else {
				0
			}}
			for _ in 0 .. arr_len {
				mut item_configs := CreateTopicsResponseTopicConfig{}
				item_configs.read_from_versioned(mut r, version, flexible)!
				arr_configs << item_configs
			}
			m.configs = arr_configs
		}
	}
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			if tag == 0 {
				m.config_error_code = r.read_int16()
			} else {
				data := r.span(size)
				if r.ok() {
					m.unknown_tags << UnknownTag{
						tag:  tag
						data: data.clone()
					}
				}
			}
		}
	}
	r.complete()!
}

pub struct CreateTopicsResponse {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version         i16
	throttle_millis int
	topics          []CreateTopicsResponseTopic
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of CreateTopicsResponse (19).
pub fn (m &CreateTopicsResponse) key() i16 {
	return 19
}

// max_version returns the maximum wire version this client supports.
pub fn (m &CreateTopicsResponse) max_version() i16 {
	return 7
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &CreateTopicsResponse) is_flexible() bool {
	return m.version >= 5
}

// write_to encodes m at m.version into w.
pub fn (m &CreateTopicsResponse) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &CreateTopicsResponse) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if version >= 2 {
		w.write_int32(m.throttle_millis)
	}
	arr_topics := m.topics
	if flexible {
		w.write_compact_array_len(arr_topics.len)
	} else {
		w.write_array_len(arr_topics.len)
	}
	for item_topics in arr_topics {
		item_topics.write_to_versioned(mut w, version, flexible)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = CreateTopicsResponse{version: v}).
pub fn (mut m CreateTopicsResponse) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m CreateTopicsResponse) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	if version >= 2 {
		m.throttle_millis = r.read_int32()
	}
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_topics := []CreateTopicsResponseTopic{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_topics := CreateTopicsResponseTopic{}
		item_topics.read_from_versioned(mut r, version, flexible)!
		arr_topics << item_topics
	}
	m.topics = arr_topics
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}
