// Code generated by `v run generate/` from
// franz-go generate/definitions/20_delete_topics — DO NOT EDIT.
module kmsg

import kbin

pub struct DeleteTopicsRequestTopic {
pub mut:
	topic    ?string
	topic_id [16]u8
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &DeleteTopicsRequestTopic) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_nullable_string(m.topic)
	} else {
		w.write_nullable_string(m.topic)
	}
	w.write_uuid(m.topic_id)
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m DeleteTopicsRequestTopic) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	if flexible {
		m.topic = r.read_compact_nullable_string()
	} else {
		m.topic = r.read_nullable_string()
	}
	m.topic_id = r.read_uuid()
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct DeleteTopicsRequest {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version        i16
	topic_names    []string
	topics         []DeleteTopicsRequestTopic
	timeout_millis int = 15000
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of DeleteTopicsRequest (20).
pub fn (m &DeleteTopicsRequest) key() i16 {
	return 20
}

// max_version returns the maximum wire version this client supports.
pub fn (m &DeleteTopicsRequest) max_version() i16 {
	return 6
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &DeleteTopicsRequest) is_flexible() bool {
	return m.version >= 4
}

// write_to encodes m at m.version into w.
pub fn (m &DeleteTopicsRequest) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &DeleteTopicsRequest) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if version <= 5 {
		arr_topic_names := m.topic_names
		if flexible {
			w.write_compact_array_len(arr_topic_names.len)
		} else {
			w.write_array_len(arr_topic_names.len)
		}
		for item_topic_names in arr_topic_names {
			if flexible {
				w.write_compact_string(item_topic_names)
			} else {
				w.write_string(item_topic_names)
			}
		}
	}
	if version >= 6 {
		arr_topics := m.topics
		if flexible {
			w.write_compact_array_len(arr_topics.len)
		} else {
			w.write_array_len(arr_topics.len)
		}
		for item_topics in arr_topics {
			item_topics.write_to_versioned(mut w, version, flexible)
		}
	}
	w.write_int32(m.timeout_millis)
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = DeleteTopicsRequest{version: v}).
pub fn (mut m DeleteTopicsRequest) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m DeleteTopicsRequest) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	if version <= 5 {
		if flexible {
			arr_len = r.read_compact_array_len()
		} else {
			arr_len = r.read_array_len()
		}
		mut arr_topic_names := []string{cap: if arr_len > 0 { arr_len } else { 0 }}
		for _ in 0 .. arr_len {
			mut item_topic_names := ''
			if flexible {
				item_topic_names = r.read_compact_string()
			} else {
				item_topic_names = r.read_string()
			}
			arr_topic_names << item_topic_names
		}
		m.topic_names = arr_topic_names
	}
	if version >= 6 {
		if flexible {
			arr_len = r.read_compact_array_len()
		} else {
			arr_len = r.read_array_len()
		}
		mut arr_topics := []DeleteTopicsRequestTopic{cap: if arr_len > 0 { arr_len } else { 0 }}
		for _ in 0 .. arr_len {
			mut item_topics := DeleteTopicsRequestTopic{}
			item_topics.read_from_versioned(mut r, version, flexible)!
			arr_topics << item_topics
		}
		m.topics = arr_topics
	}
	m.timeout_millis = r.read_int32()
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct DeleteTopicsResponseTopic {
pub mut:
	topic         ?string
	topic_id      [16]u8
	error_code    i16
	error_message ?string
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &DeleteTopicsResponseTopic) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if version < 6 {
		plain := m.topic or { '' }
		if flexible {
			w.write_compact_string(plain)
		} else {
			w.write_string(plain)
		}
	} else {
		if flexible {
			w.write_compact_nullable_string(m.topic)
		} else {
			w.write_nullable_string(m.topic)
		}
	}
	if version >= 6 {
		w.write_uuid(m.topic_id)
	}
	w.write_int16(m.error_code)
	if version >= 5 {
		if flexible {
			w.write_compact_nullable_string(m.error_message)
		} else {
			w.write_nullable_string(m.error_message)
		}
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m DeleteTopicsResponseTopic) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	if version < 6 {
		if flexible {
			m.topic = r.read_compact_string()
		} else {
			m.topic = r.read_string()
		}
	} else {
		if flexible {
			m.topic = r.read_compact_nullable_string()
		} else {
			m.topic = r.read_nullable_string()
		}
	}
	if version >= 6 {
		m.topic_id = r.read_uuid()
	}
	m.error_code = r.read_int16()
	if version >= 5 {
		if flexible {
			m.error_message = r.read_compact_nullable_string()
		} else {
			m.error_message = r.read_nullable_string()
		}
	}
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct DeleteTopicsResponse {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version         i16
	throttle_millis int
	topics          []DeleteTopicsResponseTopic
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of DeleteTopicsResponse (20).
pub fn (m &DeleteTopicsResponse) key() i16 {
	return 20
}

// max_version returns the maximum wire version this client supports.
pub fn (m &DeleteTopicsResponse) max_version() i16 {
	return 6
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &DeleteTopicsResponse) is_flexible() bool {
	return m.version >= 4
}

// write_to encodes m at m.version into w.
pub fn (m &DeleteTopicsResponse) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &DeleteTopicsResponse) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if version >= 1 {
		w.write_int32(m.throttle_millis)
	}
	arr_topics := m.topics
	if flexible {
		w.write_compact_array_len(arr_topics.len)
	} else {
		w.write_array_len(arr_topics.len)
	}
	for item_topics in arr_topics {
		item_topics.write_to_versioned(mut w, version, flexible)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = DeleteTopicsResponse{version: v}).
pub fn (mut m DeleteTopicsResponse) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m DeleteTopicsResponse) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	if version >= 1 {
		m.throttle_millis = r.read_int32()
	}
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_topics := []DeleteTopicsResponseTopic{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_topics := DeleteTopicsResponseTopic{}
		item_topics.read_from_versioned(mut r, version, flexible)!
		arr_topics << item_topics
	}
	m.topics = arr_topics
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}
