// Code generated by `v run generate/` from
// franz-go generate/definitions/42_delete_groups — DO NOT EDIT.
module kmsg

import kbin

pub struct DeleteGroupsRequest {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version i16
	groups  []string
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of DeleteGroupsRequest (42).
pub fn (m &DeleteGroupsRequest) key() i16 {
	return 42
}

// max_version returns the maximum wire version this client supports.
pub fn (m &DeleteGroupsRequest) max_version() i16 {
	return 2
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &DeleteGroupsRequest) is_flexible() bool {
	return m.version >= 2
}

// write_to encodes m at m.version into w.
pub fn (m &DeleteGroupsRequest) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &DeleteGroupsRequest) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	arr_groups := m.groups
	if flexible {
		w.write_compact_array_len(arr_groups.len)
	} else {
		w.write_array_len(arr_groups.len)
	}
	for item_groups in arr_groups {
		if flexible {
			w.write_compact_string(item_groups)
		} else {
			w.write_string(item_groups)
		}
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = DeleteGroupsRequest{version: v}).
pub fn (mut m DeleteGroupsRequest) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m DeleteGroupsRequest) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_groups := []string{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_groups := ''
		if flexible {
			item_groups = r.read_compact_string()
		} else {
			item_groups = r.read_string()
		}
		arr_groups << item_groups
	}
	m.groups = arr_groups
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct DeleteGroupsResponseGroup {
pub mut:
	group      string
	error_code i16
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &DeleteGroupsResponseGroup) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_string(m.group)
	} else {
		w.write_string(m.group)
	}
	w.write_int16(m.error_code)
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m DeleteGroupsResponseGroup) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	if flexible {
		m.group = r.read_compact_string()
	} else {
		m.group = r.read_string()
	}
	m.error_code = r.read_int16()
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct DeleteGroupsResponse {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version         i16
	throttle_millis int
	groups          []DeleteGroupsResponseGroup
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of DeleteGroupsResponse (42).
pub fn (m &DeleteGroupsResponse) key() i16 {
	return 42
}

// max_version returns the maximum wire version this client supports.
pub fn (m &DeleteGroupsResponse) max_version() i16 {
	return 2
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &DeleteGroupsResponse) is_flexible() bool {
	return m.version >= 2
}

// write_to encodes m at m.version into w.
pub fn (m &DeleteGroupsResponse) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &DeleteGroupsResponse) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int32(m.throttle_millis)
	arr_groups := m.groups
	if flexible {
		w.write_compact_array_len(arr_groups.len)
	} else {
		w.write_array_len(arr_groups.len)
	}
	for item_groups in arr_groups {
		item_groups.write_to_versioned(mut w, version, flexible)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = DeleteGroupsResponse{version: v}).
pub fn (mut m DeleteGroupsResponse) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m DeleteGroupsResponse) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	m.throttle_millis = r.read_int32()
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_groups := []DeleteGroupsResponseGroup{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_groups := DeleteGroupsResponseGroup{}
		item_groups.read_from_versioned(mut r, version, flexible)!
		arr_groups << item_groups
	}
	m.groups = arr_groups
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}
