// Code generated by `v run generate/` from
// franz-go generate/definitions/75_describe_topic_partitions — DO NOT EDIT.
module kmsg

import kbin

pub struct DescribeTopicPartitionsRequestTopic {
pub mut:
	topic string
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &DescribeTopicPartitionsRequestTopic) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_string(m.topic)
	} else {
		w.write_string(m.topic)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m DescribeTopicPartitionsRequestTopic) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	if flexible {
		m.topic = r.read_compact_string()
	} else {
		m.topic = r.read_string()
	}
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct DescribeTopicPartitionsRequestCursor {
pub mut:
	topic     string
	partition int
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &DescribeTopicPartitionsRequestCursor) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_string(m.topic)
	} else {
		w.write_string(m.topic)
	}
	w.write_int32(m.partition)
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m DescribeTopicPartitionsRequestCursor) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	if flexible {
		m.topic = r.read_compact_string()
	} else {
		m.topic = r.read_string()
	}
	m.partition = r.read_int32()
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct DescribeTopicPartitionsRequest {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version                  i16
	topics                   []DescribeTopicPartitionsRequestTopic
	response_partition_limit int = 200
	cursor                   ?DescribeTopicPartitionsRequestCursor
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of DescribeTopicPartitionsRequest (75).
pub fn (m &DescribeTopicPartitionsRequest) key() i16 {
	return 75
}

// max_version returns the maximum wire version this client supports.
pub fn (m &DescribeTopicPartitionsRequest) max_version() i16 {
	return 0
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &DescribeTopicPartitionsRequest) is_flexible() bool {
	return m.version >= 0
}

// write_to encodes m at m.version into w.
pub fn (m &DescribeTopicPartitionsRequest) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &DescribeTopicPartitionsRequest) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	arr_topics := m.topics
	if flexible {
		w.write_compact_array_len(arr_topics.len)
	} else {
		w.write_array_len(arr_topics.len)
	}
	for item_topics in arr_topics {
		item_topics.write_to_versioned(mut w, version, flexible)
	}
	w.write_int32(m.response_partition_limit)
	if sub_cursor := m.cursor {
		w.write_int8(1)
		sub_cursor.write_to_versioned(mut w, version, flexible)
	} else {
		w.write_int8(-1)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = DescribeTopicPartitionsRequest{version: v}).
pub fn (mut m DescribeTopicPartitionsRequest) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m DescribeTopicPartitionsRequest) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_topics := []DescribeTopicPartitionsRequestTopic{cap: if arr_len > 0 {
		arr_len
	} else {
		0
	}}
	for _ in 0 .. arr_len {
		mut item_topics := DescribeTopicPartitionsRequestTopic{}
		item_topics.read_from_versioned(mut r, version, flexible)!
		arr_topics << item_topics
	}
	m.topics = arr_topics
	m.response_partition_limit = r.read_int32()
	if r.read_int8() < 0 {
		m.cursor = none
	} else {
		mut sub_cursor := DescribeTopicPartitionsRequestCursor{}
		sub_cursor.read_from_versioned(mut r, version, flexible)!
		m.cursor = sub_cursor
	}
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct DescribeTopicPartitionsResponseTopicPartition {
pub mut:
	error_code               i16
	partition                int
	leader_id                int
	leader_epoch             int = -1
	replicas                 []int
	isr                      []int
	eligible_leader_replicas ?[]int
	last_known_elr           ?[]int
	offline_replicas         []int
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &DescribeTopicPartitionsResponseTopicPartition) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int16(m.error_code)
	w.write_int32(m.partition)
	w.write_int32(m.leader_id)
	w.write_int32(m.leader_epoch)
	arr_replicas := m.replicas
	if flexible {
		w.write_compact_array_len(arr_replicas.len)
	} else {
		w.write_array_len(arr_replicas.len)
	}
	for item_replicas in arr_replicas {
		w.write_int32(item_replicas)
	}
	arr_isr := m.isr
	if flexible {
		w.write_compact_array_len(arr_isr.len)
	} else {
		w.write_array_len(arr_isr.len)
	}
	for item_isr in arr_isr {
		w.write_int32(item_isr)
	}
	if arr_eligible_leader_replicas := m.eligible_leader_replicas {
		if flexible {
			w.write_compact_array_len(arr_eligible_leader_replicas.len)
		} else {
			w.write_array_len(arr_eligible_leader_replicas.len)
		}
		for item_eligible_leader_replicas in arr_eligible_leader_replicas {
			w.write_int32(item_eligible_leader_replicas)
		}
	} else {
		if flexible {
			w.write_uvarint(0)
		} else {
			w.write_int32(-1)
		}
	}
	if arr_last_known_elr := m.last_known_elr {
		if flexible {
			w.write_compact_array_len(arr_last_known_elr.len)
		} else {
			w.write_array_len(arr_last_known_elr.len)
		}
		for item_last_known_elr in arr_last_known_elr {
			w.write_int32(item_last_known_elr)
		}
	} else {
		if flexible {
			w.write_uvarint(0)
		} else {
			w.write_int32(-1)
		}
	}
	arr_offline_replicas := m.offline_replicas
	if flexible {
		w.write_compact_array_len(arr_offline_replicas.len)
	} else {
		w.write_array_len(arr_offline_replicas.len)
	}
	for item_offline_replicas in arr_offline_replicas {
		w.write_int32(item_offline_replicas)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m DescribeTopicPartitionsResponseTopicPartition) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	m.error_code = r.read_int16()
	m.partition = r.read_int32()
	m.leader_id = r.read_int32()
	m.leader_epoch = r.read_int32()
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_replicas := []int{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_replicas := 0
		item_replicas = r.read_int32()
		arr_replicas << item_replicas
	}
	m.replicas = arr_replicas
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_isr := []int{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_isr := 0
		item_isr = r.read_int32()
		arr_isr << item_isr
	}
	m.isr = arr_isr
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	if arr_len < 0 {
		m.eligible_leader_replicas = none
	} else {
		mut arr_eligible_leader_replicas := []int{cap: if arr_len > 0 { arr_len } else { 0 }}
		for _ in 0 .. arr_len {
			mut item_eligible_leader_replicas := 0
			item_eligible_leader_replicas = r.read_int32()
			arr_eligible_leader_replicas << item_eligible_leader_replicas
		}
		m.eligible_leader_replicas = arr_eligible_leader_replicas
	}
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	if arr_len < 0 {
		m.last_known_elr = none
	} else {
		mut arr_last_known_elr := []int{cap: if arr_len > 0 { arr_len } else { 0 }}
		for _ in 0 .. arr_len {
			mut item_last_known_elr := 0
			item_last_known_elr = r.read_int32()
			arr_last_known_elr << item_last_known_elr
		}
		m.last_known_elr = arr_last_known_elr
	}
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_offline_replicas := []int{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_offline_replicas := 0
		item_offline_replicas = r.read_int32()
		arr_offline_replicas << item_offline_replicas
	}
	m.offline_replicas = arr_offline_replicas
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct DescribeTopicPartitionsResponseTopic {
pub mut:
	error_code            i16
	topic                 ?string
	topic_id              [16]u8
	is_internal           bool
	partitions            []DescribeTopicPartitionsResponseTopicPartition
	authorized_operations int = -2147483648
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &DescribeTopicPartitionsResponseTopic) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int16(m.error_code)
	if flexible {
		w.write_compact_nullable_string(m.topic)
	} else {
		w.write_nullable_string(m.topic)
	}
	w.write_uuid(m.topic_id)
	w.write_bool(m.is_internal)
	arr_partitions := m.partitions
	if flexible {
		w.write_compact_array_len(arr_partitions.len)
	} else {
		w.write_array_len(arr_partitions.len)
	}
	for item_partitions in arr_partitions {
		item_partitions.write_to_versioned(mut w, version, flexible)
	}
	w.write_int32(m.authorized_operations)
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m DescribeTopicPartitionsResponseTopic) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	m.error_code = r.read_int16()
	if flexible {
		m.topic = r.read_compact_nullable_string()
	} else {
		m.topic = r.read_nullable_string()
	}
	m.topic_id = r.read_uuid()
	m.is_internal = r.read_bool()
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_partitions := []DescribeTopicPartitionsResponseTopicPartition{cap: if arr_len > 0 {
		arr_len
	} else {
		0
	}}
	for _ in 0 .. arr_len {
		mut item_partitions := DescribeTopicPartitionsResponseTopicPartition{}
		item_partitions.read_from_versioned(mut r, version, flexible)!
		arr_partitions << item_partitions
	}
	m.partitions = arr_partitions
	m.authorized_operations = r.read_int32()
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct DescribeTopicPartitionsResponseNextCursor {
pub mut:
	topic     string
	partition int
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &DescribeTopicPartitionsResponseNextCursor) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_string(m.topic)
	} else {
		w.write_string(m.topic)
	}
	w.write_int32(m.partition)
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m DescribeTopicPartitionsResponseNextCursor) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	if flexible {
		m.topic = r.read_compact_string()
	} else {
		m.topic = r.read_string()
	}
	m.partition = r.read_int32()
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct DescribeTopicPartitionsResponse {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version         i16
	throttle_millis int
	topics          []DescribeTopicPartitionsResponseTopic
	next_cursor     ?DescribeTopicPartitionsResponseNextCursor
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of DescribeTopicPartitionsResponse (75).
pub fn (m &DescribeTopicPartitionsResponse) key() i16 {
	return 75
}

// max_version returns the maximum wire version this client supports.
pub fn (m &DescribeTopicPartitionsResponse) max_version() i16 {
	return 0
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &DescribeTopicPartitionsResponse) is_flexible() bool {
	return m.version >= 0
}

// write_to encodes m at m.version into w.
pub fn (m &DescribeTopicPartitionsResponse) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &DescribeTopicPartitionsResponse) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int32(m.throttle_millis)
	arr_topics := m.topics
	if flexible {
		w.write_compact_array_len(arr_topics.len)
	} else {
		w.write_array_len(arr_topics.len)
	}
	for item_topics in arr_topics {
		item_topics.write_to_versioned(mut w, version, flexible)
	}
	if sub_next_cursor := m.next_cursor {
		w.write_int8(1)
		sub_next_cursor.write_to_versioned(mut w, version, flexible)
	} else {
		w.write_int8(-1)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = DescribeTopicPartitionsResponse{version: v}).
pub fn (mut m DescribeTopicPartitionsResponse) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m DescribeTopicPartitionsResponse) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	m.throttle_millis = r.read_int32()
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_topics := []DescribeTopicPartitionsResponseTopic{cap: if arr_len > 0 {
		arr_len
	} else {
		0
	}}
	for _ in 0 .. arr_len {
		mut item_topics := DescribeTopicPartitionsResponseTopic{}
		item_topics.read_from_versioned(mut r, version, flexible)!
		arr_topics << item_topics
	}
	m.topics = arr_topics
	if r.read_int8() < 0 {
		m.next_cursor = none
	} else {
		mut sub_next_cursor := DescribeTopicPartitionsResponseNextCursor{}
		sub_next_cursor.read_from_versioned(mut r, version, flexible)!
		m.next_cursor = sub_next_cursor
	}
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}
