// Code generated by `v run generate/` from
// franz-go generate/definitions/35_describe_log_dirs — DO NOT EDIT.
module kmsg

import kbin

pub struct DescribeLogDirsRequestTopic {
pub mut:
	topic      string
	partitions []int
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &DescribeLogDirsRequestTopic) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_string(m.topic)
	} else {
		w.write_string(m.topic)
	}
	arr_partitions := m.partitions
	if flexible {
		w.write_compact_array_len(arr_partitions.len)
	} else {
		w.write_array_len(arr_partitions.len)
	}
	for item_partitions in arr_partitions {
		w.write_int32(item_partitions)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m DescribeLogDirsRequestTopic) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	if flexible {
		m.topic = r.read_compact_string()
	} else {
		m.topic = r.read_string()
	}
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_partitions := []int{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_partitions := 0
		item_partitions = r.read_int32()
		arr_partitions << item_partitions
	}
	m.partitions = arr_partitions
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct DescribeLogDirsRequest {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version i16
	topics  ?[]DescribeLogDirsRequestTopic
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of DescribeLogDirsRequest (35).
pub fn (m &DescribeLogDirsRequest) key() i16 {
	return 35
}

// max_version returns the maximum wire version this client supports.
pub fn (m &DescribeLogDirsRequest) max_version() i16 {
	return 4
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &DescribeLogDirsRequest) is_flexible() bool {
	return m.version >= 2
}

// write_to encodes m at m.version into w.
pub fn (m &DescribeLogDirsRequest) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &DescribeLogDirsRequest) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if arr_topics := m.topics {
		if flexible {
			w.write_compact_array_len(arr_topics.len)
		} else {
			w.write_array_len(arr_topics.len)
		}
		for item_topics in arr_topics {
			item_topics.write_to_versioned(mut w, version, flexible)
		}
	} else {
		if flexible {
			w.write_uvarint(0)
		} else {
			w.write_int32(-1)
		}
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = DescribeLogDirsRequest{version: v}).
pub fn (mut m DescribeLogDirsRequest) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m DescribeLogDirsRequest) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	if arr_len < 0 {
		m.topics = none
	} else {
		mut arr_topics := []DescribeLogDirsRequestTopic{cap: if arr_len > 0 { arr_len } else { 0 }}
		for _ in 0 .. arr_len {
			mut item_topics := DescribeLogDirsRequestTopic{}
			item_topics.read_from_versioned(mut r, version, flexible)!
			arr_topics << item_topics
		}
		m.topics = arr_topics
	}
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct DescribeLogDirsResponseDirTopicPartition {
pub mut:
	partition  int
	size       i64
	offset_lag i64
	is_future  bool
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &DescribeLogDirsResponseDirTopicPartition) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int32(m.partition)
	w.write_int64(m.size)
	w.write_int64(m.offset_lag)
	w.write_bool(m.is_future)
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m DescribeLogDirsResponseDirTopicPartition) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	m.partition = r.read_int32()
	m.size = r.read_int64()
	m.offset_lag = r.read_int64()
	m.is_future = r.read_bool()
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct DescribeLogDirsResponseDirTopic {
pub mut:
	topic      string
	partitions []DescribeLogDirsResponseDirTopicPartition
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &DescribeLogDirsResponseDirTopic) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_string(m.topic)
	} else {
		w.write_string(m.topic)
	}
	arr_partitions := m.partitions
	if flexible {
		w.write_compact_array_len(arr_partitions.len)
	} else {
		w.write_array_len(arr_partitions.len)
	}
	for item_partitions in arr_partitions {
		item_partitions.write_to_versioned(mut w, version, flexible)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m DescribeLogDirsResponseDirTopic) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	if flexible {
		m.topic = r.read_compact_string()
	} else {
		m.topic = r.read_string()
	}
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_partitions := []DescribeLogDirsResponseDirTopicPartition{cap: if arr_len > 0 {
		arr_len
	} else {
		0
	}}
	for _ in 0 .. arr_len {
		mut item_partitions := DescribeLogDirsResponseDirTopicPartition{}
		item_partitions.read_from_versioned(mut r, version, flexible)!
		arr_partitions << item_partitions
	}
	m.partitions = arr_partitions
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct DescribeLogDirsResponseDir {
pub mut:
	error_code   i16
	dir          string
	topics       []DescribeLogDirsResponseDirTopic
	total_bytes  i64 = i64(-1)
	usable_bytes i64 = i64(-1)
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &DescribeLogDirsResponseDir) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int16(m.error_code)
	if flexible {
		w.write_compact_string(m.dir)
	} else {
		w.write_string(m.dir)
	}
	arr_topics := m.topics
	if flexible {
		w.write_compact_array_len(arr_topics.len)
	} else {
		w.write_array_len(arr_topics.len)
	}
	for item_topics in arr_topics {
		item_topics.write_to_versioned(mut w, version, flexible)
	}
	if version >= 4 {
		w.write_int64(m.total_bytes)
	}
	if version >= 4 {
		w.write_int64(m.usable_bytes)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m DescribeLogDirsResponseDir) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	m.error_code = r.read_int16()
	if flexible {
		m.dir = r.read_compact_string()
	} else {
		m.dir = r.read_string()
	}
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_topics := []DescribeLogDirsResponseDirTopic{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_topics := DescribeLogDirsResponseDirTopic{}
		item_topics.read_from_versioned(mut r, version, flexible)!
		arr_topics << item_topics
	}
	m.topics = arr_topics
	if version >= 4 {
		m.total_bytes = r.read_int64()
	}
	if version >= 4 {
		m.usable_bytes = r.read_int64()
	}
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct DescribeLogDirsResponse {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version         i16
	throttle_millis int
	error_code      i16
	dirs            []DescribeLogDirsResponseDir
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of DescribeLogDirsResponse (35).
pub fn (m &DescribeLogDirsResponse) key() i16 {
	return 35
}

// max_version returns the maximum wire version this client supports.
pub fn (m &DescribeLogDirsResponse) max_version() i16 {
	return 4
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &DescribeLogDirsResponse) is_flexible() bool {
	return m.version >= 2
}

// write_to encodes m at m.version into w.
pub fn (m &DescribeLogDirsResponse) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &DescribeLogDirsResponse) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int32(m.throttle_millis)
	if version >= 3 {
		w.write_int16(m.error_code)
	}
	arr_dirs := m.dirs
	if flexible {
		w.write_compact_array_len(arr_dirs.len)
	} else {
		w.write_array_len(arr_dirs.len)
	}
	for item_dirs in arr_dirs {
		item_dirs.write_to_versioned(mut w, version, flexible)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = DescribeLogDirsResponse{version: v}).
pub fn (mut m DescribeLogDirsResponse) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m DescribeLogDirsResponse) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	m.throttle_millis = r.read_int32()
	if version >= 3 {
		m.error_code = r.read_int16()
	}
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_dirs := []DescribeLogDirsResponseDir{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_dirs := DescribeLogDirsResponseDir{}
		item_dirs.read_from_versioned(mut r, version, flexible)!
		arr_dirs << item_dirs
	}
	m.dirs = arr_dirs
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}
