// Code generated by `v run generate/` from
// franz-go generate/definitions/65_describe_transactions — DO NOT EDIT.
module kmsg

import kbin

pub struct DescribeTransactionsRequest {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version            i16
	transactional_i_ds []string
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of DescribeTransactionsRequest (65).
pub fn (m &DescribeTransactionsRequest) key() i16 {
	return 65
}

// max_version returns the maximum wire version this client supports.
pub fn (m &DescribeTransactionsRequest) max_version() i16 {
	return 0
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &DescribeTransactionsRequest) is_flexible() bool {
	return m.version >= 0
}

// write_to encodes m at m.version into w.
pub fn (m &DescribeTransactionsRequest) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &DescribeTransactionsRequest) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	arr_transactional_i_ds := m.transactional_i_ds
	if flexible {
		w.write_compact_array_len(arr_transactional_i_ds.len)
	} else {
		w.write_array_len(arr_transactional_i_ds.len)
	}
	for item_transactional_i_ds in arr_transactional_i_ds {
		if flexible {
			w.write_compact_string(item_transactional_i_ds)
		} else {
			w.write_string(item_transactional_i_ds)
		}
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = DescribeTransactionsRequest{version: v}).
pub fn (mut m DescribeTransactionsRequest) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m DescribeTransactionsRequest) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_transactional_i_ds := []string{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_transactional_i_ds := ''
		if flexible {
			item_transactional_i_ds = r.read_compact_string()
		} else {
			item_transactional_i_ds = r.read_string()
		}
		arr_transactional_i_ds << item_transactional_i_ds
	}
	m.transactional_i_ds = arr_transactional_i_ds
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct DescribeTransactionsResponseTransactionStateTopic {
pub mut:
	topic      string
	partitions []int
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &DescribeTransactionsResponseTransactionStateTopic) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_string(m.topic)
	} else {
		w.write_string(m.topic)
	}
	arr_partitions := m.partitions
	if flexible {
		w.write_compact_array_len(arr_partitions.len)
	} else {
		w.write_array_len(arr_partitions.len)
	}
	for item_partitions in arr_partitions {
		w.write_int32(item_partitions)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m DescribeTransactionsResponseTransactionStateTopic) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	if flexible {
		m.topic = r.read_compact_string()
	} else {
		m.topic = r.read_string()
	}
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_partitions := []int{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_partitions := 0
		item_partitions = r.read_int32()
		arr_partitions << item_partitions
	}
	m.partitions = arr_partitions
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct DescribeTransactionsResponseTransactionState {
pub mut:
	error_code       i16
	transactional_id string
	state            string
	timeout_millis   int
	start_timestamp  i64
	producer_id      i64
	producer_epoch   i16
	topics           []DescribeTransactionsResponseTransactionStateTopic
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &DescribeTransactionsResponseTransactionState) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int16(m.error_code)
	if flexible {
		w.write_compact_string(m.transactional_id)
	} else {
		w.write_string(m.transactional_id)
	}
	if flexible {
		w.write_compact_string(m.state)
	} else {
		w.write_string(m.state)
	}
	w.write_int32(m.timeout_millis)
	w.write_int64(m.start_timestamp)
	w.write_int64(m.producer_id)
	w.write_int16(m.producer_epoch)
	arr_topics := m.topics
	if flexible {
		w.write_compact_array_len(arr_topics.len)
	} else {
		w.write_array_len(arr_topics.len)
	}
	for item_topics in arr_topics {
		item_topics.write_to_versioned(mut w, version, flexible)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m DescribeTransactionsResponseTransactionState) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	m.error_code = r.read_int16()
	if flexible {
		m.transactional_id = r.read_compact_string()
	} else {
		m.transactional_id = r.read_string()
	}
	if flexible {
		m.state = r.read_compact_string()
	} else {
		m.state = r.read_string()
	}
	m.timeout_millis = r.read_int32()
	m.start_timestamp = r.read_int64()
	m.producer_id = r.read_int64()
	m.producer_epoch = r.read_int16()
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_topics := []DescribeTransactionsResponseTransactionStateTopic{cap: if arr_len > 0 {
		arr_len
	} else {
		0
	}}
	for _ in 0 .. arr_len {
		mut item_topics := DescribeTransactionsResponseTransactionStateTopic{}
		item_topics.read_from_versioned(mut r, version, flexible)!
		arr_topics << item_topics
	}
	m.topics = arr_topics
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct DescribeTransactionsResponse {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version            i16
	throttle_millis    int
	transaction_states []DescribeTransactionsResponseTransactionState
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of DescribeTransactionsResponse (65).
pub fn (m &DescribeTransactionsResponse) key() i16 {
	return 65
}

// max_version returns the maximum wire version this client supports.
pub fn (m &DescribeTransactionsResponse) max_version() i16 {
	return 0
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &DescribeTransactionsResponse) is_flexible() bool {
	return m.version >= 0
}

// write_to encodes m at m.version into w.
pub fn (m &DescribeTransactionsResponse) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &DescribeTransactionsResponse) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int32(m.throttle_millis)
	arr_transaction_states := m.transaction_states
	if flexible {
		w.write_compact_array_len(arr_transaction_states.len)
	} else {
		w.write_array_len(arr_transaction_states.len)
	}
	for item_transaction_states in arr_transaction_states {
		item_transaction_states.write_to_versioned(mut w, version, flexible)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = DescribeTransactionsResponse{version: v}).
pub fn (mut m DescribeTransactionsResponse) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m DescribeTransactionsResponse) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	m.throttle_millis = r.read_int32()
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_transaction_states := []DescribeTransactionsResponseTransactionState{cap: if arr_len > 0 {
		arr_len
	} else {
		0
	}}
	for _ in 0 .. arr_len {
		mut item_transaction_states := DescribeTransactionsResponseTransactionState{}
		item_transaction_states.read_from_versioned(mut r, version, flexible)!
		arr_transaction_states << item_transaction_states
	}
	m.transaction_states = arr_transaction_states
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}
