// Code generated by `v run generate/` from
// franz-go generate/definitions/50_describe_user_scram_credentials — DO NOT EDIT.
module kmsg

import kbin

pub struct DescribeUserSCRAMCredentialsRequestUser {
pub mut:
	name string
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &DescribeUserSCRAMCredentialsRequestUser) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_string(m.name)
	} else {
		w.write_string(m.name)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m DescribeUserSCRAMCredentialsRequestUser) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	if flexible {
		m.name = r.read_compact_string()
	} else {
		m.name = r.read_string()
	}
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct DescribeUserSCRAMCredentialsRequest {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version i16
	users   ?[]DescribeUserSCRAMCredentialsRequestUser
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of DescribeUserSCRAMCredentialsRequest (50).
pub fn (m &DescribeUserSCRAMCredentialsRequest) key() i16 {
	return 50
}

// max_version returns the maximum wire version this client supports.
pub fn (m &DescribeUserSCRAMCredentialsRequest) max_version() i16 {
	return 0
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &DescribeUserSCRAMCredentialsRequest) is_flexible() bool {
	return m.version >= 0
}

// write_to encodes m at m.version into w.
pub fn (m &DescribeUserSCRAMCredentialsRequest) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &DescribeUserSCRAMCredentialsRequest) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if arr_users := m.users {
		if flexible {
			w.write_compact_array_len(arr_users.len)
		} else {
			w.write_array_len(arr_users.len)
		}
		for item_users in arr_users {
			item_users.write_to_versioned(mut w, version, flexible)
		}
	} else {
		if flexible {
			w.write_uvarint(0)
		} else {
			w.write_int32(-1)
		}
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = DescribeUserSCRAMCredentialsRequest{version: v}).
pub fn (mut m DescribeUserSCRAMCredentialsRequest) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m DescribeUserSCRAMCredentialsRequest) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	if arr_len < 0 {
		m.users = none
	} else {
		mut arr_users := []DescribeUserSCRAMCredentialsRequestUser{cap: if arr_len > 0 {
			arr_len
		} else {
			0
		}}
		for _ in 0 .. arr_len {
			mut item_users := DescribeUserSCRAMCredentialsRequestUser{}
			item_users.read_from_versioned(mut r, version, flexible)!
			arr_users << item_users
		}
		m.users = arr_users
	}
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct DescribeUserSCRAMCredentialsResponseResultCredentialInfo {
pub mut:
	mechanism  i8
	iterations int
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &DescribeUserSCRAMCredentialsResponseResultCredentialInfo) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int8(m.mechanism)
	w.write_int32(m.iterations)
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m DescribeUserSCRAMCredentialsResponseResultCredentialInfo) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	m.mechanism = r.read_int8()
	m.iterations = r.read_int32()
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct DescribeUserSCRAMCredentialsResponseResult {
pub mut:
	user             string
	error_code       i16
	error_message    ?string
	credential_infos []DescribeUserSCRAMCredentialsResponseResultCredentialInfo
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &DescribeUserSCRAMCredentialsResponseResult) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_string(m.user)
	} else {
		w.write_string(m.user)
	}
	w.write_int16(m.error_code)
	if flexible {
		w.write_compact_nullable_string(m.error_message)
	} else {
		w.write_nullable_string(m.error_message)
	}
	arr_credential_infos := m.credential_infos
	if flexible {
		w.write_compact_array_len(arr_credential_infos.len)
	} else {
		w.write_array_len(arr_credential_infos.len)
	}
	for item_credential_infos in arr_credential_infos {
		item_credential_infos.write_to_versioned(mut w, version, flexible)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m DescribeUserSCRAMCredentialsResponseResult) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	if flexible {
		m.user = r.read_compact_string()
	} else {
		m.user = r.read_string()
	}
	m.error_code = r.read_int16()
	if flexible {
		m.error_message = r.read_compact_nullable_string()
	} else {
		m.error_message = r.read_nullable_string()
	}
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_credential_infos := []DescribeUserSCRAMCredentialsResponseResultCredentialInfo{cap: if arr_len > 0 {
		arr_len
	} else {
		0
	}}
	for _ in 0 .. arr_len {
		mut item_credential_infos := DescribeUserSCRAMCredentialsResponseResultCredentialInfo{}
		item_credential_infos.read_from_versioned(mut r, version, flexible)!
		arr_credential_infos << item_credential_infos
	}
	m.credential_infos = arr_credential_infos
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct DescribeUserSCRAMCredentialsResponse {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version         i16
	throttle_millis int
	error_code      i16
	error_message   ?string
	results         []DescribeUserSCRAMCredentialsResponseResult
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of DescribeUserSCRAMCredentialsResponse (50).
pub fn (m &DescribeUserSCRAMCredentialsResponse) key() i16 {
	return 50
}

// max_version returns the maximum wire version this client supports.
pub fn (m &DescribeUserSCRAMCredentialsResponse) max_version() i16 {
	return 0
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &DescribeUserSCRAMCredentialsResponse) is_flexible() bool {
	return m.version >= 0
}

// write_to encodes m at m.version into w.
pub fn (m &DescribeUserSCRAMCredentialsResponse) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &DescribeUserSCRAMCredentialsResponse) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int32(m.throttle_millis)
	w.write_int16(m.error_code)
	if flexible {
		w.write_compact_nullable_string(m.error_message)
	} else {
		w.write_nullable_string(m.error_message)
	}
	arr_results := m.results
	if flexible {
		w.write_compact_array_len(arr_results.len)
	} else {
		w.write_array_len(arr_results.len)
	}
	for item_results in arr_results {
		item_results.write_to_versioned(mut w, version, flexible)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = DescribeUserSCRAMCredentialsResponse{version: v}).
pub fn (mut m DescribeUserSCRAMCredentialsResponse) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m DescribeUserSCRAMCredentialsResponse) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	m.throttle_millis = r.read_int32()
	m.error_code = r.read_int16()
	if flexible {
		m.error_message = r.read_compact_nullable_string()
	} else {
		m.error_message = r.read_nullable_string()
	}
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_results := []DescribeUserSCRAMCredentialsResponseResult{cap: if arr_len > 0 {
		arr_len
	} else {
		0
	}}
	for _ in 0 .. arr_len {
		mut item_results := DescribeUserSCRAMCredentialsResponseResult{}
		item_results.read_from_versioned(mut r, version, flexible)!
		arr_results << item_results
	}
	m.results = arr_results
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}
