// Code generated by `v run generate/` from
// franz-go generate/definitions/55_describe_quorum — DO NOT EDIT.
module kmsg

import kbin

pub struct DescribeQuorumResponseTopicPartitionReplicaState {
pub mut:
	replica_id               int
	replica_directory_id     [16]u8
	log_end_offset           i64
	last_fetch_timestamp     i64 = i64(-1)
	last_caught_up_timestamp i64 = i64(-1)
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &DescribeQuorumResponseTopicPartitionReplicaState) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int32(m.replica_id)
	if version >= 2 {
		w.write_uuid(m.replica_directory_id)
	}
	w.write_int64(m.log_end_offset)
	if version >= 1 {
		w.write_int64(m.last_fetch_timestamp)
	}
	if version >= 1 {
		w.write_int64(m.last_caught_up_timestamp)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m DescribeQuorumResponseTopicPartitionReplicaState) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	m.replica_id = r.read_int32()
	if version >= 2 {
		m.replica_directory_id = r.read_uuid()
	}
	m.log_end_offset = r.read_int64()
	if version >= 1 {
		m.last_fetch_timestamp = r.read_int64()
	}
	if version >= 1 {
		m.last_caught_up_timestamp = r.read_int64()
	}
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct DescribeQuorumRequestTopicPartition {
pub mut:
	partition int
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &DescribeQuorumRequestTopicPartition) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int32(m.partition)
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m DescribeQuorumRequestTopicPartition) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	m.partition = r.read_int32()
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct DescribeQuorumRequestTopic {
pub mut:
	topic      string
	partitions []DescribeQuorumRequestTopicPartition
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &DescribeQuorumRequestTopic) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_string(m.topic)
	} else {
		w.write_string(m.topic)
	}
	arr_partitions := m.partitions
	if flexible {
		w.write_compact_array_len(arr_partitions.len)
	} else {
		w.write_array_len(arr_partitions.len)
	}
	for item_partitions in arr_partitions {
		item_partitions.write_to_versioned(mut w, version, flexible)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m DescribeQuorumRequestTopic) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	if flexible {
		m.topic = r.read_compact_string()
	} else {
		m.topic = r.read_string()
	}
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_partitions := []DescribeQuorumRequestTopicPartition{cap: if arr_len > 0 {
		arr_len
	} else {
		0
	}}
	for _ in 0 .. arr_len {
		mut item_partitions := DescribeQuorumRequestTopicPartition{}
		item_partitions.read_from_versioned(mut r, version, flexible)!
		arr_partitions << item_partitions
	}
	m.partitions = arr_partitions
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct DescribeQuorumRequest {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version i16
	topics  []DescribeQuorumRequestTopic
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of DescribeQuorumRequest (55).
pub fn (m &DescribeQuorumRequest) key() i16 {
	return 55
}

// max_version returns the maximum wire version this client supports.
pub fn (m &DescribeQuorumRequest) max_version() i16 {
	return 2
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &DescribeQuorumRequest) is_flexible() bool {
	return m.version >= 0
}

// write_to encodes m at m.version into w.
pub fn (m &DescribeQuorumRequest) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &DescribeQuorumRequest) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	arr_topics := m.topics
	if flexible {
		w.write_compact_array_len(arr_topics.len)
	} else {
		w.write_array_len(arr_topics.len)
	}
	for item_topics in arr_topics {
		item_topics.write_to_versioned(mut w, version, flexible)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = DescribeQuorumRequest{version: v}).
pub fn (mut m DescribeQuorumRequest) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m DescribeQuorumRequest) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_topics := []DescribeQuorumRequestTopic{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_topics := DescribeQuorumRequestTopic{}
		item_topics.read_from_versioned(mut r, version, flexible)!
		arr_topics << item_topics
	}
	m.topics = arr_topics
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct DescribeQuorumResponseTopicPartition {
pub mut:
	partition      int
	error_code     i16
	error_message  ?string
	leader_id      int
	leader_epoch   int
	high_watermark i64
	current_voters []DescribeQuorumResponseTopicPartitionReplicaState
	observers      []DescribeQuorumResponseTopicPartitionReplicaState
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &DescribeQuorumResponseTopicPartition) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int32(m.partition)
	w.write_int16(m.error_code)
	if version >= 2 {
		if flexible {
			w.write_compact_nullable_string(m.error_message)
		} else {
			w.write_nullable_string(m.error_message)
		}
	}
	w.write_int32(m.leader_id)
	w.write_int32(m.leader_epoch)
	w.write_int64(m.high_watermark)
	arr_current_voters := m.current_voters
	if flexible {
		w.write_compact_array_len(arr_current_voters.len)
	} else {
		w.write_array_len(arr_current_voters.len)
	}
	for item_current_voters in arr_current_voters {
		item_current_voters.write_to_versioned(mut w, version, flexible)
	}
	arr_observers := m.observers
	if flexible {
		w.write_compact_array_len(arr_observers.len)
	} else {
		w.write_array_len(arr_observers.len)
	}
	for item_observers in arr_observers {
		item_observers.write_to_versioned(mut w, version, flexible)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m DescribeQuorumResponseTopicPartition) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	m.partition = r.read_int32()
	m.error_code = r.read_int16()
	if version >= 2 {
		if flexible {
			m.error_message = r.read_compact_nullable_string()
		} else {
			m.error_message = r.read_nullable_string()
		}
	}
	m.leader_id = r.read_int32()
	m.leader_epoch = r.read_int32()
	m.high_watermark = r.read_int64()
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_current_voters := []DescribeQuorumResponseTopicPartitionReplicaState{cap: if arr_len > 0 {
		arr_len
	} else {
		0
	}}
	for _ in 0 .. arr_len {
		mut item_current_voters := DescribeQuorumResponseTopicPartitionReplicaState{}
		item_current_voters.read_from_versioned(mut r, version, flexible)!
		arr_current_voters << item_current_voters
	}
	m.current_voters = arr_current_voters
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_observers := []DescribeQuorumResponseTopicPartitionReplicaState{cap: if arr_len > 0 {
		arr_len
	} else {
		0
	}}
	for _ in 0 .. arr_len {
		mut item_observers := DescribeQuorumResponseTopicPartitionReplicaState{}
		item_observers.read_from_versioned(mut r, version, flexible)!
		arr_observers << item_observers
	}
	m.observers = arr_observers
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct DescribeQuorumResponseTopic {
pub mut:
	topic      string
	partitions []DescribeQuorumResponseTopicPartition
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &DescribeQuorumResponseTopic) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_string(m.topic)
	} else {
		w.write_string(m.topic)
	}
	arr_partitions := m.partitions
	if flexible {
		w.write_compact_array_len(arr_partitions.len)
	} else {
		w.write_array_len(arr_partitions.len)
	}
	for item_partitions in arr_partitions {
		item_partitions.write_to_versioned(mut w, version, flexible)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m DescribeQuorumResponseTopic) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	if flexible {
		m.topic = r.read_compact_string()
	} else {
		m.topic = r.read_string()
	}
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_partitions := []DescribeQuorumResponseTopicPartition{cap: if arr_len > 0 {
		arr_len
	} else {
		0
	}}
	for _ in 0 .. arr_len {
		mut item_partitions := DescribeQuorumResponseTopicPartition{}
		item_partitions.read_from_versioned(mut r, version, flexible)!
		arr_partitions << item_partitions
	}
	m.partitions = arr_partitions
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct DescribeQuorumResponseNodeListener {
pub mut:
	name string
	host string
	port u16
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &DescribeQuorumResponseNodeListener) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_string(m.name)
	} else {
		w.write_string(m.name)
	}
	if flexible {
		w.write_compact_string(m.host)
	} else {
		w.write_string(m.host)
	}
	w.write_uint16(m.port)
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m DescribeQuorumResponseNodeListener) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	if flexible {
		m.name = r.read_compact_string()
	} else {
		m.name = r.read_string()
	}
	if flexible {
		m.host = r.read_compact_string()
	} else {
		m.host = r.read_string()
	}
	m.port = r.read_uint16()
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct DescribeQuorumResponseNode {
pub mut:
	node_id   int
	listeners []DescribeQuorumResponseNodeListener
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &DescribeQuorumResponseNode) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int32(m.node_id)
	arr_listeners := m.listeners
	if flexible {
		w.write_compact_array_len(arr_listeners.len)
	} else {
		w.write_array_len(arr_listeners.len)
	}
	for item_listeners in arr_listeners {
		item_listeners.write_to_versioned(mut w, version, flexible)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m DescribeQuorumResponseNode) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	m.node_id = r.read_int32()
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_listeners := []DescribeQuorumResponseNodeListener{cap: if arr_len > 0 {
		arr_len
	} else {
		0
	}}
	for _ in 0 .. arr_len {
		mut item_listeners := DescribeQuorumResponseNodeListener{}
		item_listeners.read_from_versioned(mut r, version, flexible)!
		arr_listeners << item_listeners
	}
	m.listeners = arr_listeners
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct DescribeQuorumResponse {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version       i16
	error_code    i16
	error_message ?string
	topics        []DescribeQuorumResponseTopic
	nodes         []DescribeQuorumResponseNode
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of DescribeQuorumResponse (55).
pub fn (m &DescribeQuorumResponse) key() i16 {
	return 55
}

// max_version returns the maximum wire version this client supports.
pub fn (m &DescribeQuorumResponse) max_version() i16 {
	return 2
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &DescribeQuorumResponse) is_flexible() bool {
	return m.version >= 0
}

// write_to encodes m at m.version into w.
pub fn (m &DescribeQuorumResponse) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &DescribeQuorumResponse) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int16(m.error_code)
	if version >= 2 {
		if flexible {
			w.write_compact_nullable_string(m.error_message)
		} else {
			w.write_nullable_string(m.error_message)
		}
	}
	arr_topics := m.topics
	if flexible {
		w.write_compact_array_len(arr_topics.len)
	} else {
		w.write_array_len(arr_topics.len)
	}
	for item_topics in arr_topics {
		item_topics.write_to_versioned(mut w, version, flexible)
	}
	if version >= 2 {
		arr_nodes := m.nodes
		if flexible {
			w.write_compact_array_len(arr_nodes.len)
		} else {
			w.write_array_len(arr_nodes.len)
		}
		for item_nodes in arr_nodes {
			item_nodes.write_to_versioned(mut w, version, flexible)
		}
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = DescribeQuorumResponse{version: v}).
pub fn (mut m DescribeQuorumResponse) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m DescribeQuorumResponse) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	m.error_code = r.read_int16()
	if version >= 2 {
		if flexible {
			m.error_message = r.read_compact_nullable_string()
		} else {
			m.error_message = r.read_nullable_string()
		}
	}
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_topics := []DescribeQuorumResponseTopic{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_topics := DescribeQuorumResponseTopic{}
		item_topics.read_from_versioned(mut r, version, flexible)!
		arr_topics << item_topics
	}
	m.topics = arr_topics
	if version >= 2 {
		if flexible {
			arr_len = r.read_compact_array_len()
		} else {
			arr_len = r.read_array_len()
		}
		mut arr_nodes := []DescribeQuorumResponseNode{cap: if arr_len > 0 { arr_len } else { 0 }}
		for _ in 0 .. arr_len {
			mut item_nodes := DescribeQuorumResponseNode{}
			item_nodes.read_from_versioned(mut r, version, flexible)!
			arr_nodes << item_nodes
		}
		m.nodes = arr_nodes
	}
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}
