// Code generated by `v run generate/` from
// franz-go generate/definitions/enums — DO NOT EDIT.
module kmsg

// ACLOperation is a Kafka protocol enum, kept as an open alias so
// unknown future wire values still decode losslessly.
pub type ACLOperation = i8

pub const acl_operation_any = ACLOperation(1)
pub const acl_operation_all = ACLOperation(2)
pub const acl_operation_read = ACLOperation(3)
pub const acl_operation_write = ACLOperation(4)
pub const acl_operation_create = ACLOperation(5)
pub const acl_operation_delete = ACLOperation(6)
pub const acl_operation_alter = ACLOperation(7)
pub const acl_operation_describe = ACLOperation(8)
pub const acl_operation_cluster_action = ACLOperation(9)
pub const acl_operation_describe_configs = ACLOperation(10)
pub const acl_operation_alter_configs = ACLOperation(11)
pub const acl_operation_idempotent_write = ACLOperation(12)
pub const acl_operation_create_tokens = ACLOperation(13)
pub const acl_operation_describe_tokens = ACLOperation(14)

// ACLPermissionType is a Kafka protocol enum, kept as an open alias so
// unknown future wire values still decode losslessly.
pub type ACLPermissionType = i8

pub const acl_permission_type_any = ACLPermissionType(1)
pub const acl_permission_type_deny = ACLPermissionType(2)
pub const acl_permission_type_allow = ACLPermissionType(3)

// ACLResourcePatternType is a Kafka protocol enum, kept as an open alias so
// unknown future wire values still decode losslessly.
pub type ACLResourcePatternType = i8

pub const acl_resource_pattern_type_any = ACLResourcePatternType(1)
pub const acl_resource_pattern_type_match_ = ACLResourcePatternType(2)
pub const acl_resource_pattern_type_literal = ACLResourcePatternType(3)
pub const acl_resource_pattern_type_prefixed = ACLResourcePatternType(4)

// ACLResourceType is a Kafka protocol enum, kept as an open alias so
// unknown future wire values still decode losslessly.
pub type ACLResourceType = i8

pub const acl_resource_type_any = ACLResourceType(1)
pub const acl_resource_type_topic = ACLResourceType(2)
pub const acl_resource_type_group = ACLResourceType(3)
pub const acl_resource_type_cluster = ACLResourceType(4)
pub const acl_resource_type_transactional_id = ACLResourceType(5)
pub const acl_resource_type_delegation_token = ACLResourceType(6)
pub const acl_resource_type_user = ACLResourceType(7)

// ConfigResourceType is a Kafka protocol enum, kept as an open alias so
// unknown future wire values still decode losslessly.
pub type ConfigResourceType = i8

pub const config_resource_type_topic = ConfigResourceType(2)
pub const config_resource_type_broker = ConfigResourceType(4)
pub const config_resource_type_broker_logger = ConfigResourceType(8)
pub const config_resource_type_client_metrics = ConfigResourceType(16)
pub const config_resource_type_group_config = ConfigResourceType(32)

// ConfigSource is a Kafka protocol enum, kept as an open alias so
// unknown future wire values still decode losslessly.
pub type ConfigSource = i8

pub const config_source_dynamic_topic_config = ConfigSource(1)
pub const config_source_dynamic_broker_config = ConfigSource(2)
pub const config_source_dynamic_default_broker_config = ConfigSource(3)
pub const config_source_static_broker_config = ConfigSource(4)
pub const config_source_default_config = ConfigSource(5)
pub const config_source_dynamic_broker_logger_config = ConfigSource(6)
pub const config_source_client_metrics_config = ConfigSource(7)
pub const config_source_group_config = ConfigSource(8)

// ConfigType is a Kafka protocol enum, kept as an open alias so
// unknown future wire values still decode losslessly.
pub type ConfigType = i8

pub const config_type_boolean = ConfigType(1)
pub const config_type_string = ConfigType(2)
pub const config_type_int = ConfigType(3)
pub const config_type_short = ConfigType(4)
pub const config_type_long = ConfigType(5)
pub const config_type_double = ConfigType(6)
pub const config_type_list = ConfigType(7)
pub const config_type_class = ConfigType(8)
pub const config_type_password = ConfigType(9)

// ControlRecordKeyType is a Kafka protocol enum, kept as an open alias so
// unknown future wire values still decode losslessly.
pub type ControlRecordKeyType = i16

pub const control_record_key_type_abort = ControlRecordKeyType(0)
pub const control_record_key_type_commit = ControlRecordKeyType(1)
pub const control_record_key_type_quorum_reassignment = ControlRecordKeyType(2)
pub const control_record_key_type_snapshot_header = ControlRecordKeyType(3)
pub const control_record_key_type_snapshot_footer = ControlRecordKeyType(4)
pub const control_record_key_type_kraft_version = ControlRecordKeyType(5)
pub const control_record_key_type_kraft_voters = ControlRecordKeyType(6)

// IncrementalAlterConfigOp is a Kafka protocol enum, kept as an open alias so
// unknown future wire values still decode losslessly.
pub type IncrementalAlterConfigOp = i8

pub const incremental_alter_config_op_set = IncrementalAlterConfigOp(0)
pub const incremental_alter_config_op_delete = IncrementalAlterConfigOp(1)
pub const incremental_alter_config_op_append = IncrementalAlterConfigOp(2)
pub const incremental_alter_config_op_subtract = IncrementalAlterConfigOp(3)

// QuotasMatchType is a Kafka protocol enum, kept as an open alias so
// unknown future wire values still decode losslessly.
pub type QuotasMatchType = i8

pub const quotas_match_type_exact = QuotasMatchType(0)
pub const quotas_match_type_default = QuotasMatchType(1)
pub const quotas_match_type_any = QuotasMatchType(2)

// TransactionState is a Kafka protocol enum, kept as an open alias so
// unknown future wire values still decode losslessly.
pub type TransactionState = i8

pub const transaction_state_empty = TransactionState(0)
pub const transaction_state_ongoing = TransactionState(1)
pub const transaction_state_prepare_commit = TransactionState(2)
pub const transaction_state_prepare_abort = TransactionState(3)
pub const transaction_state_complete_commit = TransactionState(4)
pub const transaction_state_complete_abort = TransactionState(5)
pub const transaction_state_dead = TransactionState(6)
pub const transaction_state_prepare_epoch_fence = TransactionState(7)
