// Code generated by `v run generate/` from
// franz-go generate/definitions/58_envelope — DO NOT EDIT.
module kmsg

import kbin

pub struct EnvelopeRequest {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version             i16
	request_data        []u8
	request_principal   ?[]u8
	client_host_address []u8
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of EnvelopeRequest (58).
pub fn (m &EnvelopeRequest) key() i16 {
	return 58
}

// max_version returns the maximum wire version this client supports.
pub fn (m &EnvelopeRequest) max_version() i16 {
	return 0
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &EnvelopeRequest) is_flexible() bool {
	return m.version >= 0
}

// write_to encodes m at m.version into w.
pub fn (m &EnvelopeRequest) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &EnvelopeRequest) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_bytes(m.request_data)
	} else {
		w.write_bytes(m.request_data)
	}
	if flexible {
		w.write_compact_nullable_bytes(m.request_principal)
	} else {
		w.write_nullable_bytes(m.request_principal)
	}
	if flexible {
		w.write_compact_bytes(m.client_host_address)
	} else {
		w.write_bytes(m.client_host_address)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = EnvelopeRequest{version: v}).
pub fn (mut m EnvelopeRequest) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m EnvelopeRequest) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	if flexible {
		m.request_data = r.read_compact_bytes()
	} else {
		m.request_data = r.read_bytes()
	}
	if flexible {
		m.request_principal = r.read_compact_nullable_bytes()
	} else {
		m.request_principal = r.read_nullable_bytes()
	}
	if flexible {
		m.client_host_address = r.read_compact_bytes()
	} else {
		m.client_host_address = r.read_bytes()
	}
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct EnvelopeResponse {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version       i16
	response_data ?[]u8
	error_code    i16
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of EnvelopeResponse (58).
pub fn (m &EnvelopeResponse) key() i16 {
	return 58
}

// max_version returns the maximum wire version this client supports.
pub fn (m &EnvelopeResponse) max_version() i16 {
	return 0
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &EnvelopeResponse) is_flexible() bool {
	return m.version >= 0
}

// write_to encodes m at m.version into w.
pub fn (m &EnvelopeResponse) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &EnvelopeResponse) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_nullable_bytes(m.response_data)
	} else {
		w.write_nullable_bytes(m.response_data)
	}
	w.write_int16(m.error_code)
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = EnvelopeResponse{version: v}).
pub fn (mut m EnvelopeResponse) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m EnvelopeResponse) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	if flexible {
		m.response_data = r.read_compact_nullable_bytes()
	} else {
		m.response_data = r.read_nullable_bytes()
	}
	m.error_code = r.read_int16()
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}
