// Code generated by `v run generate/` from
// franz-go generate/definitions/10_find_coordinator — DO NOT EDIT.
module kmsg

import kbin

pub struct FindCoordinatorRequest {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version          i16
	coordinator_key  string
	coordinator_type i8
	coordinator_keys []string
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of FindCoordinatorRequest (10).
pub fn (m &FindCoordinatorRequest) key() i16 {
	return 10
}

// max_version returns the maximum wire version this client supports.
pub fn (m &FindCoordinatorRequest) max_version() i16 {
	return 6
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &FindCoordinatorRequest) is_flexible() bool {
	return m.version >= 3
}

// write_to encodes m at m.version into w.
pub fn (m &FindCoordinatorRequest) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &FindCoordinatorRequest) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if version <= 3 {
		if flexible {
			w.write_compact_string(m.coordinator_key)
		} else {
			w.write_string(m.coordinator_key)
		}
	}
	if version >= 1 {
		w.write_int8(m.coordinator_type)
	}
	if version >= 4 {
		arr_coordinator_keys := m.coordinator_keys
		if flexible {
			w.write_compact_array_len(arr_coordinator_keys.len)
		} else {
			w.write_array_len(arr_coordinator_keys.len)
		}
		for item_coordinator_keys in arr_coordinator_keys {
			if flexible {
				w.write_compact_string(item_coordinator_keys)
			} else {
				w.write_string(item_coordinator_keys)
			}
		}
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = FindCoordinatorRequest{version: v}).
pub fn (mut m FindCoordinatorRequest) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m FindCoordinatorRequest) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	if version <= 3 {
		if flexible {
			m.coordinator_key = r.read_compact_string()
		} else {
			m.coordinator_key = r.read_string()
		}
	}
	if version >= 1 {
		m.coordinator_type = r.read_int8()
	}
	if version >= 4 {
		if flexible {
			arr_len = r.read_compact_array_len()
		} else {
			arr_len = r.read_array_len()
		}
		mut arr_coordinator_keys := []string{cap: if arr_len > 0 { arr_len } else { 0 }}
		for _ in 0 .. arr_len {
			mut item_coordinator_keys := ''
			if flexible {
				item_coordinator_keys = r.read_compact_string()
			} else {
				item_coordinator_keys = r.read_string()
			}
			arr_coordinator_keys << item_coordinator_keys
		}
		m.coordinator_keys = arr_coordinator_keys
	}
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct FindCoordinatorResponseCoordinator {
pub mut:
	key           string
	node_id       int
	host          string
	port          int
	error_code    i16
	error_message ?string
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &FindCoordinatorResponseCoordinator) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_string(m.key)
	} else {
		w.write_string(m.key)
	}
	w.write_int32(m.node_id)
	if flexible {
		w.write_compact_string(m.host)
	} else {
		w.write_string(m.host)
	}
	w.write_int32(m.port)
	w.write_int16(m.error_code)
	if flexible {
		w.write_compact_nullable_string(m.error_message)
	} else {
		w.write_nullable_string(m.error_message)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m FindCoordinatorResponseCoordinator) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	if flexible {
		m.key = r.read_compact_string()
	} else {
		m.key = r.read_string()
	}
	m.node_id = r.read_int32()
	if flexible {
		m.host = r.read_compact_string()
	} else {
		m.host = r.read_string()
	}
	m.port = r.read_int32()
	m.error_code = r.read_int16()
	if flexible {
		m.error_message = r.read_compact_nullable_string()
	} else {
		m.error_message = r.read_nullable_string()
	}
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct FindCoordinatorResponse {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version         i16
	throttle_millis int
	error_code      i16
	error_message   ?string
	node_id         int
	host            string
	port            int
	coordinators    []FindCoordinatorResponseCoordinator
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of FindCoordinatorResponse (10).
pub fn (m &FindCoordinatorResponse) key() i16 {
	return 10
}

// max_version returns the maximum wire version this client supports.
pub fn (m &FindCoordinatorResponse) max_version() i16 {
	return 6
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &FindCoordinatorResponse) is_flexible() bool {
	return m.version >= 3
}

// write_to encodes m at m.version into w.
pub fn (m &FindCoordinatorResponse) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &FindCoordinatorResponse) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if version >= 1 {
		w.write_int32(m.throttle_millis)
	}
	if version <= 3 {
		w.write_int16(m.error_code)
	}
	if version >= 1 && version <= 3 {
		if flexible {
			w.write_compact_nullable_string(m.error_message)
		} else {
			w.write_nullable_string(m.error_message)
		}
	}
	if version <= 3 {
		w.write_int32(m.node_id)
	}
	if version <= 3 {
		if flexible {
			w.write_compact_string(m.host)
		} else {
			w.write_string(m.host)
		}
	}
	if version <= 3 {
		w.write_int32(m.port)
	}
	if version >= 4 {
		arr_coordinators := m.coordinators
		if flexible {
			w.write_compact_array_len(arr_coordinators.len)
		} else {
			w.write_array_len(arr_coordinators.len)
		}
		for item_coordinators in arr_coordinators {
			item_coordinators.write_to_versioned(mut w, version, flexible)
		}
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = FindCoordinatorResponse{version: v}).
pub fn (mut m FindCoordinatorResponse) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m FindCoordinatorResponse) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	if version >= 1 {
		m.throttle_millis = r.read_int32()
	}
	if version <= 3 {
		m.error_code = r.read_int16()
	}
	if version >= 1 && version <= 3 {
		if flexible {
			m.error_message = r.read_compact_nullable_string()
		} else {
			m.error_message = r.read_nullable_string()
		}
	}
	if version <= 3 {
		m.node_id = r.read_int32()
	}
	if version <= 3 {
		if flexible {
			m.host = r.read_compact_string()
		} else {
			m.host = r.read_string()
		}
	}
	if version <= 3 {
		m.port = r.read_int32()
	}
	if version >= 4 {
		if flexible {
			arr_len = r.read_compact_array_len()
		} else {
			arr_len = r.read_array_len()
		}
		mut arr_coordinators := []FindCoordinatorResponseCoordinator{cap: if arr_len > 0 {
			arr_len
		} else {
			0
		}}
		for _ in 0 .. arr_len {
			mut item_coordinators := FindCoordinatorResponseCoordinator{}
			item_coordinators.read_from_versioned(mut r, version, flexible)!
			arr_coordinators << item_coordinators
		}
		m.coordinators = arr_coordinators
	}
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}
