// Code generated by `v run generate/` from
// franz-go generate/definitions/71_get_telemetry_subscriptions — DO NOT EDIT.
module kmsg

import kbin

pub struct GetTelemetrySubscriptionsRequest {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version            i16
	client_instance_id [16]u8
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of GetTelemetrySubscriptionsRequest (71).
pub fn (m &GetTelemetrySubscriptionsRequest) key() i16 {
	return 71
}

// max_version returns the maximum wire version this client supports.
pub fn (m &GetTelemetrySubscriptionsRequest) max_version() i16 {
	return 0
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &GetTelemetrySubscriptionsRequest) is_flexible() bool {
	return m.version >= 0
}

// write_to encodes m at m.version into w.
pub fn (m &GetTelemetrySubscriptionsRequest) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &GetTelemetrySubscriptionsRequest) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_uuid(m.client_instance_id)
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = GetTelemetrySubscriptionsRequest{version: v}).
pub fn (mut m GetTelemetrySubscriptionsRequest) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m GetTelemetrySubscriptionsRequest) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	m.client_instance_id = r.read_uuid()
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct GetTelemetrySubscriptionsResponse {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version                    i16
	throttle_millis            int
	error_code                 i16
	client_instance_id         [16]u8
	subscription_id            int
	accepted_compression_types []i8
	push_interval_millis       int
	telemetry_max_bytes        int
	delta_temporality          bool
	requested_metrics          []string
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of GetTelemetrySubscriptionsResponse (71).
pub fn (m &GetTelemetrySubscriptionsResponse) key() i16 {
	return 71
}

// max_version returns the maximum wire version this client supports.
pub fn (m &GetTelemetrySubscriptionsResponse) max_version() i16 {
	return 0
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &GetTelemetrySubscriptionsResponse) is_flexible() bool {
	return m.version >= 0
}

// write_to encodes m at m.version into w.
pub fn (m &GetTelemetrySubscriptionsResponse) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &GetTelemetrySubscriptionsResponse) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int32(m.throttle_millis)
	w.write_int16(m.error_code)
	w.write_uuid(m.client_instance_id)
	w.write_int32(m.subscription_id)
	arr_accepted_compression_types := m.accepted_compression_types
	if flexible {
		w.write_compact_array_len(arr_accepted_compression_types.len)
	} else {
		w.write_array_len(arr_accepted_compression_types.len)
	}
	for item_accepted_compression_types in arr_accepted_compression_types {
		w.write_int8(item_accepted_compression_types)
	}
	w.write_int32(m.push_interval_millis)
	w.write_int32(m.telemetry_max_bytes)
	w.write_bool(m.delta_temporality)
	arr_requested_metrics := m.requested_metrics
	if flexible {
		w.write_compact_array_len(arr_requested_metrics.len)
	} else {
		w.write_array_len(arr_requested_metrics.len)
	}
	for item_requested_metrics in arr_requested_metrics {
		if flexible {
			w.write_compact_string(item_requested_metrics)
		} else {
			w.write_string(item_requested_metrics)
		}
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = GetTelemetrySubscriptionsResponse{version: v}).
pub fn (mut m GetTelemetrySubscriptionsResponse) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m GetTelemetrySubscriptionsResponse) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	m.throttle_millis = r.read_int32()
	m.error_code = r.read_int16()
	m.client_instance_id = r.read_uuid()
	m.subscription_id = r.read_int32()
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_accepted_compression_types := []i8{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_accepted_compression_types := i8(0)
		item_accepted_compression_types = r.read_int8()
		arr_accepted_compression_types << item_accepted_compression_types
	}
	m.accepted_compression_types = arr_accepted_compression_types
	m.push_interval_millis = r.read_int32()
	m.telemetry_max_bytes = r.read_int32()
	m.delta_temporality = r.read_bool()
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_requested_metrics := []string{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_requested_metrics := ''
		if flexible {
			item_requested_metrics = r.read_compact_string()
		} else {
			item_requested_metrics = r.read_string()
		}
		arr_requested_metrics << item_requested_metrics
	}
	m.requested_metrics = arr_requested_metrics
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}
