// Code generated by `v run generate/` from
// franz-go generate/definitions/12_heartbeat — DO NOT EDIT.
module kmsg

import kbin

pub struct HeartbeatRequest {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version     i16
	group       string
	generation  int
	member_id   string
	instance_id ?string
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of HeartbeatRequest (12).
pub fn (m &HeartbeatRequest) key() i16 {
	return 12
}

// max_version returns the maximum wire version this client supports.
pub fn (m &HeartbeatRequest) max_version() i16 {
	return 4
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &HeartbeatRequest) is_flexible() bool {
	return m.version >= 4
}

// write_to encodes m at m.version into w.
pub fn (m &HeartbeatRequest) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &HeartbeatRequest) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_string(m.group)
	} else {
		w.write_string(m.group)
	}
	w.write_int32(m.generation)
	if flexible {
		w.write_compact_string(m.member_id)
	} else {
		w.write_string(m.member_id)
	}
	if version >= 3 {
		if flexible {
			w.write_compact_nullable_string(m.instance_id)
		} else {
			w.write_nullable_string(m.instance_id)
		}
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = HeartbeatRequest{version: v}).
pub fn (mut m HeartbeatRequest) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m HeartbeatRequest) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	if flexible {
		m.group = r.read_compact_string()
	} else {
		m.group = r.read_string()
	}
	m.generation = r.read_int32()
	if flexible {
		m.member_id = r.read_compact_string()
	} else {
		m.member_id = r.read_string()
	}
	if version >= 3 {
		if flexible {
			m.instance_id = r.read_compact_nullable_string()
		} else {
			m.instance_id = r.read_nullable_string()
		}
	}
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct HeartbeatResponse {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version         i16
	throttle_millis int
	error_code      i16
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of HeartbeatResponse (12).
pub fn (m &HeartbeatResponse) key() i16 {
	return 12
}

// max_version returns the maximum wire version this client supports.
pub fn (m &HeartbeatResponse) max_version() i16 {
	return 4
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &HeartbeatResponse) is_flexible() bool {
	return m.version >= 4
}

// write_to encodes m at m.version into w.
pub fn (m &HeartbeatResponse) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &HeartbeatResponse) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if version >= 1 {
		w.write_int32(m.throttle_millis)
	}
	w.write_int16(m.error_code)
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = HeartbeatResponse{version: v}).
pub fn (mut m HeartbeatResponse) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m HeartbeatResponse) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	if version >= 1 {
		m.throttle_millis = r.read_int32()
	}
	m.error_code = r.read_int16()
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}
