// Code generated by `v run generate/` from
// franz-go generate/definitions/44_incremental_alter_configs — DO NOT EDIT.
module kmsg

import kbin

pub struct IncrementalAlterConfigsRequestResourceConfig {
pub mut:
	name  string
	op    IncrementalAlterConfigOp
	value ?string
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &IncrementalAlterConfigsRequestResourceConfig) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_string(m.name)
	} else {
		w.write_string(m.name)
	}
	w.write_int8(i8(m.op))
	if flexible {
		w.write_compact_nullable_string(m.value)
	} else {
		w.write_nullable_string(m.value)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m IncrementalAlterConfigsRequestResourceConfig) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	if flexible {
		m.name = r.read_compact_string()
	} else {
		m.name = r.read_string()
	}
	m.op = IncrementalAlterConfigOp(r.read_int8())
	if flexible {
		m.value = r.read_compact_nullable_string()
	} else {
		m.value = r.read_nullable_string()
	}
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct IncrementalAlterConfigsRequestResource {
pub mut:
	resource_type ConfigResourceType
	resource_name string
	configs       []IncrementalAlterConfigsRequestResourceConfig
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &IncrementalAlterConfigsRequestResource) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int8(i8(m.resource_type))
	if flexible {
		w.write_compact_string(m.resource_name)
	} else {
		w.write_string(m.resource_name)
	}
	arr_configs := m.configs
	if flexible {
		w.write_compact_array_len(arr_configs.len)
	} else {
		w.write_array_len(arr_configs.len)
	}
	for item_configs in arr_configs {
		item_configs.write_to_versioned(mut w, version, flexible)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m IncrementalAlterConfigsRequestResource) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	m.resource_type = ConfigResourceType(r.read_int8())
	if flexible {
		m.resource_name = r.read_compact_string()
	} else {
		m.resource_name = r.read_string()
	}
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_configs := []IncrementalAlterConfigsRequestResourceConfig{cap: if arr_len > 0 {
		arr_len
	} else {
		0
	}}
	for _ in 0 .. arr_len {
		mut item_configs := IncrementalAlterConfigsRequestResourceConfig{}
		item_configs.read_from_versioned(mut r, version, flexible)!
		arr_configs << item_configs
	}
	m.configs = arr_configs
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct IncrementalAlterConfigsRequest {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version       i16
	resources     []IncrementalAlterConfigsRequestResource
	validate_only bool
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of IncrementalAlterConfigsRequest (44).
pub fn (m &IncrementalAlterConfigsRequest) key() i16 {
	return 44
}

// max_version returns the maximum wire version this client supports.
pub fn (m &IncrementalAlterConfigsRequest) max_version() i16 {
	return 1
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &IncrementalAlterConfigsRequest) is_flexible() bool {
	return m.version >= 1
}

// write_to encodes m at m.version into w.
pub fn (m &IncrementalAlterConfigsRequest) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &IncrementalAlterConfigsRequest) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	arr_resources := m.resources
	if flexible {
		w.write_compact_array_len(arr_resources.len)
	} else {
		w.write_array_len(arr_resources.len)
	}
	for item_resources in arr_resources {
		item_resources.write_to_versioned(mut w, version, flexible)
	}
	w.write_bool(m.validate_only)
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = IncrementalAlterConfigsRequest{version: v}).
pub fn (mut m IncrementalAlterConfigsRequest) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m IncrementalAlterConfigsRequest) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_resources := []IncrementalAlterConfigsRequestResource{cap: if arr_len > 0 {
		arr_len
	} else {
		0
	}}
	for _ in 0 .. arr_len {
		mut item_resources := IncrementalAlterConfigsRequestResource{}
		item_resources.read_from_versioned(mut r, version, flexible)!
		arr_resources << item_resources
	}
	m.resources = arr_resources
	m.validate_only = r.read_bool()
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct IncrementalAlterConfigsResponseResource {
pub mut:
	error_code    i16
	error_message ?string
	resource_type ConfigResourceType
	resource_name string
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &IncrementalAlterConfigsResponseResource) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int16(m.error_code)
	if flexible {
		w.write_compact_nullable_string(m.error_message)
	} else {
		w.write_nullable_string(m.error_message)
	}
	w.write_int8(i8(m.resource_type))
	if flexible {
		w.write_compact_string(m.resource_name)
	} else {
		w.write_string(m.resource_name)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m IncrementalAlterConfigsResponseResource) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	m.error_code = r.read_int16()
	if flexible {
		m.error_message = r.read_compact_nullable_string()
	} else {
		m.error_message = r.read_nullable_string()
	}
	m.resource_type = ConfigResourceType(r.read_int8())
	if flexible {
		m.resource_name = r.read_compact_string()
	} else {
		m.resource_name = r.read_string()
	}
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct IncrementalAlterConfigsResponse {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version         i16
	throttle_millis int
	resources       []IncrementalAlterConfigsResponseResource
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of IncrementalAlterConfigsResponse (44).
pub fn (m &IncrementalAlterConfigsResponse) key() i16 {
	return 44
}

// max_version returns the maximum wire version this client supports.
pub fn (m &IncrementalAlterConfigsResponse) max_version() i16 {
	return 1
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &IncrementalAlterConfigsResponse) is_flexible() bool {
	return m.version >= 1
}

// write_to encodes m at m.version into w.
pub fn (m &IncrementalAlterConfigsResponse) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &IncrementalAlterConfigsResponse) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int32(m.throttle_millis)
	arr_resources := m.resources
	if flexible {
		w.write_compact_array_len(arr_resources.len)
	} else {
		w.write_array_len(arr_resources.len)
	}
	for item_resources in arr_resources {
		item_resources.write_to_versioned(mut w, version, flexible)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = IncrementalAlterConfigsResponse{version: v}).
pub fn (mut m IncrementalAlterConfigsResponse) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m IncrementalAlterConfigsResponse) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	m.throttle_millis = r.read_int32()
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_resources := []IncrementalAlterConfigsResponseResource{cap: if arr_len > 0 {
		arr_len
	} else {
		0
	}}
	for _ in 0 .. arr_len {
		mut item_resources := IncrementalAlterConfigsResponseResource{}
		item_resources.read_from_versioned(mut r, version, flexible)!
		arr_resources << item_resources
	}
	m.resources = arr_resources
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}
