// Code generated by `v run generate/` from
// franz-go generate/definitions/22_init_producer_id — DO NOT EDIT.
module kmsg

import kbin

pub struct InitProducerIDRequest {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version                    i16
	transactional_id           ?string
	transaction_timeout_millis int
	producer_id                i64 = i64(-1)
	producer_epoch             i16 = i16(-1)
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of InitProducerIDRequest (22).
pub fn (m &InitProducerIDRequest) key() i16 {
	return 22
}

// max_version returns the maximum wire version this client supports.
pub fn (m &InitProducerIDRequest) max_version() i16 {
	return 5
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &InitProducerIDRequest) is_flexible() bool {
	return m.version >= 2
}

// write_to encodes m at m.version into w.
pub fn (m &InitProducerIDRequest) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &InitProducerIDRequest) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_nullable_string(m.transactional_id)
	} else {
		w.write_nullable_string(m.transactional_id)
	}
	w.write_int32(m.transaction_timeout_millis)
	if version >= 3 {
		w.write_int64(m.producer_id)
	}
	if version >= 3 {
		w.write_int16(m.producer_epoch)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = InitProducerIDRequest{version: v}).
pub fn (mut m InitProducerIDRequest) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m InitProducerIDRequest) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	if flexible {
		m.transactional_id = r.read_compact_nullable_string()
	} else {
		m.transactional_id = r.read_nullable_string()
	}
	m.transaction_timeout_millis = r.read_int32()
	if version >= 3 {
		m.producer_id = r.read_int64()
	}
	if version >= 3 {
		m.producer_epoch = r.read_int16()
	}
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct InitProducerIDResponse {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version         i16
	throttle_millis int
	error_code      i16
	producer_id     i64 = i64(-1)
	producer_epoch  i16
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of InitProducerIDResponse (22).
pub fn (m &InitProducerIDResponse) key() i16 {
	return 22
}

// max_version returns the maximum wire version this client supports.
pub fn (m &InitProducerIDResponse) max_version() i16 {
	return 5
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &InitProducerIDResponse) is_flexible() bool {
	return m.version >= 2
}

// write_to encodes m at m.version into w.
pub fn (m &InitProducerIDResponse) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &InitProducerIDResponse) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int32(m.throttle_millis)
	w.write_int16(m.error_code)
	w.write_int64(m.producer_id)
	w.write_int16(m.producer_epoch)
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = InitProducerIDResponse{version: v}).
pub fn (mut m InitProducerIDResponse) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m InitProducerIDResponse) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	m.throttle_millis = r.read_int32()
	m.error_code = r.read_int16()
	m.producer_id = r.read_int64()
	m.producer_epoch = r.read_int16()
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}
