// Code generated by `v run generate/` from
// franz-go generate/definitions/11_join_group — DO NOT EDIT.
module kmsg

import kbin

pub struct JoinGroupRequestProtocol {
pub mut:
	name     string
	metadata []u8
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &JoinGroupRequestProtocol) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_string(m.name)
	} else {
		w.write_string(m.name)
	}
	if flexible {
		w.write_compact_bytes(m.metadata)
	} else {
		w.write_bytes(m.metadata)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m JoinGroupRequestProtocol) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	if flexible {
		m.name = r.read_compact_string()
	} else {
		m.name = r.read_string()
	}
	if flexible {
		m.metadata = r.read_compact_bytes()
	} else {
		m.metadata = r.read_bytes()
	}
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct JoinGroupRequest {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version                  i16
	group                    string
	session_timeout_millis   int
	rebalance_timeout_millis int = -1
	member_id                string
	instance_id              ?string
	protocol_type            string
	protocols                []JoinGroupRequestProtocol
	reason                   ?string
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of JoinGroupRequest (11).
pub fn (m &JoinGroupRequest) key() i16 {
	return 11
}

// max_version returns the maximum wire version this client supports.
pub fn (m &JoinGroupRequest) max_version() i16 {
	return 9
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &JoinGroupRequest) is_flexible() bool {
	return m.version >= 6
}

// write_to encodes m at m.version into w.
pub fn (m &JoinGroupRequest) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &JoinGroupRequest) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_string(m.group)
	} else {
		w.write_string(m.group)
	}
	w.write_int32(m.session_timeout_millis)
	if version >= 1 {
		w.write_int32(m.rebalance_timeout_millis)
	}
	if flexible {
		w.write_compact_string(m.member_id)
	} else {
		w.write_string(m.member_id)
	}
	if version >= 5 {
		if flexible {
			w.write_compact_nullable_string(m.instance_id)
		} else {
			w.write_nullable_string(m.instance_id)
		}
	}
	if flexible {
		w.write_compact_string(m.protocol_type)
	} else {
		w.write_string(m.protocol_type)
	}
	arr_protocols := m.protocols
	if flexible {
		w.write_compact_array_len(arr_protocols.len)
	} else {
		w.write_array_len(arr_protocols.len)
	}
	for item_protocols in arr_protocols {
		item_protocols.write_to_versioned(mut w, version, flexible)
	}
	if version >= 8 {
		if flexible {
			w.write_compact_nullable_string(m.reason)
		} else {
			w.write_nullable_string(m.reason)
		}
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = JoinGroupRequest{version: v}).
pub fn (mut m JoinGroupRequest) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m JoinGroupRequest) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	if flexible {
		m.group = r.read_compact_string()
	} else {
		m.group = r.read_string()
	}
	m.session_timeout_millis = r.read_int32()
	if version >= 1 {
		m.rebalance_timeout_millis = r.read_int32()
	}
	if flexible {
		m.member_id = r.read_compact_string()
	} else {
		m.member_id = r.read_string()
	}
	if version >= 5 {
		if flexible {
			m.instance_id = r.read_compact_nullable_string()
		} else {
			m.instance_id = r.read_nullable_string()
		}
	}
	if flexible {
		m.protocol_type = r.read_compact_string()
	} else {
		m.protocol_type = r.read_string()
	}
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_protocols := []JoinGroupRequestProtocol{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_protocols := JoinGroupRequestProtocol{}
		item_protocols.read_from_versioned(mut r, version, flexible)!
		arr_protocols << item_protocols
	}
	m.protocols = arr_protocols
	if version >= 8 {
		if flexible {
			m.reason = r.read_compact_nullable_string()
		} else {
			m.reason = r.read_nullable_string()
		}
	}
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct JoinGroupResponseMember {
pub mut:
	member_id         string
	instance_id       ?string
	protocol_metadata []u8
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &JoinGroupResponseMember) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_string(m.member_id)
	} else {
		w.write_string(m.member_id)
	}
	if version >= 5 {
		if flexible {
			w.write_compact_nullable_string(m.instance_id)
		} else {
			w.write_nullable_string(m.instance_id)
		}
	}
	if flexible {
		w.write_compact_bytes(m.protocol_metadata)
	} else {
		w.write_bytes(m.protocol_metadata)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m JoinGroupResponseMember) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	if flexible {
		m.member_id = r.read_compact_string()
	} else {
		m.member_id = r.read_string()
	}
	if version >= 5 {
		if flexible {
			m.instance_id = r.read_compact_nullable_string()
		} else {
			m.instance_id = r.read_nullable_string()
		}
	}
	if flexible {
		m.protocol_metadata = r.read_compact_bytes()
	} else {
		m.protocol_metadata = r.read_bytes()
	}
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct JoinGroupResponse {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version         i16
	throttle_millis int
	error_code      i16
	generation      int = -1
	protocol_type   ?string
	protocol        ?string
	leader_id       string
	skip_assignment bool
	member_id       string
	members         []JoinGroupResponseMember
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of JoinGroupResponse (11).
pub fn (m &JoinGroupResponse) key() i16 {
	return 11
}

// max_version returns the maximum wire version this client supports.
pub fn (m &JoinGroupResponse) max_version() i16 {
	return 9
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &JoinGroupResponse) is_flexible() bool {
	return m.version >= 6
}

// write_to encodes m at m.version into w.
pub fn (m &JoinGroupResponse) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &JoinGroupResponse) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if version >= 2 {
		w.write_int32(m.throttle_millis)
	}
	w.write_int16(m.error_code)
	w.write_int32(m.generation)
	if version >= 7 {
		if flexible {
			w.write_compact_nullable_string(m.protocol_type)
		} else {
			w.write_nullable_string(m.protocol_type)
		}
	}
	if version < 7 {
		plain := m.protocol or { '' }
		if flexible {
			w.write_compact_string(plain)
		} else {
			w.write_string(plain)
		}
	} else {
		if flexible {
			w.write_compact_nullable_string(m.protocol)
		} else {
			w.write_nullable_string(m.protocol)
		}
	}
	if flexible {
		w.write_compact_string(m.leader_id)
	} else {
		w.write_string(m.leader_id)
	}
	if version >= 9 {
		w.write_bool(m.skip_assignment)
	}
	if flexible {
		w.write_compact_string(m.member_id)
	} else {
		w.write_string(m.member_id)
	}
	arr_members := m.members
	if flexible {
		w.write_compact_array_len(arr_members.len)
	} else {
		w.write_array_len(arr_members.len)
	}
	for item_members in arr_members {
		item_members.write_to_versioned(mut w, version, flexible)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = JoinGroupResponse{version: v}).
pub fn (mut m JoinGroupResponse) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m JoinGroupResponse) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	if version >= 2 {
		m.throttle_millis = r.read_int32()
	}
	m.error_code = r.read_int16()
	m.generation = r.read_int32()
	if version >= 7 {
		if flexible {
			m.protocol_type = r.read_compact_nullable_string()
		} else {
			m.protocol_type = r.read_nullable_string()
		}
	}
	if version < 7 {
		if flexible {
			m.protocol = r.read_compact_string()
		} else {
			m.protocol = r.read_string()
		}
	} else {
		if flexible {
			m.protocol = r.read_compact_nullable_string()
		} else {
			m.protocol = r.read_nullable_string()
		}
	}
	if flexible {
		m.leader_id = r.read_compact_string()
	} else {
		m.leader_id = r.read_string()
	}
	if version >= 9 {
		m.skip_assignment = r.read_bool()
	}
	if flexible {
		m.member_id = r.read_compact_string()
	} else {
		m.member_id = r.read_string()
	}
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_members := []JoinGroupResponseMember{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_members := JoinGroupResponseMember{}
		item_members.read_from_versioned(mut r, version, flexible)!
		arr_members << item_members
	}
	m.members = arr_members
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}
