// Code generated by `v run generate/` — DO NOT EDIT.
module kmsg

// name_for_key returns the name of the API that a key belongs to,
// or 'Unknown' if the key is unknown.
pub fn name_for_key(key i16) string {
	return match key {
		0 { 'Produce' }
		1 { 'Fetch' }
		2 { 'ListOffsets' }
		3 { 'Metadata' }
		4 { 'LeaderAndISR' }
		5 { 'StopReplica' }
		6 { 'UpdateMetadata' }
		7 { 'ControlledShutdown' }
		8 { 'OffsetCommit' }
		9 { 'OffsetFetch' }
		10 { 'FindCoordinator' }
		11 { 'JoinGroup' }
		12 { 'Heartbeat' }
		13 { 'LeaveGroup' }
		14 { 'SyncGroup' }
		15 { 'DescribeGroups' }
		16 { 'ListGroups' }
		17 { 'SASLHandshake' }
		18 { 'ApiVersions' }
		19 { 'CreateTopics' }
		20 { 'DeleteTopics' }
		21 { 'DeleteRecords' }
		22 { 'InitProducerID' }
		23 { 'OffsetForLeaderEpoch' }
		24 { 'AddPartitionsToTxn' }
		25 { 'AddOffsetsToTxn' }
		26 { 'EndTxn' }
		27 { 'WriteTxnMarkers' }
		28 { 'TxnOffsetCommit' }
		29 { 'DescribeACLs' }
		30 { 'CreateACLs' }
		31 { 'DeleteACLs' }
		32 { 'DescribeConfigs' }
		33 { 'AlterConfigs' }
		34 { 'AlterReplicaLogDirs' }
		35 { 'DescribeLogDirs' }
		36 { 'SASLAuthenticate' }
		37 { 'CreatePartitions' }
		38 { 'CreateDelegationToken' }
		39 { 'RenewDelegationToken' }
		40 { 'ExpireDelegationToken' }
		41 { 'DescribeDelegationToken' }
		42 { 'DeleteGroups' }
		43 { 'ElectLeaders' }
		44 { 'IncrementalAlterConfigs' }
		45 { 'AlterPartitionAssignments' }
		46 { 'ListPartitionReassignments' }
		47 { 'OffsetDelete' }
		48 { 'DescribeClientQuotas' }
		49 { 'AlterClientQuotas' }
		50 { 'DescribeUserSCRAMCredentials' }
		51 { 'AlterUserSCRAMCredentials' }
		52 { 'Vote' }
		53 { 'BeginQuorumEpoch' }
		54 { 'EndQuorumEpoch' }
		55 { 'DescribeQuorum' }
		56 { 'AlterPartition' }
		57 { 'UpdateFeatures' }
		58 { 'Envelope' }
		59 { 'FetchSnapshot' }
		60 { 'DescribeCluster' }
		61 { 'DescribeProducers' }
		62 { 'BrokerRegistration' }
		63 { 'BrokerHeartbeat' }
		64 { 'UnregisterBroker' }
		65 { 'DescribeTransactions' }
		66 { 'ListTransactions' }
		67 { 'AllocateProducerIDs' }
		68 { 'ConsumerGroupHeartbeat' }
		69 { 'ConsumerGroupDescribe' }
		70 { 'ControllerRegistration' }
		71 { 'GetTelemetrySubscriptions' }
		72 { 'PushTelemetry' }
		73 { 'AssignReplicasToDirs' }
		74 { 'ListConfigResources' }
		75 { 'DescribeTopicPartitions' }
		76 { 'ShareGroupHeartbeat' }
		77 { 'ShareGroupDescribe' }
		78 { 'ShareFetch' }
		79 { 'ShareAcknowledge' }
		80 { 'AddRaftVoter' }
		81 { 'RemoveRaftVoter' }
		82 { 'UpdateRaftVoter' }
		83 { 'InitializeShareGroupState' }
		84 { 'ReadShareGroupState' }
		85 { 'WriteShareGroupState' }
		86 { 'DeleteShareGroupState' }
		87 { 'ReadShareGroupStateSummary' }
		88 { 'StreamsGroupHeartbeat' }
		89 { 'StreamsGroupDescribe' }
		90 { 'DescribeShareGroupOffsets' }
		91 { 'AlterShareGroupOffsets' }
		92 { 'DeleteShareGroupOffsets' }
		else { 'Unknown' }
	}
}

// max_key is the highest known API key.
pub const max_key = i16(92)
