// Code generated by `v run generate/` from
// franz-go generate/definitions/02_list_offsets — DO NOT EDIT.
module kmsg

import kbin

pub struct ListOffsetsRequestTopicPartition {
pub mut:
	partition            int
	current_leader_epoch int = -1
	timestamp            i64
	max_num_offsets      int = 1
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &ListOffsetsRequestTopicPartition) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int32(m.partition)
	if version >= 4 {
		w.write_int32(m.current_leader_epoch)
	}
	w.write_int64(m.timestamp)
	if version <= 0 {
		w.write_int32(m.max_num_offsets)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m ListOffsetsRequestTopicPartition) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	m.partition = r.read_int32()
	if version >= 4 {
		m.current_leader_epoch = r.read_int32()
	}
	m.timestamp = r.read_int64()
	if version <= 0 {
		m.max_num_offsets = r.read_int32()
	}
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct ListOffsetsRequestTopic {
pub mut:
	topic      string
	partitions []ListOffsetsRequestTopicPartition
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &ListOffsetsRequestTopic) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_string(m.topic)
	} else {
		w.write_string(m.topic)
	}
	arr_partitions := m.partitions
	if flexible {
		w.write_compact_array_len(arr_partitions.len)
	} else {
		w.write_array_len(arr_partitions.len)
	}
	for item_partitions in arr_partitions {
		item_partitions.write_to_versioned(mut w, version, flexible)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m ListOffsetsRequestTopic) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	if flexible {
		m.topic = r.read_compact_string()
	} else {
		m.topic = r.read_string()
	}
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_partitions := []ListOffsetsRequestTopicPartition{cap: if arr_len > 0 {
		arr_len
	} else {
		0
	}}
	for _ in 0 .. arr_len {
		mut item_partitions := ListOffsetsRequestTopicPartition{}
		item_partitions.read_from_versioned(mut r, version, flexible)!
		arr_partitions << item_partitions
	}
	m.partitions = arr_partitions
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct ListOffsetsRequest {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version         i16
	replica_id      int = -1
	isolation_level i8
	topics          []ListOffsetsRequestTopic
	timeout_millis  int = 30000
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of ListOffsetsRequest (2).
pub fn (m &ListOffsetsRequest) key() i16 {
	return 2
}

// max_version returns the maximum wire version this client supports.
pub fn (m &ListOffsetsRequest) max_version() i16 {
	return 11
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &ListOffsetsRequest) is_flexible() bool {
	return m.version >= 6
}

// write_to encodes m at m.version into w.
pub fn (m &ListOffsetsRequest) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &ListOffsetsRequest) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int32(m.replica_id)
	if version >= 2 {
		w.write_int8(m.isolation_level)
	}
	arr_topics := m.topics
	if flexible {
		w.write_compact_array_len(arr_topics.len)
	} else {
		w.write_array_len(arr_topics.len)
	}
	for item_topics in arr_topics {
		item_topics.write_to_versioned(mut w, version, flexible)
	}
	if version >= 10 {
		w.write_int32(m.timeout_millis)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = ListOffsetsRequest{version: v}).
pub fn (mut m ListOffsetsRequest) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m ListOffsetsRequest) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	m.replica_id = r.read_int32()
	if version >= 2 {
		m.isolation_level = r.read_int8()
	}
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_topics := []ListOffsetsRequestTopic{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_topics := ListOffsetsRequestTopic{}
		item_topics.read_from_versioned(mut r, version, flexible)!
		arr_topics << item_topics
	}
	m.topics = arr_topics
	if version >= 10 {
		m.timeout_millis = r.read_int32()
	}
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct ListOffsetsResponseTopicPartition {
pub mut:
	partition         int
	error_code        i16
	old_style_offsets []i64
	timestamp         i64 = i64(-1)
	offset            i64 = i64(-1)
	leader_epoch      int = -1
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &ListOffsetsResponseTopicPartition) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int32(m.partition)
	w.write_int16(m.error_code)
	if version <= 0 {
		arr_old_style_offsets := m.old_style_offsets
		if flexible {
			w.write_compact_array_len(arr_old_style_offsets.len)
		} else {
			w.write_array_len(arr_old_style_offsets.len)
		}
		for item_old_style_offsets in arr_old_style_offsets {
			w.write_int64(item_old_style_offsets)
		}
	}
	if version >= 1 {
		w.write_int64(m.timestamp)
	}
	if version >= 1 {
		w.write_int64(m.offset)
	}
	if version >= 4 {
		w.write_int32(m.leader_epoch)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m ListOffsetsResponseTopicPartition) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	m.partition = r.read_int32()
	m.error_code = r.read_int16()
	if version <= 0 {
		if flexible {
			arr_len = r.read_compact_array_len()
		} else {
			arr_len = r.read_array_len()
		}
		mut arr_old_style_offsets := []i64{cap: if arr_len > 0 { arr_len } else { 0 }}
		for _ in 0 .. arr_len {
			mut item_old_style_offsets := i64(0)
			item_old_style_offsets = r.read_int64()
			arr_old_style_offsets << item_old_style_offsets
		}
		m.old_style_offsets = arr_old_style_offsets
	}
	if version >= 1 {
		m.timestamp = r.read_int64()
	}
	if version >= 1 {
		m.offset = r.read_int64()
	}
	if version >= 4 {
		m.leader_epoch = r.read_int32()
	}
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct ListOffsetsResponseTopic {
pub mut:
	topic      string
	partitions []ListOffsetsResponseTopicPartition
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &ListOffsetsResponseTopic) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_string(m.topic)
	} else {
		w.write_string(m.topic)
	}
	arr_partitions := m.partitions
	if flexible {
		w.write_compact_array_len(arr_partitions.len)
	} else {
		w.write_array_len(arr_partitions.len)
	}
	for item_partitions in arr_partitions {
		item_partitions.write_to_versioned(mut w, version, flexible)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m ListOffsetsResponseTopic) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	if flexible {
		m.topic = r.read_compact_string()
	} else {
		m.topic = r.read_string()
	}
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_partitions := []ListOffsetsResponseTopicPartition{cap: if arr_len > 0 {
		arr_len
	} else {
		0
	}}
	for _ in 0 .. arr_len {
		mut item_partitions := ListOffsetsResponseTopicPartition{}
		item_partitions.read_from_versioned(mut r, version, flexible)!
		arr_partitions << item_partitions
	}
	m.partitions = arr_partitions
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct ListOffsetsResponse {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version         i16
	throttle_millis int
	topics          []ListOffsetsResponseTopic
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of ListOffsetsResponse (2).
pub fn (m &ListOffsetsResponse) key() i16 {
	return 2
}

// max_version returns the maximum wire version this client supports.
pub fn (m &ListOffsetsResponse) max_version() i16 {
	return 11
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &ListOffsetsResponse) is_flexible() bool {
	return m.version >= 6
}

// write_to encodes m at m.version into w.
pub fn (m &ListOffsetsResponse) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &ListOffsetsResponse) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if version >= 2 {
		w.write_int32(m.throttle_millis)
	}
	arr_topics := m.topics
	if flexible {
		w.write_compact_array_len(arr_topics.len)
	} else {
		w.write_array_len(arr_topics.len)
	}
	for item_topics in arr_topics {
		item_topics.write_to_versioned(mut w, version, flexible)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = ListOffsetsResponse{version: v}).
pub fn (mut m ListOffsetsResponse) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m ListOffsetsResponse) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	if version >= 2 {
		m.throttle_millis = r.read_int32()
	}
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_topics := []ListOffsetsResponseTopic{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_topics := ListOffsetsResponseTopic{}
		item_topics.read_from_versioned(mut r, version, flexible)!
		arr_topics << item_topics
	}
	m.topics = arr_topics
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}
