// Code generated by `v run generate/` from
// franz-go generate/definitions/09_offset_fetch — DO NOT EDIT.
module kmsg

import kbin

pub struct OffsetFetchRequestTopic {
pub mut:
	topic      string
	partitions []int
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &OffsetFetchRequestTopic) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_string(m.topic)
	} else {
		w.write_string(m.topic)
	}
	arr_partitions := m.partitions
	if flexible {
		w.write_compact_array_len(arr_partitions.len)
	} else {
		w.write_array_len(arr_partitions.len)
	}
	for item_partitions in arr_partitions {
		w.write_int32(item_partitions)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m OffsetFetchRequestTopic) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	if flexible {
		m.topic = r.read_compact_string()
	} else {
		m.topic = r.read_string()
	}
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_partitions := []int{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_partitions := 0
		item_partitions = r.read_int32()
		arr_partitions << item_partitions
	}
	m.partitions = arr_partitions
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct OffsetFetchRequestGroupTopic {
pub mut:
	topic      string
	topic_id   [16]u8
	partitions []int
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &OffsetFetchRequestGroupTopic) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if version >= 8 && version <= 9 {
		if flexible {
			w.write_compact_string(m.topic)
		} else {
			w.write_string(m.topic)
		}
	}
	if version >= 10 {
		w.write_uuid(m.topic_id)
	}
	arr_partitions := m.partitions
	if flexible {
		w.write_compact_array_len(arr_partitions.len)
	} else {
		w.write_array_len(arr_partitions.len)
	}
	for item_partitions in arr_partitions {
		w.write_int32(item_partitions)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m OffsetFetchRequestGroupTopic) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	if version >= 8 && version <= 9 {
		if flexible {
			m.topic = r.read_compact_string()
		} else {
			m.topic = r.read_string()
		}
	}
	if version >= 10 {
		m.topic_id = r.read_uuid()
	}
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_partitions := []int{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_partitions := 0
		item_partitions = r.read_int32()
		arr_partitions << item_partitions
	}
	m.partitions = arr_partitions
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct OffsetFetchRequestGroup {
pub mut:
	group        string
	member_id    ?string
	member_epoch int = -1
	topics       ?[]OffsetFetchRequestGroupTopic
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &OffsetFetchRequestGroup) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_string(m.group)
	} else {
		w.write_string(m.group)
	}
	if version >= 9 {
		if flexible {
			w.write_compact_nullable_string(m.member_id)
		} else {
			w.write_nullable_string(m.member_id)
		}
	}
	if version >= 9 {
		w.write_int32(m.member_epoch)
	}
	if arr_topics := m.topics {
		if flexible {
			w.write_compact_array_len(arr_topics.len)
		} else {
			w.write_array_len(arr_topics.len)
		}
		for item_topics in arr_topics {
			item_topics.write_to_versioned(mut w, version, flexible)
		}
	} else {
		if flexible {
			w.write_uvarint(0)
		} else {
			w.write_int32(-1)
		}
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m OffsetFetchRequestGroup) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	if flexible {
		m.group = r.read_compact_string()
	} else {
		m.group = r.read_string()
	}
	if version >= 9 {
		if flexible {
			m.member_id = r.read_compact_nullable_string()
		} else {
			m.member_id = r.read_nullable_string()
		}
	}
	if version >= 9 {
		m.member_epoch = r.read_int32()
	}
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	if arr_len < 0 {
		m.topics = none
	} else {
		mut arr_topics := []OffsetFetchRequestGroupTopic{cap: if arr_len > 0 { arr_len } else { 0 }}
		for _ in 0 .. arr_len {
			mut item_topics := OffsetFetchRequestGroupTopic{}
			item_topics.read_from_versioned(mut r, version, flexible)!
			arr_topics << item_topics
		}
		m.topics = arr_topics
	}
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct OffsetFetchRequest {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version        i16
	group          string
	topics         ?[]OffsetFetchRequestTopic
	groups         []OffsetFetchRequestGroup
	require_stable bool
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of OffsetFetchRequest (9).
pub fn (m &OffsetFetchRequest) key() i16 {
	return 9
}

// max_version returns the maximum wire version this client supports.
pub fn (m &OffsetFetchRequest) max_version() i16 {
	return 10
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &OffsetFetchRequest) is_flexible() bool {
	return m.version >= 6
}

// write_to encodes m at m.version into w.
pub fn (m &OffsetFetchRequest) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &OffsetFetchRequest) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if version <= 7 {
		if flexible {
			w.write_compact_string(m.group)
		} else {
			w.write_string(m.group)
		}
	}
	if version <= 7 {
		if arr_topics := m.topics {
			if flexible {
				w.write_compact_array_len(arr_topics.len)
			} else {
				w.write_array_len(arr_topics.len)
			}
			for item_topics in arr_topics {
				item_topics.write_to_versioned(mut w, version, flexible)
			}
		} else {
			if version >= 2 {
				if flexible {
					w.write_uvarint(0)
				} else {
					w.write_int32(-1)
				}
			} else {
				if flexible {
					w.write_compact_array_len(0)
				} else {
					w.write_array_len(0)
				}
			}
		}
	}
	if version >= 8 {
		arr_groups := m.groups
		if flexible {
			w.write_compact_array_len(arr_groups.len)
		} else {
			w.write_array_len(arr_groups.len)
		}
		for item_groups in arr_groups {
			item_groups.write_to_versioned(mut w, version, flexible)
		}
	}
	if version >= 7 {
		w.write_bool(m.require_stable)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = OffsetFetchRequest{version: v}).
pub fn (mut m OffsetFetchRequest) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m OffsetFetchRequest) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	if version <= 7 {
		if flexible {
			m.group = r.read_compact_string()
		} else {
			m.group = r.read_string()
		}
	}
	if version <= 7 {
		if flexible {
			arr_len = r.read_compact_array_len()
		} else {
			arr_len = r.read_array_len()
		}
		if arr_len < 0 {
			m.topics = none
		} else {
			mut arr_topics := []OffsetFetchRequestTopic{cap: if arr_len > 0 { arr_len } else { 0 }}
			for _ in 0 .. arr_len {
				mut item_topics := OffsetFetchRequestTopic{}
				item_topics.read_from_versioned(mut r, version, flexible)!
				arr_topics << item_topics
			}
			m.topics = arr_topics
		}
	}
	if version >= 8 {
		if flexible {
			arr_len = r.read_compact_array_len()
		} else {
			arr_len = r.read_array_len()
		}
		mut arr_groups := []OffsetFetchRequestGroup{cap: if arr_len > 0 { arr_len } else { 0 }}
		for _ in 0 .. arr_len {
			mut item_groups := OffsetFetchRequestGroup{}
			item_groups.read_from_versioned(mut r, version, flexible)!
			arr_groups << item_groups
		}
		m.groups = arr_groups
	}
	if version >= 7 {
		m.require_stable = r.read_bool()
	}
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct OffsetFetchResponseTopicPartition {
pub mut:
	partition    int
	offset       i64
	leader_epoch int = -1
	metadata     ?string
	error_code   i16
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &OffsetFetchResponseTopicPartition) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int32(m.partition)
	w.write_int64(m.offset)
	if version >= 5 {
		w.write_int32(m.leader_epoch)
	}
	if flexible {
		w.write_compact_nullable_string(m.metadata)
	} else {
		w.write_nullable_string(m.metadata)
	}
	w.write_int16(m.error_code)
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m OffsetFetchResponseTopicPartition) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	m.partition = r.read_int32()
	m.offset = r.read_int64()
	if version >= 5 {
		m.leader_epoch = r.read_int32()
	}
	if flexible {
		m.metadata = r.read_compact_nullable_string()
	} else {
		m.metadata = r.read_nullable_string()
	}
	m.error_code = r.read_int16()
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct OffsetFetchResponseTopic {
pub mut:
	topic      string
	partitions []OffsetFetchResponseTopicPartition
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &OffsetFetchResponseTopic) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_string(m.topic)
	} else {
		w.write_string(m.topic)
	}
	arr_partitions := m.partitions
	if flexible {
		w.write_compact_array_len(arr_partitions.len)
	} else {
		w.write_array_len(arr_partitions.len)
	}
	for item_partitions in arr_partitions {
		item_partitions.write_to_versioned(mut w, version, flexible)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m OffsetFetchResponseTopic) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	if flexible {
		m.topic = r.read_compact_string()
	} else {
		m.topic = r.read_string()
	}
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_partitions := []OffsetFetchResponseTopicPartition{cap: if arr_len > 0 {
		arr_len
	} else {
		0
	}}
	for _ in 0 .. arr_len {
		mut item_partitions := OffsetFetchResponseTopicPartition{}
		item_partitions.read_from_versioned(mut r, version, flexible)!
		arr_partitions << item_partitions
	}
	m.partitions = arr_partitions
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct OffsetFetchResponseGroupTopicPartition {
pub mut:
	partition    int
	offset       i64
	leader_epoch int = -1
	metadata     ?string
	error_code   i16
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &OffsetFetchResponseGroupTopicPartition) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int32(m.partition)
	w.write_int64(m.offset)
	w.write_int32(m.leader_epoch)
	if flexible {
		w.write_compact_nullable_string(m.metadata)
	} else {
		w.write_nullable_string(m.metadata)
	}
	w.write_int16(m.error_code)
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m OffsetFetchResponseGroupTopicPartition) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	m.partition = r.read_int32()
	m.offset = r.read_int64()
	m.leader_epoch = r.read_int32()
	if flexible {
		m.metadata = r.read_compact_nullable_string()
	} else {
		m.metadata = r.read_nullable_string()
	}
	m.error_code = r.read_int16()
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct OffsetFetchResponseGroupTopic {
pub mut:
	topic      string
	topic_id   [16]u8
	partitions []OffsetFetchResponseGroupTopicPartition
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &OffsetFetchResponseGroupTopic) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if version >= 8 && version <= 9 {
		if flexible {
			w.write_compact_string(m.topic)
		} else {
			w.write_string(m.topic)
		}
	}
	if version >= 10 {
		w.write_uuid(m.topic_id)
	}
	arr_partitions := m.partitions
	if flexible {
		w.write_compact_array_len(arr_partitions.len)
	} else {
		w.write_array_len(arr_partitions.len)
	}
	for item_partitions in arr_partitions {
		item_partitions.write_to_versioned(mut w, version, flexible)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m OffsetFetchResponseGroupTopic) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	if version >= 8 && version <= 9 {
		if flexible {
			m.topic = r.read_compact_string()
		} else {
			m.topic = r.read_string()
		}
	}
	if version >= 10 {
		m.topic_id = r.read_uuid()
	}
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_partitions := []OffsetFetchResponseGroupTopicPartition{cap: if arr_len > 0 {
		arr_len
	} else {
		0
	}}
	for _ in 0 .. arr_len {
		mut item_partitions := OffsetFetchResponseGroupTopicPartition{}
		item_partitions.read_from_versioned(mut r, version, flexible)!
		arr_partitions << item_partitions
	}
	m.partitions = arr_partitions
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct OffsetFetchResponseGroup {
pub mut:
	group      string
	topics     []OffsetFetchResponseGroupTopic
	error_code i16
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &OffsetFetchResponseGroup) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_string(m.group)
	} else {
		w.write_string(m.group)
	}
	arr_topics := m.topics
	if flexible {
		w.write_compact_array_len(arr_topics.len)
	} else {
		w.write_array_len(arr_topics.len)
	}
	for item_topics in arr_topics {
		item_topics.write_to_versioned(mut w, version, flexible)
	}
	w.write_int16(m.error_code)
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m OffsetFetchResponseGroup) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	if flexible {
		m.group = r.read_compact_string()
	} else {
		m.group = r.read_string()
	}
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_topics := []OffsetFetchResponseGroupTopic{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_topics := OffsetFetchResponseGroupTopic{}
		item_topics.read_from_versioned(mut r, version, flexible)!
		arr_topics << item_topics
	}
	m.topics = arr_topics
	m.error_code = r.read_int16()
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct OffsetFetchResponse {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version         i16
	throttle_millis int
	topics          []OffsetFetchResponseTopic
	error_code      i16
	groups          []OffsetFetchResponseGroup
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of OffsetFetchResponse (9).
pub fn (m &OffsetFetchResponse) key() i16 {
	return 9
}

// max_version returns the maximum wire version this client supports.
pub fn (m &OffsetFetchResponse) max_version() i16 {
	return 10
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &OffsetFetchResponse) is_flexible() bool {
	return m.version >= 6
}

// write_to encodes m at m.version into w.
pub fn (m &OffsetFetchResponse) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &OffsetFetchResponse) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if version >= 3 {
		w.write_int32(m.throttle_millis)
	}
	if version <= 7 {
		arr_topics := m.topics
		if flexible {
			w.write_compact_array_len(arr_topics.len)
		} else {
			w.write_array_len(arr_topics.len)
		}
		for item_topics in arr_topics {
			item_topics.write_to_versioned(mut w, version, flexible)
		}
	}
	if version >= 2 && version <= 7 {
		w.write_int16(m.error_code)
	}
	if version >= 8 {
		arr_groups := m.groups
		if flexible {
			w.write_compact_array_len(arr_groups.len)
		} else {
			w.write_array_len(arr_groups.len)
		}
		for item_groups in arr_groups {
			item_groups.write_to_versioned(mut w, version, flexible)
		}
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = OffsetFetchResponse{version: v}).
pub fn (mut m OffsetFetchResponse) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m OffsetFetchResponse) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	if version >= 3 {
		m.throttle_millis = r.read_int32()
	}
	if version <= 7 {
		if flexible {
			arr_len = r.read_compact_array_len()
		} else {
			arr_len = r.read_array_len()
		}
		mut arr_topics := []OffsetFetchResponseTopic{cap: if arr_len > 0 { arr_len } else { 0 }}
		for _ in 0 .. arr_len {
			mut item_topics := OffsetFetchResponseTopic{}
			item_topics.read_from_versioned(mut r, version, flexible)!
			arr_topics << item_topics
		}
		m.topics = arr_topics
	}
	if version >= 2 && version <= 7 {
		m.error_code = r.read_int16()
	}
	if version >= 8 {
		if flexible {
			arr_len = r.read_compact_array_len()
		} else {
			arr_len = r.read_array_len()
		}
		mut arr_groups := []OffsetFetchResponseGroup{cap: if arr_len > 0 { arr_len } else { 0 }}
		for _ in 0 .. arr_len {
			mut item_groups := OffsetFetchResponseGroup{}
			item_groups.read_from_versioned(mut r, version, flexible)!
			arr_groups << item_groups
		}
		m.groups = arr_groups
	}
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}
