// Code generated by `v run generate/` from
// franz-go generate/definitions/36_sasl_authenticate — DO NOT EDIT.
module kmsg

import kbin

pub struct SASLAuthenticateRequest {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version         i16
	sasl_auth_bytes []u8
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of SASLAuthenticateRequest (36).
pub fn (m &SASLAuthenticateRequest) key() i16 {
	return 36
}

// max_version returns the maximum wire version this client supports.
pub fn (m &SASLAuthenticateRequest) max_version() i16 {
	return 2
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &SASLAuthenticateRequest) is_flexible() bool {
	return m.version >= 2
}

// write_to encodes m at m.version into w.
pub fn (m &SASLAuthenticateRequest) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &SASLAuthenticateRequest) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_bytes(m.sasl_auth_bytes)
	} else {
		w.write_bytes(m.sasl_auth_bytes)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = SASLAuthenticateRequest{version: v}).
pub fn (mut m SASLAuthenticateRequest) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m SASLAuthenticateRequest) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	if flexible {
		m.sasl_auth_bytes = r.read_compact_bytes()
	} else {
		m.sasl_auth_bytes = r.read_bytes()
	}
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct SASLAuthenticateResponse {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version                 i16
	error_code              i16
	error_message           ?string
	sasl_auth_bytes         []u8
	session_lifetime_millis i64
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of SASLAuthenticateResponse (36).
pub fn (m &SASLAuthenticateResponse) key() i16 {
	return 36
}

// max_version returns the maximum wire version this client supports.
pub fn (m &SASLAuthenticateResponse) max_version() i16 {
	return 2
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &SASLAuthenticateResponse) is_flexible() bool {
	return m.version >= 2
}

// write_to encodes m at m.version into w.
pub fn (m &SASLAuthenticateResponse) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &SASLAuthenticateResponse) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int16(m.error_code)
	if flexible {
		w.write_compact_nullable_string(m.error_message)
	} else {
		w.write_nullable_string(m.error_message)
	}
	if flexible {
		w.write_compact_bytes(m.sasl_auth_bytes)
	} else {
		w.write_bytes(m.sasl_auth_bytes)
	}
	if version >= 1 {
		w.write_int64(m.session_lifetime_millis)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = SASLAuthenticateResponse{version: v}).
pub fn (mut m SASLAuthenticateResponse) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m SASLAuthenticateResponse) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	m.error_code = r.read_int16()
	if flexible {
		m.error_message = r.read_compact_nullable_string()
	} else {
		m.error_message = r.read_nullable_string()
	}
	if flexible {
		m.sasl_auth_bytes = r.read_compact_bytes()
	} else {
		m.sasl_auth_bytes = r.read_bytes()
	}
	if version >= 1 {
		m.session_lifetime_millis = r.read_int64()
	}
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}
