// Code generated by `v run generate/` from
// franz-go generate/definitions/89_streams_group_describe — DO NOT EDIT.
module kmsg

import kbin

pub struct StreamsAssignment {
pub mut:
	active_tasks  []TaskIDs
	standby_tasks []TaskIDs
	warmup_tasks  []TaskIDs
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &StreamsAssignment) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	arr_active_tasks := m.active_tasks
	if flexible {
		w.write_compact_array_len(arr_active_tasks.len)
	} else {
		w.write_array_len(arr_active_tasks.len)
	}
	for item_active_tasks in arr_active_tasks {
		item_active_tasks.write_to_versioned(mut w, version, flexible)
	}
	arr_standby_tasks := m.standby_tasks
	if flexible {
		w.write_compact_array_len(arr_standby_tasks.len)
	} else {
		w.write_array_len(arr_standby_tasks.len)
	}
	for item_standby_tasks in arr_standby_tasks {
		item_standby_tasks.write_to_versioned(mut w, version, flexible)
	}
	arr_warmup_tasks := m.warmup_tasks
	if flexible {
		w.write_compact_array_len(arr_warmup_tasks.len)
	} else {
		w.write_array_len(arr_warmup_tasks.len)
	}
	for item_warmup_tasks in arr_warmup_tasks {
		item_warmup_tasks.write_to_versioned(mut w, version, flexible)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m StreamsAssignment) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_active_tasks := []TaskIDs{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_active_tasks := TaskIDs{}
		item_active_tasks.read_from_versioned(mut r, version, flexible)!
		arr_active_tasks << item_active_tasks
	}
	m.active_tasks = arr_active_tasks
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_standby_tasks := []TaskIDs{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_standby_tasks := TaskIDs{}
		item_standby_tasks.read_from_versioned(mut r, version, flexible)!
		arr_standby_tasks << item_standby_tasks
	}
	m.standby_tasks = arr_standby_tasks
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_warmup_tasks := []TaskIDs{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_warmup_tasks := TaskIDs{}
		item_warmup_tasks.read_from_versioned(mut r, version, flexible)!
		arr_warmup_tasks << item_warmup_tasks
	}
	m.warmup_tasks = arr_warmup_tasks
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct StreamsGroupDescribeRequest {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version                       i16
	groups                        []string
	include_authorized_operations bool
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of StreamsGroupDescribeRequest (89).
pub fn (m &StreamsGroupDescribeRequest) key() i16 {
	return 89
}

// max_version returns the maximum wire version this client supports.
pub fn (m &StreamsGroupDescribeRequest) max_version() i16 {
	return 0
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &StreamsGroupDescribeRequest) is_flexible() bool {
	return m.version >= 0
}

// write_to encodes m at m.version into w.
pub fn (m &StreamsGroupDescribeRequest) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &StreamsGroupDescribeRequest) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	arr_groups := m.groups
	if flexible {
		w.write_compact_array_len(arr_groups.len)
	} else {
		w.write_array_len(arr_groups.len)
	}
	for item_groups in arr_groups {
		if flexible {
			w.write_compact_string(item_groups)
		} else {
			w.write_string(item_groups)
		}
	}
	w.write_bool(m.include_authorized_operations)
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = StreamsGroupDescribeRequest{version: v}).
pub fn (mut m StreamsGroupDescribeRequest) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m StreamsGroupDescribeRequest) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_groups := []string{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_groups := ''
		if flexible {
			item_groups = r.read_compact_string()
		} else {
			item_groups = r.read_string()
		}
		arr_groups << item_groups
	}
	m.groups = arr_groups
	m.include_authorized_operations = r.read_bool()
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct StreamsGroupDescribeResponseGroupTopologySubtopologie {
pub mut:
	subtopology_id            string
	source_topics             []string
	repartition_sink_topics   []string
	state_changelog_topics    []TopicInfo
	repartition_source_topics []TopicInfo
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &StreamsGroupDescribeResponseGroupTopologySubtopologie) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_string(m.subtopology_id)
	} else {
		w.write_string(m.subtopology_id)
	}
	arr_source_topics := m.source_topics
	if flexible {
		w.write_compact_array_len(arr_source_topics.len)
	} else {
		w.write_array_len(arr_source_topics.len)
	}
	for item_source_topics in arr_source_topics {
		if flexible {
			w.write_compact_string(item_source_topics)
		} else {
			w.write_string(item_source_topics)
		}
	}
	arr_repartition_sink_topics := m.repartition_sink_topics
	if flexible {
		w.write_compact_array_len(arr_repartition_sink_topics.len)
	} else {
		w.write_array_len(arr_repartition_sink_topics.len)
	}
	for item_repartition_sink_topics in arr_repartition_sink_topics {
		if flexible {
			w.write_compact_string(item_repartition_sink_topics)
		} else {
			w.write_string(item_repartition_sink_topics)
		}
	}
	arr_state_changelog_topics := m.state_changelog_topics
	if flexible {
		w.write_compact_array_len(arr_state_changelog_topics.len)
	} else {
		w.write_array_len(arr_state_changelog_topics.len)
	}
	for item_state_changelog_topics in arr_state_changelog_topics {
		item_state_changelog_topics.write_to_versioned(mut w, version, flexible)
	}
	arr_repartition_source_topics := m.repartition_source_topics
	if flexible {
		w.write_compact_array_len(arr_repartition_source_topics.len)
	} else {
		w.write_array_len(arr_repartition_source_topics.len)
	}
	for item_repartition_source_topics in arr_repartition_source_topics {
		item_repartition_source_topics.write_to_versioned(mut w, version, flexible)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m StreamsGroupDescribeResponseGroupTopologySubtopologie) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	if flexible {
		m.subtopology_id = r.read_compact_string()
	} else {
		m.subtopology_id = r.read_string()
	}
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_source_topics := []string{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_source_topics := ''
		if flexible {
			item_source_topics = r.read_compact_string()
		} else {
			item_source_topics = r.read_string()
		}
		arr_source_topics << item_source_topics
	}
	m.source_topics = arr_source_topics
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_repartition_sink_topics := []string{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_repartition_sink_topics := ''
		if flexible {
			item_repartition_sink_topics = r.read_compact_string()
		} else {
			item_repartition_sink_topics = r.read_string()
		}
		arr_repartition_sink_topics << item_repartition_sink_topics
	}
	m.repartition_sink_topics = arr_repartition_sink_topics
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_state_changelog_topics := []TopicInfo{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_state_changelog_topics := TopicInfo{}
		item_state_changelog_topics.read_from_versioned(mut r, version, flexible)!
		arr_state_changelog_topics << item_state_changelog_topics
	}
	m.state_changelog_topics = arr_state_changelog_topics
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_repartition_source_topics := []TopicInfo{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_repartition_source_topics := TopicInfo{}
		item_repartition_source_topics.read_from_versioned(mut r, version, flexible)!
		arr_repartition_source_topics << item_repartition_source_topics
	}
	m.repartition_source_topics = arr_repartition_source_topics
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct StreamsGroupDescribeResponseGroupTopology {
pub mut:
	epoch         int
	subtopologies ?[]StreamsGroupDescribeResponseGroupTopologySubtopologie
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &StreamsGroupDescribeResponseGroupTopology) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int32(m.epoch)
	if arr_subtopologies := m.subtopologies {
		if flexible {
			w.write_compact_array_len(arr_subtopologies.len)
		} else {
			w.write_array_len(arr_subtopologies.len)
		}
		for item_subtopologies in arr_subtopologies {
			item_subtopologies.write_to_versioned(mut w, version, flexible)
		}
	} else {
		if flexible {
			w.write_uvarint(0)
		} else {
			w.write_int32(-1)
		}
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m StreamsGroupDescribeResponseGroupTopology) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	m.epoch = r.read_int32()
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	if arr_len < 0 {
		m.subtopologies = none
	} else {
		mut arr_subtopologies := []StreamsGroupDescribeResponseGroupTopologySubtopologie{cap: if arr_len > 0 {
			arr_len
		} else {
			0
		}}
		for _ in 0 .. arr_len {
			mut item_subtopologies := StreamsGroupDescribeResponseGroupTopologySubtopologie{}
			item_subtopologies.read_from_versioned(mut r, version, flexible)!
			arr_subtopologies << item_subtopologies
		}
		m.subtopologies = arr_subtopologies
	}
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct StreamsGroupDescribeResponseGroupMemberUserEndpoint {
pub mut:
	host string
	port u16
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &StreamsGroupDescribeResponseGroupMemberUserEndpoint) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_string(m.host)
	} else {
		w.write_string(m.host)
	}
	w.write_uint16(m.port)
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m StreamsGroupDescribeResponseGroupMemberUserEndpoint) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	if flexible {
		m.host = r.read_compact_string()
	} else {
		m.host = r.read_string()
	}
	m.port = r.read_uint16()
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct StreamsGroupDescribeResponseGroupMemberClientTag {
pub mut:
	key   string
	value string
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &StreamsGroupDescribeResponseGroupMemberClientTag) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_string(m.key)
	} else {
		w.write_string(m.key)
	}
	if flexible {
		w.write_compact_string(m.value)
	} else {
		w.write_string(m.value)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m StreamsGroupDescribeResponseGroupMemberClientTag) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	if flexible {
		m.key = r.read_compact_string()
	} else {
		m.key = r.read_string()
	}
	if flexible {
		m.value = r.read_compact_string()
	} else {
		m.value = r.read_string()
	}
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct StreamsGroupDescribeResponseGroupMember {
pub mut:
	member_id         string
	member_epoch      int
	instance_id       ?string
	rack_id           ?string
	client_id         string
	client_host       string
	topology_epoch    int
	process_id        string
	user_endpoint     ?StreamsGroupDescribeResponseGroupMemberUserEndpoint
	client_tags       []StreamsGroupDescribeResponseGroupMemberClientTag
	task_offsets      []TaskOffset
	task_end_offsets  []TaskOffset
	assignment        StreamsAssignment
	target_assignment StreamsAssignment
	is_classic        bool
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &StreamsGroupDescribeResponseGroupMember) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_string(m.member_id)
	} else {
		w.write_string(m.member_id)
	}
	w.write_int32(m.member_epoch)
	if flexible {
		w.write_compact_nullable_string(m.instance_id)
	} else {
		w.write_nullable_string(m.instance_id)
	}
	if flexible {
		w.write_compact_nullable_string(m.rack_id)
	} else {
		w.write_nullable_string(m.rack_id)
	}
	if flexible {
		w.write_compact_string(m.client_id)
	} else {
		w.write_string(m.client_id)
	}
	if flexible {
		w.write_compact_string(m.client_host)
	} else {
		w.write_string(m.client_host)
	}
	w.write_int32(m.topology_epoch)
	if flexible {
		w.write_compact_string(m.process_id)
	} else {
		w.write_string(m.process_id)
	}
	if sub_user_endpoint := m.user_endpoint {
		w.write_int8(1)
		sub_user_endpoint.write_to_versioned(mut w, version, flexible)
	} else {
		w.write_int8(-1)
	}
	arr_client_tags := m.client_tags
	if flexible {
		w.write_compact_array_len(arr_client_tags.len)
	} else {
		w.write_array_len(arr_client_tags.len)
	}
	for item_client_tags in arr_client_tags {
		item_client_tags.write_to_versioned(mut w, version, flexible)
	}
	arr_task_offsets := m.task_offsets
	if flexible {
		w.write_compact_array_len(arr_task_offsets.len)
	} else {
		w.write_array_len(arr_task_offsets.len)
	}
	for item_task_offsets in arr_task_offsets {
		item_task_offsets.write_to_versioned(mut w, version, flexible)
	}
	arr_task_end_offsets := m.task_end_offsets
	if flexible {
		w.write_compact_array_len(arr_task_end_offsets.len)
	} else {
		w.write_array_len(arr_task_end_offsets.len)
	}
	for item_task_end_offsets in arr_task_end_offsets {
		item_task_end_offsets.write_to_versioned(mut w, version, flexible)
	}
	m.assignment.write_to_versioned(mut w, version, flexible)
	m.target_assignment.write_to_versioned(mut w, version, flexible)
	w.write_bool(m.is_classic)
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m StreamsGroupDescribeResponseGroupMember) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	if flexible {
		m.member_id = r.read_compact_string()
	} else {
		m.member_id = r.read_string()
	}
	m.member_epoch = r.read_int32()
	if flexible {
		m.instance_id = r.read_compact_nullable_string()
	} else {
		m.instance_id = r.read_nullable_string()
	}
	if flexible {
		m.rack_id = r.read_compact_nullable_string()
	} else {
		m.rack_id = r.read_nullable_string()
	}
	if flexible {
		m.client_id = r.read_compact_string()
	} else {
		m.client_id = r.read_string()
	}
	if flexible {
		m.client_host = r.read_compact_string()
	} else {
		m.client_host = r.read_string()
	}
	m.topology_epoch = r.read_int32()
	if flexible {
		m.process_id = r.read_compact_string()
	} else {
		m.process_id = r.read_string()
	}
	if r.read_int8() < 0 {
		m.user_endpoint = none
	} else {
		mut sub_user_endpoint := StreamsGroupDescribeResponseGroupMemberUserEndpoint{}
		sub_user_endpoint.read_from_versioned(mut r, version, flexible)!
		m.user_endpoint = sub_user_endpoint
	}
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_client_tags := []StreamsGroupDescribeResponseGroupMemberClientTag{cap: if arr_len > 0 {
		arr_len
	} else {
		0
	}}
	for _ in 0 .. arr_len {
		mut item_client_tags := StreamsGroupDescribeResponseGroupMemberClientTag{}
		item_client_tags.read_from_versioned(mut r, version, flexible)!
		arr_client_tags << item_client_tags
	}
	m.client_tags = arr_client_tags
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_task_offsets := []TaskOffset{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_task_offsets := TaskOffset{}
		item_task_offsets.read_from_versioned(mut r, version, flexible)!
		arr_task_offsets << item_task_offsets
	}
	m.task_offsets = arr_task_offsets
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_task_end_offsets := []TaskOffset{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_task_end_offsets := TaskOffset{}
		item_task_end_offsets.read_from_versioned(mut r, version, flexible)!
		arr_task_end_offsets << item_task_end_offsets
	}
	m.task_end_offsets = arr_task_end_offsets
	m.assignment.read_from_versioned(mut r, version, flexible)!
	m.target_assignment.read_from_versioned(mut r, version, flexible)!
	m.is_classic = r.read_bool()
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct StreamsGroupDescribeResponseGroup {
pub mut:
	error_code            i16
	error_message         ?string
	group                 string
	state                 string
	epoch                 int
	assignment_epoch      int
	topology              ?StreamsGroupDescribeResponseGroupTopology
	members               []StreamsGroupDescribeResponseGroupMember
	authorized_operations int = -2147483648
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &StreamsGroupDescribeResponseGroup) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int16(m.error_code)
	if flexible {
		w.write_compact_nullable_string(m.error_message)
	} else {
		w.write_nullable_string(m.error_message)
	}
	if flexible {
		w.write_compact_string(m.group)
	} else {
		w.write_string(m.group)
	}
	if flexible {
		w.write_compact_string(m.state)
	} else {
		w.write_string(m.state)
	}
	w.write_int32(m.epoch)
	w.write_int32(m.assignment_epoch)
	if sub_topology := m.topology {
		w.write_int8(1)
		sub_topology.write_to_versioned(mut w, version, flexible)
	} else {
		w.write_int8(-1)
	}
	arr_members := m.members
	if flexible {
		w.write_compact_array_len(arr_members.len)
	} else {
		w.write_array_len(arr_members.len)
	}
	for item_members in arr_members {
		item_members.write_to_versioned(mut w, version, flexible)
	}
	w.write_int32(m.authorized_operations)
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m StreamsGroupDescribeResponseGroup) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	m.error_code = r.read_int16()
	if flexible {
		m.error_message = r.read_compact_nullable_string()
	} else {
		m.error_message = r.read_nullable_string()
	}
	if flexible {
		m.group = r.read_compact_string()
	} else {
		m.group = r.read_string()
	}
	if flexible {
		m.state = r.read_compact_string()
	} else {
		m.state = r.read_string()
	}
	m.epoch = r.read_int32()
	m.assignment_epoch = r.read_int32()
	if r.read_int8() < 0 {
		m.topology = none
	} else {
		mut sub_topology := StreamsGroupDescribeResponseGroupTopology{}
		sub_topology.read_from_versioned(mut r, version, flexible)!
		m.topology = sub_topology
	}
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_members := []StreamsGroupDescribeResponseGroupMember{cap: if arr_len > 0 {
		arr_len
	} else {
		0
	}}
	for _ in 0 .. arr_len {
		mut item_members := StreamsGroupDescribeResponseGroupMember{}
		item_members.read_from_versioned(mut r, version, flexible)!
		arr_members << item_members
	}
	m.members = arr_members
	m.authorized_operations = r.read_int32()
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct StreamsGroupDescribeResponse {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version         i16
	throttle_millis int
	groups          []StreamsGroupDescribeResponseGroup
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of StreamsGroupDescribeResponse (89).
pub fn (m &StreamsGroupDescribeResponse) key() i16 {
	return 89
}

// max_version returns the maximum wire version this client supports.
pub fn (m &StreamsGroupDescribeResponse) max_version() i16 {
	return 0
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &StreamsGroupDescribeResponse) is_flexible() bool {
	return m.version >= 0
}

// write_to encodes m at m.version into w.
pub fn (m &StreamsGroupDescribeResponse) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &StreamsGroupDescribeResponse) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int32(m.throttle_millis)
	arr_groups := m.groups
	if flexible {
		w.write_compact_array_len(arr_groups.len)
	} else {
		w.write_array_len(arr_groups.len)
	}
	for item_groups in arr_groups {
		item_groups.write_to_versioned(mut w, version, flexible)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = StreamsGroupDescribeResponse{version: v}).
pub fn (mut m StreamsGroupDescribeResponse) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m StreamsGroupDescribeResponse) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	m.throttle_millis = r.read_int32()
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_groups := []StreamsGroupDescribeResponseGroup{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_groups := StreamsGroupDescribeResponseGroup{}
		item_groups.read_from_versioned(mut r, version, flexible)!
		arr_groups << item_groups
	}
	m.groups = arr_groups
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}
