// Code generated by `v run generate/` from
// franz-go generate/definitions/64_unregister_broker — DO NOT EDIT.
module kmsg

import kbin

pub struct UnregisterBrokerRequest {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version   i16
	broker_id int
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of UnregisterBrokerRequest (64).
pub fn (m &UnregisterBrokerRequest) key() i16 {
	return 64
}

// max_version returns the maximum wire version this client supports.
pub fn (m &UnregisterBrokerRequest) max_version() i16 {
	return 0
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &UnregisterBrokerRequest) is_flexible() bool {
	return m.version >= 0
}

// write_to encodes m at m.version into w.
pub fn (m &UnregisterBrokerRequest) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &UnregisterBrokerRequest) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int32(m.broker_id)
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = UnregisterBrokerRequest{version: v}).
pub fn (mut m UnregisterBrokerRequest) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m UnregisterBrokerRequest) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	m.broker_id = r.read_int32()
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct UnregisterBrokerResponse {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version         i16
	throttle_millis int
	error_code      i16
	error_message   ?string
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of UnregisterBrokerResponse (64).
pub fn (m &UnregisterBrokerResponse) key() i16 {
	return 64
}

// max_version returns the maximum wire version this client supports.
pub fn (m &UnregisterBrokerResponse) max_version() i16 {
	return 0
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &UnregisterBrokerResponse) is_flexible() bool {
	return m.version >= 0
}

// write_to encodes m at m.version into w.
pub fn (m &UnregisterBrokerResponse) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &UnregisterBrokerResponse) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int32(m.throttle_millis)
	w.write_int16(m.error_code)
	if flexible {
		w.write_compact_nullable_string(m.error_message)
	} else {
		w.write_nullable_string(m.error_message)
	}
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = UnregisterBrokerResponse{version: v}).
pub fn (mut m UnregisterBrokerResponse) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m UnregisterBrokerResponse) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	m.throttle_millis = r.read_int32()
	m.error_code = r.read_int16()
	if flexible {
		m.error_message = r.read_compact_nullable_string()
	} else {
		m.error_message = r.read_nullable_string()
	}
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}
