// Code generated by `v run generate/` from
// franz-go generate/definitions/82_update_raft_voter — DO NOT EDIT.
module kmsg

import kbin

pub struct UpdateRaftVoterRequestListener {
pub mut:
	name string
	host string
	port u16
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &UpdateRaftVoterRequestListener) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_string(m.name)
	} else {
		w.write_string(m.name)
	}
	if flexible {
		w.write_compact_string(m.host)
	} else {
		w.write_string(m.host)
	}
	w.write_uint16(m.port)
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m UpdateRaftVoterRequestListener) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	if flexible {
		m.name = r.read_compact_string()
	} else {
		m.name = r.read_string()
	}
	if flexible {
		m.host = r.read_compact_string()
	} else {
		m.host = r.read_string()
	}
	m.port = r.read_uint16()
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct UpdateRaftVoterRequestKRaftVersionFeature {
pub mut:
	min_supported_version i16
	max_supported_version i16
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &UpdateRaftVoterRequestKRaftVersionFeature) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int16(m.min_supported_version)
	w.write_int16(m.max_supported_version)
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m UpdateRaftVoterRequestKRaftVersionFeature) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	m.min_supported_version = r.read_int16()
	m.max_supported_version = r.read_int16()
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct UpdateRaftVoterRequest {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version                i16
	cluster_id             ?string
	current_leader_epoch   int
	voter_id               int
	voter_directory_id     [16]u8
	listeners              []UpdateRaftVoterRequestListener
	k_raft_version_feature UpdateRaftVoterRequestKRaftVersionFeature
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of UpdateRaftVoterRequest (82).
pub fn (m &UpdateRaftVoterRequest) key() i16 {
	return 82
}

// max_version returns the maximum wire version this client supports.
pub fn (m &UpdateRaftVoterRequest) max_version() i16 {
	return 0
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &UpdateRaftVoterRequest) is_flexible() bool {
	return m.version >= 0
}

// write_to encodes m at m.version into w.
pub fn (m &UpdateRaftVoterRequest) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &UpdateRaftVoterRequest) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	if flexible {
		w.write_compact_nullable_string(m.cluster_id)
	} else {
		w.write_nullable_string(m.cluster_id)
	}
	w.write_int32(m.current_leader_epoch)
	w.write_int32(m.voter_id)
	w.write_uuid(m.voter_directory_id)
	arr_listeners := m.listeners
	if flexible {
		w.write_compact_array_len(arr_listeners.len)
	} else {
		w.write_array_len(arr_listeners.len)
	}
	for item_listeners in arr_listeners {
		item_listeners.write_to_versioned(mut w, version, flexible)
	}
	m.k_raft_version_feature.write_to_versioned(mut w, version, flexible)
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = UpdateRaftVoterRequest{version: v}).
pub fn (mut m UpdateRaftVoterRequest) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m UpdateRaftVoterRequest) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	mut arr_len := 0
	_ = arr_len
	if flexible {
		m.cluster_id = r.read_compact_nullable_string()
	} else {
		m.cluster_id = r.read_nullable_string()
	}
	m.current_leader_epoch = r.read_int32()
	m.voter_id = r.read_int32()
	m.voter_directory_id = r.read_uuid()
	if flexible {
		arr_len = r.read_compact_array_len()
	} else {
		arr_len = r.read_array_len()
	}
	mut arr_listeners := []UpdateRaftVoterRequestListener{cap: if arr_len > 0 { arr_len } else { 0 }}
	for _ in 0 .. arr_len {
		mut item_listeners := UpdateRaftVoterRequestListener{}
		item_listeners.read_from_versioned(mut r, version, flexible)!
		arr_listeners << item_listeners
	}
	m.listeners = arr_listeners
	m.k_raft_version_feature.read_from_versioned(mut r, version, flexible)!
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct UpdateRaftVoterResponseCurrentLeader {
pub mut:
	leader_id    int = -1
	leader_epoch int = -1
	host         string
	port         int
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

fn (m &UpdateRaftVoterResponseCurrentLeader) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int32(m.leader_id)
	w.write_int32(m.leader_epoch)
	if flexible {
		w.write_compact_string(m.host)
	} else {
		w.write_string(m.host)
	}
	w.write_int32(m.port)
	if flexible {
		w.write_uvarint(u32(m.unknown_tags.len))
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

fn (mut m UpdateRaftVoterResponseCurrentLeader) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	m.leader_id = r.read_int32()
	m.leader_epoch = r.read_int32()
	if flexible {
		m.host = r.read_compact_string()
	} else {
		m.host = r.read_string()
	}
	m.port = r.read_int32()
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			data := r.span(size)
			if r.ok() {
				m.unknown_tags << UnknownTag{
					tag:  tag
					data: data.clone()
				}
			}
		}
	}
	r.complete()!
}

pub struct UpdateRaftVoterResponse {
pub mut:
	// version is the wire version to encode with / that was used
	// by the request this response answers. Set it before use.
	version         i16
	throttle_millis int
	error_code      i16
	current_leader  UpdateRaftVoterResponseCurrentLeader
	// unknown_tags preserves tagged fields this client does not know.
	unknown_tags []UnknownTag
}

// key returns the Kafka API key of UpdateRaftVoterResponse (82).
pub fn (m &UpdateRaftVoterResponse) key() i16 {
	return 82
}

// max_version returns the maximum wire version this client supports.
pub fn (m &UpdateRaftVoterResponse) max_version() i16 {
	return 0
}

// is_flexible reports whether m.version uses flexible (compact) encoding.
pub fn (m &UpdateRaftVoterResponse) is_flexible() bool {
	return m.version >= 0
}

// write_to encodes m at m.version into w.
pub fn (m &UpdateRaftVoterResponse) write_to(mut w kbin.Writer) {
	version := m.version
	flexible := m.is_flexible()
	m.write_to_versioned(mut w, version, flexible)
}

fn (m &UpdateRaftVoterResponse) write_to_versioned(mut w kbin.Writer, version i16, flexible bool) {
	_ = version
	_ = flexible
	w.write_int32(m.throttle_millis)
	w.write_int16(m.error_code)
	if flexible {
		mut tag_buf := kbin.Writer{}
		mut num_tags := u32(0)
		if m.current_leader != UpdateRaftVoterResponseCurrentLeader{} {
			num_tags++
			mut tw := kbin.Writer{}
			m.current_leader.write_to_versioned(mut tw, version, flexible)
			tag_buf.write_uvarint(0)
			tag_buf.write_uvarint(u32(tw.buf.len))
			tag_buf.buf << tw.buf
		}
		w.write_uvarint(num_tags + u32(m.unknown_tags.len))
		w.buf << tag_buf.buf
		write_unknown_tags(mut w, m.unknown_tags)
	}
}

// read_from decodes into m using m.version; call on a fresh
// struct (or after reassigning m = UpdateRaftVoterResponse{version: v}).
pub fn (mut m UpdateRaftVoterResponse) read_from(mut r kbin.Reader) ! {
	version := m.version
	flexible := m.is_flexible()
	m.read_from_versioned(mut r, version, flexible)!
	r.complete()!
}

fn (mut m UpdateRaftVoterResponse) read_from_versioned(mut r kbin.Reader, version i16, flexible bool) ! {
	_ = version
	_ = flexible
	m.throttle_millis = r.read_int32()
	m.error_code = r.read_int16()
	if flexible {
		num_tags := r.read_uvarint()
		for _ in 0 .. num_tags {
			tag := r.read_uvarint()
			size := int(r.read_uvarint())
			if tag == 0 {
				m.current_leader.read_from_versioned(mut r, version, flexible)!
			} else {
				data := r.span(size)
				if r.ok() {
					m.unknown_tags << UnknownTag{
						tag:  tag
						data: data.clone()
					}
				}
			}
		}
	}
	r.complete()!
}
